using System.Collections.Generic;

namespace GameData.Domains.Adventure;

public static class AdventureDomainHelper
{
	public static class DataIds
	{
		public const ushort EscapingRandomEnemies = 0;

		public const ushort Adventures = 1;

		public const ushort AdventureTaiwu = 2;

		public const ushort AdventureCache = 3;

		public const ushort AdventureMajorEvents = 4;

		public const ushort AdventureMajorEventTaiwu = 5;

		public const ushort AutoGenerateData = 6;
	}

	public static class MethodIds
	{
		public const ushort TryInvokeConfirmEnterEvent = 0;

		public const ushort GmCmd_GenerateAdventureRemake = 1;

		public const ushort ExitAdventureRemake = 2;

		public const ushort EnterAdventureRemake = 3;

		public const ushort MoveInAdventure = 4;

		public const ushort GmCmd_ChangeAdventureRemakeParameter = 5;

		public const ushort InteractElement = 6;

		public const ushort UseTemporaryItem = 7;

		public const ushort GmCmd_AdventureAddTemporaryItem = 8;

		public const ushort GmCmd_ReloadAdventureCore = 9;

		public const ushort AdventureCanEnter = 10;

		public const ushort PostEnterAdventureRemake = 11;

		public const ushort EnterMajorEvent = 12;

		public const ushort SelectMajorEvent = 13;

		public const ushort PostEnterMajorEvent = 14;

		public const ushort GmCmd_GenerateAdventureMajorEvent = 15;

		public const ushort AddProgress = 16;

		public const ushort FinishAdventure = 17;

		public const ushort GmCmd_ChangeAdventureRemakeElementParameter = 18;

		public const ushort SelectAndMarkCustomTextInvoked = 19;

		public const ushort GmCmd_RemoveAllAdventures = 20;

		public const ushort ConsumeActionPointInAdventure = 21;

		public const ushort GmCmd_ReGenerateAdventure = 22;
	}

	public const ushort DataCount = 7;

	public static readonly Dictionary<string, ushort> FieldName2DataId = new Dictionary<string, ushort>
	{
		{ "EscapingRandomEnemies", 0 },
		{ "Adventures", 1 },
		{ "AdventureTaiwu", 2 },
		{ "AdventureCache", 3 },
		{ "AdventureMajorEvents", 4 },
		{ "AdventureMajorEventTaiwu", 5 },
		{ "AutoGenerateData", 6 }
	};

	public static readonly string[] DataId2FieldName = new string[7] { "EscapingRandomEnemies", "Adventures", "AdventureTaiwu", "AdventureCache", "AdventureMajorEvents", "AdventureMajorEventTaiwu", "AutoGenerateData" };

	public static readonly string[][] DataId2ObjectFieldId2FieldName = new string[7][];

	public static readonly Dictionary<string, ushort> MethodName2MethodId = new Dictionary<string, ushort>
	{
		{ "TryInvokeConfirmEnterEvent", 0 },
		{ "GmCmd_GenerateAdventureRemake", 1 },
		{ "ExitAdventureRemake", 2 },
		{ "EnterAdventureRemake", 3 },
		{ "MoveInAdventure", 4 },
		{ "GmCmd_ChangeAdventureRemakeParameter", 5 },
		{ "InteractElement", 6 },
		{ "UseTemporaryItem", 7 },
		{ "GmCmd_AdventureAddTemporaryItem", 8 },
		{ "GmCmd_ReloadAdventureCore", 9 },
		{ "AdventureCanEnter", 10 },
		{ "PostEnterAdventureRemake", 11 },
		{ "EnterMajorEvent", 12 },
		{ "SelectMajorEvent", 13 },
		{ "PostEnterMajorEvent", 14 },
		{ "GmCmd_GenerateAdventureMajorEvent", 15 },
		{ "AddProgress", 16 },
		{ "FinishAdventure", 17 },
		{ "GmCmd_ChangeAdventureRemakeElementParameter", 18 },
		{ "SelectAndMarkCustomTextInvoked", 19 },
		{ "GmCmd_RemoveAllAdventures", 20 },
		{ "ConsumeActionPointInAdventure", 21 },
		{ "GmCmd_ReGenerateAdventure", 22 }
	};

	public static readonly string[] MethodId2MethodName = new string[23]
	{
		"TryInvokeConfirmEnterEvent", "GmCmd_GenerateAdventureRemake", "ExitAdventureRemake", "EnterAdventureRemake", "MoveInAdventure", "GmCmd_ChangeAdventureRemakeParameter", "InteractElement", "UseTemporaryItem", "GmCmd_AdventureAddTemporaryItem", "GmCmd_ReloadAdventureCore",
		"AdventureCanEnter", "PostEnterAdventureRemake", "EnterMajorEvent", "SelectMajorEvent", "PostEnterMajorEvent", "GmCmd_GenerateAdventureMajorEvent", "AddProgress", "FinishAdventure", "GmCmd_ChangeAdventureRemakeElementParameter", "SelectAndMarkCustomTextInvoked",
		"GmCmd_RemoveAllAdventures", "ConsumeActionPointInAdventure", "GmCmd_ReGenerateAdventure"
	};
}
