return {
	BackendPlugins = {
		[1] = "TaiwuDiagnostics.dll",
	},
	Title = "[天幕心帷]实时分析工具",
	Version = "0.1.0.0",
	Author = "man!",
	Description = "随游戏后端启动的本地实时分析工具，用于查看 SaveWorld、AdvanceMonth、缓存命中与 GameData 日志转发内容。",
	Source = 0,
	HasArchive = false,
	NeedRestartWhenSettingChanged = false,
	ChangeConfig = false,
	TagList = {
		[1] = "工具",
		[2] = "诊断",
	},
	GameVersion = "1.0.32.0",
	DefaultSettings = {
		[1] = {
			SettingType = "Toggle",
			Key = "EnableTaiwuDiagnosticsServer",
			DisplayName = "启用本地诊断服务",
			Description = "随游戏后端启动本地网页诊断面板。",
			GroupName = "太吾诊断",
			DefaultValue = true,
		},
		[2] = {
			SettingType = "Toggle",
			Key = "AutoOpenTaiwuDiagnosticsDashboard",
			DisplayName = "自动打开诊断页面",
			Description = "诊断服务就绪后自动在浏览器中打开本地页面。",
			GroupName = "太吾诊断",
			DefaultValue = false,
		},
		[3] = {
			SettingType = "Slider",
			Key = "TaiwuDiagnosticsPort",
			DisplayName = "诊断页面端口",
			Description = "本地 HTTP 服务端口；必须与 TaiwuOptimzation / TaiwuAILimitationRemoval 中的 TaiwuDiagnosticsPort 保持一致。可选范围 18580-18595。",
			GroupName = "太吾诊断",
			MinValue = 18580,
			MaxValue = 18595,
			StepSize = 1,
			DefaultValue = 18580,
		},
		[4] = {
			SettingType = "Toggle",
			Key = "CaptureSaveWorldDiagnostics",
			DisplayName = "采集存档写入细节",
			Description = "记录存档保存时的 Header、正文、Domain、数据库复制与压缩阶段耗时。",
			GroupName = "太吾诊断",
			DefaultValue = true,
		},
		[5] = {
			SettingType = "Toggle",
			Key = "CopySaveArchiveSnapshot",
			DisplayName = "保存存档快照副本",
			Description = "存档成功后复制一份归档文件到诊断目录，便于离线分析。",
			GroupName = "太吾诊断",
			DefaultValue = true,
		},
		[6] = {
			SettingType = "Slider",
			Key = "SaveArchiveSnapshotMaxCount",
			DisplayName = "存档快照保留数量",
			Description = "超过数量后自动清理较旧的诊断快照。",
			GroupName = "太吾诊断",
			MinValue = 1,
			MaxValue = 20,
			StepSize = 1,
			DefaultValue = 5,
		},
		[7] = {
			SettingType = "Toggle",
			Key = "CaptureAdvanceMonthPlanningDiagnostics",
			DisplayName = "采集过月行动规划细节",
			Description = "记录 NPC 过月行动规划、目标筛选、条件匹配与诊断缓存命中数据。",
			GroupName = "太吾诊断",
			DefaultValue = true,
		},
	},
	SettingGroups = {
		[1] = "太吾诊断",
	},
}
