using System;
using System.Collections.Generic;
using GameData.Adventure;
using GameData.Combat.Cricket;
using GameData.Domains.Combat;

namespace GameData.Serializer;

public static class ExtraSerializeAs
{
	public static readonly Dictionary<Type, Type> ExtraSerializeAsAttribute = new Dictionary<Type, Type>
	{
		{
			typeof(EAdventureParameterType),
			typeof(byte)
		},
		{
			typeof(ECricketCombatPropertyType),
			typeof(sbyte)
		},
		{
			typeof(DefeatMarkKey),
			typeof(int)
		},
		{
			typeof(EBuildingScaleEffect),
			typeof(int)
		}
	};

	public const string AutoGeneratedExtraSerializeAsString = "\nGameData.Adventure.EAdventureParameterType => byte\nGameData.Combat.Cricket.ECricketCombatPropertyType => sbyte\nGameData.Domains.Combat.DefeatMarkKey => int\nEBuildingScaleEffect => int\n";
}
