<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>TaiwuZstdSave.Backend</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>net8.0</TargetFramework>
    <PlatformTarget>x64</PlatformTarget>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>14.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup />
  <ItemGroup />
  <ItemGroup>
    <Reference Include="SQLite-net" />
    <Reference Include="ZstdNet">
      <HintPath>..\..\Plugins\ZstdNet.dll</HintPath>
    </Reference>
    <Reference Include="GameData.ArchiveData" />
    <Reference Include="0Harmony" />
    <Reference Include="System.Collections">
      <HintPath>..\..\..\..\..\..\..\..\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.25\System.Collections.dll</HintPath>
    </Reference>
    <Reference Include="System.IO.Compression">
      <HintPath>..\..\..\..\..\..\..\..\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.25\System.IO.Compression.dll</HintPath>
    </Reference>
    <Reference Include="System.IO.Hashing" />
    <Reference Include="TaiwuModdingLib" />
    <Reference Include="System.Runtime.InteropServices">
      <HintPath>..\..\..\..\..\..\..\..\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.25\System.Runtime.InteropServices.dll</HintPath>
    </Reference>
    <Reference Include="System.Memory">
      <HintPath>..\..\..\..\..\..\..\..\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.25\System.Memory.dll</HintPath>
    </Reference>
    <Reference Include="System.Threading">
      <HintPath>..\..\..\..\..\..\..\..\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.25\System.Threading.dll</HintPath>
    </Reference>
    <Reference Include="GameData.Utilities" />
    <Reference Include="GameData" />
  </ItemGroup>
</Project>