using System;
using System.Collections.Generic;
using Config.Common;

namespace Config;

[Serializable]
public class CharacterPropertyDisplay : ConfigData<CharacterPropertyDisplayItem, short>
{
	/// <summary>
	/// 配置表实例
	/// </summary>
	public static CharacterPropertyDisplay Instance = new CharacterPropertyDisplay();

	private readonly HashSet<string> RequiredFields = new HashSet<string> { "Name", "ShortName", "Desc", "TemplateId", "Type", "Icon", "TipsBigIcon", "TipsIcon", "PositiveColor", "NegativeColor" };

	internal override int ToInt(short value)
	{
		return value;
	}

	internal override short ToTemplateId(int value)
	{
		return (short)value;
	}

	private void CreateItems0()
	{
		_dataArray.Add(new CharacterPropertyDisplayItem(0, ECharacterPropertyDisplayType.Strength, LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Name_0"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "ShortName_0"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Desc_0"), "sp_icon_attribute_0", "mousetip_zhuyao_big_0", "ui9_icon_attribute_major_small_0", isPercent: false, "brightblue", "brightred", isInverse: false, 0, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(1, ECharacterPropertyDisplayType.Dexterity, LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Name_1"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "ShortName_1"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Desc_1"), "sp_icon_attribute_1", "mousetip_zhuyao_big_1", "ui9_icon_attribute_major_small_1", isPercent: false, "brightblue", "brightred", isInverse: false, 0, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(2, ECharacterPropertyDisplayType.Concentration, LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Name_2"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "ShortName_2"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Desc_2"), "sp_icon_attribute_2", "mousetip_zhuyao_big_2", "ui9_icon_attribute_major_small_2", isPercent: false, "brightblue", "brightred", isInverse: false, 0, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(3, ECharacterPropertyDisplayType.Vitality, LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Name_3"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "ShortName_3"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Desc_3"), "sp_icon_attribute_3", "mousetip_zhuyao_big_3", "ui9_icon_attribute_major_small_3", isPercent: false, "brightblue", "brightred", isInverse: false, 0, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(4, ECharacterPropertyDisplayType.Energy, LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Name_4"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "ShortName_4"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Desc_4"), "sp_icon_attribute_4", "mousetip_zhuyao_big_4", "ui9_icon_attribute_major_small_4", isPercent: false, "brightblue", "brightred", isInverse: false, 0, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(5, ECharacterPropertyDisplayType.Intelligence, LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Name_5"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "ShortName_5"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Desc_5"), "sp_icon_attribute_5", "mousetip_zhuyao_big_5", "ui9_icon_attribute_major_small_5", isPercent: false, "brightblue", "brightred", isInverse: false, 0, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(6, ECharacterPropertyDisplayType.HitRateStrength, LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Name_6"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "ShortName_6"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Desc_6"), "sp_icon_attribute_10", "mousetip_mingzhong_big_0", "ui9_icon_attribute_hit_small_0", isPercent: false, "brightblue", "brightred", isInverse: false, 0, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(7, ECharacterPropertyDisplayType.HitRateTechnique, LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Name_7"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "ShortName_7"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Desc_7"), "sp_icon_attribute_12", "mousetip_mingzhong_big_1", "ui9_icon_attribute_hit_small_1", isPercent: false, "brightblue", "brightred", isInverse: false, 0, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(8, ECharacterPropertyDisplayType.HitRateSpeed, LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Name_8"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "ShortName_8"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Desc_8"), "sp_icon_attribute_14", "mousetip_mingzhong_big_2", "ui9_icon_attribute_hit_small_2", isPercent: false, "brightblue", "brightred", isInverse: false, 0, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(9, ECharacterPropertyDisplayType.HitRateMind, LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Name_9"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "ShortName_9"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Desc_9"), "sp_icon_attribute_16", "mousetip_mingzhong_big_3", "ui9_icon_attribute_hit_small_3", isPercent: false, "brightblue", "brightred", isInverse: false, 0, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(10, ECharacterPropertyDisplayType.PenetrateOfOuter, LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Name_10"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "ShortName_10"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Desc_10"), "sp_icon_attribute_6", "mousetip_gongji_big_0", "ui9_icon_attribute_attack_small_0", isPercent: false, "brightblue", "brightred", isInverse: false, 0, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(11, ECharacterPropertyDisplayType.PenetrateOfInner, LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Name_11"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "ShortName_11"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Desc_11"), "sp_icon_attribute_7", "mousetip_gongji_big_1", "ui9_icon_attribute_attack_small_1", isPercent: false, "brightblue", "brightred", isInverse: false, 0, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(12, ECharacterPropertyDisplayType.AvoidRateStrength, LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Name_12"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "ShortName_12"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Desc_12"), "sp_icon_attribute_11", "mousetip_huajie_big_0", "ui9_icon_attribute_avoid_small_0", isPercent: false, "brightblue", "brightred", isInverse: false, 0, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(13, ECharacterPropertyDisplayType.AvoidRateTechnique, LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Name_13"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "ShortName_13"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Desc_13"), "sp_icon_attribute_13", "mousetip_huajie_big_1", "ui9_icon_attribute_avoid_small_1", isPercent: false, "brightblue", "brightred", isInverse: false, 0, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(14, ECharacterPropertyDisplayType.AvoidRateSpeed, LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Name_14"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "ShortName_14"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Desc_14"), "sp_icon_attribute_15", "mousetip_huajie_big_2", "ui9_icon_attribute_avoid_small_2", isPercent: false, "brightblue", "brightred", isInverse: false, 0, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(15, ECharacterPropertyDisplayType.AvoidRateMind, LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Name_15"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "ShortName_15"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Desc_15"), "sp_icon_attribute_17", "mousetip_huajie_big_3", "ui9_icon_attribute_avoid_small_3", isPercent: false, "brightblue", "brightred", isInverse: false, 0, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(16, ECharacterPropertyDisplayType.PenetrateResistOfOuter, LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Name_16"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "ShortName_16"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Desc_16"), "sp_icon_attribute_8", "mousetip_fangyu_big_0", "ui9_icon_attribute_defence_small_0", isPercent: false, "brightblue", "brightred", isInverse: false, 0, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(17, ECharacterPropertyDisplayType.PenetrateResistOfInner, LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Name_17"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "ShortName_17"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Desc_17"), "sp_icon_attribute_9", "mousetip_fangyu_big_1", "ui9_icon_attribute_defence_small_1", isPercent: false, "brightblue", "brightred", isInverse: false, 0, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(18, ECharacterPropertyDisplayType.RecoveryOfStance, LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Name_18"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "ShortName_18"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Desc_18"), "sp_icon_attribute_18", "mousetip_ciyao_big_0", "ui9_icon_attribute_minor_small_0", isPercent: false, "brightblue", "brightred", isInverse: false, 0, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(19, ECharacterPropertyDisplayType.RecoveryOfBreath, LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Name_19"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "ShortName_19"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Desc_19"), "sp_icon_attribute_18", "mousetip_ciyao_big_1", "ui9_icon_attribute_minor_small_1", isPercent: false, "brightblue", "brightred", isInverse: false, 0, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(20, ECharacterPropertyDisplayType.MoveSpeed, LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Name_20"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "ShortName_20"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Desc_20"), "sp_icon_attribute_19", "mousetip_ciyao_big_2", "ui9_icon_attribute_minor_small_2", isPercent: false, "brightblue", "brightred", isInverse: false, 0, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(21, ECharacterPropertyDisplayType.RecoveryOfFlaw, LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Name_21"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "ShortName_21"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Desc_21"), "sp_icon_attribute_19", "mousetip_ciyao_big_3", "ui9_icon_attribute_minor_small_3", isPercent: false, "brightblue", "brightred", isInverse: false, 0, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(22, ECharacterPropertyDisplayType.CastSpeed, LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Name_22"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "ShortName_22"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Desc_22"), "sp_icon_attribute_20", "mousetip_ciyao_big_4", "ui9_icon_attribute_minor_small_4", isPercent: false, "brightblue", "brightred", isInverse: false, 0, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(23, ECharacterPropertyDisplayType.RecoveryOfBlockedAcupoint, LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Name_23"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "ShortName_23"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Desc_23"), "sp_icon_attribute_20", "mousetip_ciyao_big_5", "ui9_icon_attribute_minor_small_5", isPercent: false, "brightblue", "brightred", isInverse: false, 0, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(24, ECharacterPropertyDisplayType.WeaponSwitchSpeed, LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Name_24"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "ShortName_24"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Desc_24"), "sp_icon_attribute_21", "mousetip_ciyao_big_6", "ui9_icon_attribute_minor_small_6", isPercent: false, "brightblue", "brightred", isInverse: false, 0, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(25, ECharacterPropertyDisplayType.AttackSpeed, LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Name_25"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "ShortName_25"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Desc_25"), "sp_icon_attribute_21", "mousetip_ciyao_big_7", "ui9_icon_attribute_minor_small_7", isPercent: false, "brightblue", "brightred", isInverse: false, 0, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(26, ECharacterPropertyDisplayType.InnerRatio, LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Name_26"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "ShortName_26"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Desc_26"), "sp_icon_attribute_22", "mousetip_ciyao_big_8", "ui9_icon_attribute_minor_small_8", isPercent: false, "brightblue", "brightred", isInverse: false, 0, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(27, ECharacterPropertyDisplayType.RecoveryOfQiDisorder, LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Name_27"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "ShortName_27"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Desc_27"), "sp_icon_attribute_22", "mousetip_ciyao_big_9", "ui9_icon_attribute_minor_small_9", isPercent: false, "brightblue", "brightred", isInverse: false, 0, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(28, ECharacterPropertyDisplayType.ResistOfHotPoison, LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Name_28"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "ShortName_28"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Desc_28"), "sp_icon_poison_0", "mousetip_duxing_big_0", "ui9_mousetip_icon_poison_0_0", isPercent: false, "brightblue", "brightred", isInverse: false, 0, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(29, ECharacterPropertyDisplayType.ResistOfGloomyPoison, LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Name_29"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "ShortName_29"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Desc_29"), "sp_icon_poison_1", "mousetip_duxing_big_1", "ui9_mousetip_icon_poison_1_0", isPercent: false, "brightblue", "brightred", isInverse: false, 0, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(30, ECharacterPropertyDisplayType.ResistOfColdPoison, LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Name_30"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "ShortName_30"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Desc_30"), "sp_icon_poison_2", "mousetip_duxing_big_2", "ui9_mousetip_icon_poison_2_0", isPercent: false, "brightblue", "brightred", isInverse: false, 0, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(31, ECharacterPropertyDisplayType.ResistOfRedPoison, LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Name_31"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "ShortName_31"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Desc_31"), "sp_icon_poison_3", "mousetip_duxing_big_3", "ui9_mousetip_icon_poison_3_0", isPercent: false, "brightblue", "brightred", isInverse: false, 0, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(32, ECharacterPropertyDisplayType.ResistOfRottenPoison, LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Name_32"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "ShortName_32"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Desc_32"), "sp_icon_poison_4", "mousetip_duxing_big_4", "ui9_mousetip_icon_poison_4_0", isPercent: false, "brightblue", "brightred", isInverse: false, 0, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(33, ECharacterPropertyDisplayType.ResistOfIllusoryPoison, LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Name_33"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "ShortName_33"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Desc_33"), "sp_icon_poison_5", "mousetip_duxing_big_5", "ui9_mousetip_icon_poison_5_0", isPercent: false, "brightblue", "brightred", isInverse: false, 0, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(34, ECharacterPropertyDisplayType.QualificationMusic, LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Name_34"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "ShortName_34"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Desc_34"), null, "mousetip_jiyi_big_0", "ui9_icon_craftsmanship_small_1_0", isPercent: false, "brightblue", "brightred", isInverse: false, 0, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(35, ECharacterPropertyDisplayType.QualificationChess, LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Name_35"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "ShortName_35"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Desc_35"), null, "mousetip_jiyi_big_1", "ui9_icon_craftsmanship_small_1_1", isPercent: false, "brightblue", "brightred", isInverse: false, 0, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(36, ECharacterPropertyDisplayType.QualificationPoem, LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Name_36"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "ShortName_36"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Desc_36"), null, "mousetip_jiyi_big_2", "ui9_icon_craftsmanship_small_1_2", isPercent: false, "brightblue", "brightred", isInverse: false, 0, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(37, ECharacterPropertyDisplayType.QualificationPainting, LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Name_37"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "ShortName_37"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Desc_37"), null, "mousetip_jiyi_big_3", "ui9_icon_craftsmanship_small_1_3", isPercent: false, "brightblue", "brightred", isInverse: false, 0, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(38, ECharacterPropertyDisplayType.QualificationMath, LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Name_38"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "ShortName_38"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Desc_38"), null, "mousetip_jiyi_big_4", "ui9_icon_craftsmanship_small_1_4", isPercent: false, "brightblue", "brightred", isInverse: false, 0, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(39, ECharacterPropertyDisplayType.QualificationAppraisal, LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Name_39"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "ShortName_39"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Desc_39"), null, "mousetip_jiyi_big_5", "ui9_icon_craftsmanship_small_1_5", isPercent: false, "brightblue", "brightred", isInverse: false, 0, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(40, ECharacterPropertyDisplayType.QualificationForging, LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Name_40"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "ShortName_40"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Desc_40"), null, "mousetip_jiyi_big_6", "ui9_icon_craftsmanship_small_1_6", isPercent: false, "brightblue", "brightred", isInverse: false, 0, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(41, ECharacterPropertyDisplayType.QualificationWoodworking, LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Name_41"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "ShortName_41"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Desc_41"), null, "mousetip_jiyi_big_7", "ui9_icon_craftsmanship_small_1_7", isPercent: false, "brightblue", "brightred", isInverse: false, 0, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(42, ECharacterPropertyDisplayType.QualificationMedicine, LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Name_42"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "ShortName_42"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Desc_42"), null, "mousetip_jiyi_big_8", "ui9_icon_craftsmanship_small_1_8", isPercent: false, "brightblue", "brightred", isInverse: false, 0, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(43, ECharacterPropertyDisplayType.QualificationToxicology, LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Name_43"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "ShortName_43"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Desc_43"), null, "mousetip_jiyi_big_9", "ui9_icon_craftsmanship_small_1_9", isPercent: false, "brightblue", "brightred", isInverse: false, 0, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(44, ECharacterPropertyDisplayType.QualificationWeaving, LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Name_44"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "ShortName_44"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Desc_44"), null, "mousetip_jiyi_big_10", "ui9_icon_craftsmanship_small_1_10", isPercent: false, "brightblue", "brightred", isInverse: false, 0, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(45, ECharacterPropertyDisplayType.QualificationJade, LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Name_45"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "ShortName_45"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Desc_45"), null, "mousetip_jiyi_big_11", "ui9_icon_craftsmanship_small_1_11", isPercent: false, "brightblue", "brightred", isInverse: false, 0, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(46, ECharacterPropertyDisplayType.QualificationTaoism, LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Name_46"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "ShortName_46"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Desc_46"), null, "mousetip_jiyi_big_12", "ui9_icon_craftsmanship_small_1_12", isPercent: false, "brightblue", "brightred", isInverse: false, 0, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(47, ECharacterPropertyDisplayType.QualificationBuddhism, LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Name_47"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "ShortName_47"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Desc_47"), null, "mousetip_jiyi_big_13", "ui9_icon_craftsmanship_small_1_13", isPercent: false, "brightblue", "brightred", isInverse: false, 0, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(48, ECharacterPropertyDisplayType.QualificationCooking, LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Name_48"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "ShortName_48"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Desc_48"), null, "mousetip_jiyi_big_14", "ui9_icon_craftsmanship_small_1_14", isPercent: false, "brightblue", "brightred", isInverse: false, 0, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(49, ECharacterPropertyDisplayType.QualificationEclectic, LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Name_49"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "ShortName_49"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Desc_49"), null, "mousetip_jiyi_big_15", "ui9_icon_craftsmanship_small_1_15", isPercent: false, "brightblue", "brightred", isInverse: false, 0, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(50, ECharacterPropertyDisplayType.AttainmentMusic, LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Name_50"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "ShortName_50"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Desc_50"), "sp_14_iconjiyizhanshi_0", "mousetip_jiyi_big_0", "ui9_icon_craftsmanship_small_1_0", isPercent: false, "brightblue", "brightred", isInverse: false, 0, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(51, ECharacterPropertyDisplayType.AttainmentChess, LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Name_51"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "ShortName_51"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Desc_51"), "sp_14_iconjiyizhanshi_1", "mousetip_jiyi_big_1", "ui9_icon_craftsmanship_small_1_1", isPercent: false, "brightblue", "brightred", isInverse: false, 0, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(52, ECharacterPropertyDisplayType.AttainmentPoem, LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Name_52"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "ShortName_52"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Desc_52"), "sp_14_iconjiyizhanshi_2", "mousetip_jiyi_big_2", "ui9_icon_craftsmanship_small_1_2", isPercent: false, "brightblue", "brightred", isInverse: false, 0, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(53, ECharacterPropertyDisplayType.AttainmentPainting, LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Name_53"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "ShortName_53"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Desc_53"), "sp_14_iconjiyizhanshi_3", "mousetip_jiyi_big_3", "ui9_icon_craftsmanship_small_1_3", isPercent: false, "brightblue", "brightred", isInverse: false, 0, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(54, ECharacterPropertyDisplayType.AttainmentMath, LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Name_54"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "ShortName_54"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Desc_54"), "sp_14_iconjiyizhanshi_4", "mousetip_jiyi_big_4", "ui9_icon_craftsmanship_small_1_4", isPercent: false, "brightblue", "brightred", isInverse: false, 0, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(55, ECharacterPropertyDisplayType.AttainmentAppraisal, LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Name_55"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "ShortName_55"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Desc_55"), "sp_14_iconjiyizhanshi_5", "mousetip_jiyi_big_5", "ui9_icon_craftsmanship_small_1_5", isPercent: false, "brightblue", "brightred", isInverse: false, 0, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(56, ECharacterPropertyDisplayType.AttainmentForging, LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Name_56"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "ShortName_56"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Desc_56"), "sp_14_iconjiyizhanshi_6", "mousetip_jiyi_big_6", "ui9_icon_craftsmanship_small_1_6", isPercent: false, "brightblue", "brightred", isInverse: false, 0, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(57, ECharacterPropertyDisplayType.AttainmentWoodworking, LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Name_57"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "ShortName_57"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Desc_57"), "sp_14_iconjiyizhanshi_7", "mousetip_jiyi_big_7", "ui9_icon_craftsmanship_small_1_7", isPercent: false, "brightblue", "brightred", isInverse: false, 0, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(58, ECharacterPropertyDisplayType.AttainmentMedicine, LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Name_58"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "ShortName_58"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Desc_58"), "sp_14_iconjiyizhanshi_10", "mousetip_jiyi_big_8", "ui9_icon_craftsmanship_small_1_8", isPercent: false, "brightblue", "brightred", isInverse: false, 0, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(59, ECharacterPropertyDisplayType.AttainmentToxicology, LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Name_59"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "ShortName_59"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Desc_59"), "sp_14_iconjiyizhanshi_11", "mousetip_jiyi_big_9", "ui9_icon_craftsmanship_small_1_9", isPercent: false, "brightblue", "brightred", isInverse: false, 0, isDisplaySpecially: false));
	}

	private void CreateItems1()
	{
		_dataArray.Add(new CharacterPropertyDisplayItem(60, ECharacterPropertyDisplayType.AttainmentWeaving, LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Name_60"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "ShortName_60"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Desc_60"), "sp_14_iconjiyizhanshi_9", "mousetip_jiyi_big_10", "ui9_icon_craftsmanship_small_1_10", isPercent: false, "brightblue", "brightred", isInverse: false, 0, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(61, ECharacterPropertyDisplayType.AttainmentJade, LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Name_61"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "ShortName_61"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Desc_61"), "sp_14_iconjiyizhanshi_8", "mousetip_jiyi_big_11", "ui9_icon_craftsmanship_small_1_11", isPercent: false, "brightblue", "brightred", isInverse: false, 0, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(62, ECharacterPropertyDisplayType.AttainmentTaoism, LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Name_62"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "ShortName_62"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Desc_62"), "sp_14_iconjiyizhanshi_12", "mousetip_jiyi_big_12", "ui9_icon_craftsmanship_small_1_12", isPercent: false, "brightblue", "brightred", isInverse: false, 0, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(63, ECharacterPropertyDisplayType.AttainmentBuddhism, LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Name_63"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "ShortName_63"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Desc_63"), "sp_14_iconjiyizhanshi_13", "mousetip_jiyi_big_13", "ui9_icon_craftsmanship_small_1_13", isPercent: false, "brightblue", "brightred", isInverse: false, 0, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(64, ECharacterPropertyDisplayType.AttainmentCooking, LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Name_64"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "ShortName_64"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Desc_64"), "sp_14_iconjiyizhanshi_14", "mousetip_jiyi_big_14", "ui9_icon_craftsmanship_small_1_14", isPercent: false, "brightblue", "brightred", isInverse: false, 0, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(65, ECharacterPropertyDisplayType.AttainmentEclectic, LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Name_65"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "ShortName_65"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Desc_65"), "sp_14_iconjiyizhanshi_15", "mousetip_jiyi_big_15", "ui9_icon_craftsmanship_small_1_15", isPercent: false, "brightblue", "brightred", isInverse: false, 0, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(66, ECharacterPropertyDisplayType.QualificationNeigong, LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Name_66"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "ShortName_66"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Desc_66"), null, "mousetip_gongfa_big_0", "ui9_icon_attainments_small_1_0", isPercent: false, "brightblue", "brightred", isInverse: false, 0, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(67, ECharacterPropertyDisplayType.QualificationPosing, LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Name_67"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "ShortName_67"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Desc_67"), null, "mousetip_gongfa_big_1", "ui9_icon_attainments_small_1_1", isPercent: false, "brightblue", "brightred", isInverse: false, 0, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(68, ECharacterPropertyDisplayType.QualificationStunt, LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Name_68"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "ShortName_68"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Desc_68"), null, "mousetip_gongfa_big_2", "ui9_icon_attainments_small_1_2", isPercent: false, "brightblue", "brightred", isInverse: false, 0, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(69, ECharacterPropertyDisplayType.QualificationFistAndPalm, LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Name_69"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "ShortName_69"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Desc_69"), null, "mousetip_gongfa_big_3", "ui9_icon_attainments_small_1_3", isPercent: false, "brightblue", "brightred", isInverse: false, 0, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(70, ECharacterPropertyDisplayType.QualificationFinger, LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Name_70"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "ShortName_70"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Desc_70"), null, "mousetip_gongfa_big_4", "ui9_icon_attainments_small_1_4", isPercent: false, "brightblue", "brightred", isInverse: false, 0, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(71, ECharacterPropertyDisplayType.QualificationLeg, LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Name_71"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "ShortName_71"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Desc_71"), null, "mousetip_gongfa_big_5", "ui9_icon_attainments_small_1_5", isPercent: false, "brightblue", "brightred", isInverse: false, 0, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(72, ECharacterPropertyDisplayType.QualificationThrow, LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Name_72"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "ShortName_72"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Desc_72"), null, "mousetip_gongfa_big_6", "ui9_icon_attainments_small_1_6", isPercent: false, "brightblue", "brightred", isInverse: false, 0, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(73, ECharacterPropertyDisplayType.QualificationSword, LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Name_73"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "ShortName_73"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Desc_73"), null, "mousetip_gongfa_big_7", "ui9_icon_attainments_small_1_7", isPercent: false, "brightblue", "brightred", isInverse: false, 0, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(74, ECharacterPropertyDisplayType.QualificationBlade, LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Name_74"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "ShortName_74"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Desc_74"), null, "mousetip_gongfa_big_8", "ui9_icon_attainments_small_1_8", isPercent: false, "brightblue", "brightred", isInverse: false, 0, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(75, ECharacterPropertyDisplayType.QualificationPolearm, LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Name_75"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "ShortName_75"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Desc_75"), null, "mousetip_gongfa_big_9", "ui9_icon_attainments_small_1_9", isPercent: false, "brightblue", "brightred", isInverse: false, 0, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(76, ECharacterPropertyDisplayType.QualificationSpecial, LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Name_76"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "ShortName_76"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Desc_76"), null, "mousetip_gongfa_big_10", "ui9_icon_attainments_small_1_10", isPercent: false, "brightblue", "brightred", isInverse: false, 0, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(77, ECharacterPropertyDisplayType.QualificationWhip, LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Name_77"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "ShortName_77"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Desc_77"), null, "mousetip_gongfa_big_11", "ui9_icon_attainments_small_1_11", isPercent: false, "brightblue", "brightred", isInverse: false, 0, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(78, ECharacterPropertyDisplayType.QualificationControllableShot, LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Name_78"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "ShortName_78"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Desc_78"), null, "mousetip_gongfa_big_12", "ui9_icon_attainments_small_1_12", isPercent: false, "brightblue", "brightred", isInverse: false, 0, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(79, ECharacterPropertyDisplayType.QualificationCombatMusic, LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Name_79"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "ShortName_79"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Desc_79"), null, "mousetip_gongfa_big_13", "ui9_icon_attainments_small_1_13", isPercent: false, "brightblue", "brightred", isInverse: false, 0, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(80, ECharacterPropertyDisplayType.AttainmentNeigong, LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Name_80"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "ShortName_80"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Desc_80"), "sp_18_iconwuxuezhanshi_0", "mousetip_gongfa_big_0", "ui9_icon_attainments_small_1_0", isPercent: false, "brightblue", "brightred", isInverse: false, 0, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(81, ECharacterPropertyDisplayType.AttainmentPosing, LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Name_81"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "ShortName_81"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Desc_81"), "sp_18_iconwuxuezhanshi_1", "mousetip_gongfa_big_1", "ui9_icon_attainments_small_1_1", isPercent: false, "brightblue", "brightred", isInverse: false, 0, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(82, ECharacterPropertyDisplayType.AttainmentStunt, LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Name_82"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "ShortName_82"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Desc_82"), "sp_18_iconwuxuezhanshi_2", "mousetip_gongfa_big_2", "ui9_icon_attainments_small_1_2", isPercent: false, "brightblue", "brightred", isInverse: false, 0, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(83, ECharacterPropertyDisplayType.AttainmentFistAndPalm, LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Name_83"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "ShortName_83"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Desc_83"), "sp_18_iconwuxuezhanshi_3", "mousetip_gongfa_big_3", "ui9_icon_attainments_small_1_3", isPercent: false, "brightblue", "brightred", isInverse: false, 0, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(84, ECharacterPropertyDisplayType.AttainmentFinger, LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Name_84"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "ShortName_84"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Desc_84"), "sp_18_iconwuxuezhanshi_4", "mousetip_gongfa_big_4", "ui9_icon_attainments_small_1_4", isPercent: false, "brightblue", "brightred", isInverse: false, 0, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(85, ECharacterPropertyDisplayType.AttainmentLeg, LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Name_85"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "ShortName_85"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Desc_85"), "sp_18_iconwuxuezhanshi_5", "mousetip_gongfa_big_5", "ui9_icon_attainments_small_1_5", isPercent: false, "brightblue", "brightred", isInverse: false, 0, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(86, ECharacterPropertyDisplayType.AttainmentThrow, LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Name_86"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "ShortName_86"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Desc_86"), "sp_18_iconwuxuezhanshi_6", "mousetip_gongfa_big_6", "ui9_icon_attainments_small_1_6", isPercent: false, "brightblue", "brightred", isInverse: false, 0, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(87, ECharacterPropertyDisplayType.AttainmentSword, LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Name_87"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "ShortName_87"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Desc_87"), "sp_18_iconwuxuezhanshi_7", "mousetip_gongfa_big_7", "ui9_icon_attainments_small_1_7", isPercent: false, "brightblue", "brightred", isInverse: false, 0, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(88, ECharacterPropertyDisplayType.AttainmentBlade, LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Name_88"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "ShortName_88"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Desc_88"), "sp_18_iconwuxuezhanshi_8", "mousetip_gongfa_big_8", "ui9_icon_attainments_small_1_8", isPercent: false, "brightblue", "brightred", isInverse: false, 0, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(89, ECharacterPropertyDisplayType.AttainmentPolearm, LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Name_89"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "ShortName_89"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Desc_89"), "sp_18_iconwuxuezhanshi_9", "mousetip_gongfa_big_9", "ui9_icon_attainments_small_1_9", isPercent: false, "brightblue", "brightred", isInverse: false, 0, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(90, ECharacterPropertyDisplayType.AttainmentSpecial, LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Name_90"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "ShortName_90"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Desc_90"), "sp_18_iconwuxuezhanshi_10", "mousetip_gongfa_big_10", "ui9_icon_attainments_small_1_10", isPercent: false, "brightblue", "brightred", isInverse: false, 0, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(91, ECharacterPropertyDisplayType.AttainmentWhip, LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Name_91"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "ShortName_91"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Desc_91"), "sp_18_iconwuxuezhanshi_11", "mousetip_gongfa_big_11", "ui9_icon_attainments_small_1_11", isPercent: false, "brightblue", "brightred", isInverse: false, 0, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(92, ECharacterPropertyDisplayType.AttainmentControllableShot, LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Name_92"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "ShortName_92"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Desc_92"), "sp_18_iconwuxuezhanshi_12", "mousetip_gongfa_big_12", "ui9_icon_attainments_small_1_12", isPercent: false, "brightblue", "brightred", isInverse: false, 0, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(93, ECharacterPropertyDisplayType.AttainmentCombatMusic, LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Name_93"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "ShortName_93"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Desc_93"), "sp_18_iconwuxuezhanshi_13", "mousetip_gongfa_big_13", "ui9_icon_attainments_small_1_13", isPercent: false, "brightblue", "brightred", isInverse: false, 0, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(94, ECharacterPropertyDisplayType.PersonalityCalm, LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Name_94"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "ShortName_94"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Desc_94"), "sp_personality_0", null, "mousetip_qiyuan_0", isPercent: false, "yellow", "yellow", isInverse: false, 0, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(95, ECharacterPropertyDisplayType.PersonalityClever, LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Name_95"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "ShortName_95"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Desc_95"), "sp_personality_1", null, "mousetip_qiyuan_1", isPercent: false, "yellow", "yellow", isInverse: false, 0, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(96, ECharacterPropertyDisplayType.PersonalityEnthusiastic, LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Name_96"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "ShortName_96"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Desc_96"), "sp_personality_2", null, "mousetip_qiyuan_2", isPercent: false, "yellow", "yellow", isInverse: false, 0, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(97, ECharacterPropertyDisplayType.PersonalityBrave, LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Name_97"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "ShortName_97"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Desc_97"), "sp_personality_3", null, "mousetip_qiyuan_3", isPercent: false, "yellow", "yellow", isInverse: false, 0, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(98, ECharacterPropertyDisplayType.PersonalityFirm, LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Name_98"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "ShortName_98"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Desc_98"), "sp_personality_4", null, "mousetip_qiyuan_4", isPercent: false, "yellow", "yellow", isInverse: false, 0, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(99, ECharacterPropertyDisplayType.PersonalityLucky, LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Name_99"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "ShortName_99"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Desc_99"), "sp_personality_5", null, "mousetip_qiyuan_5", isPercent: false, "yellow", "yellow", isInverse: false, 0, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(100, ECharacterPropertyDisplayType.PersonalityPerceptive, LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Name_100"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "ShortName_100"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Desc_100"), "sp_personality_6", null, "mousetip_qiyuan_6", isPercent: false, "yellow", "yellow", isInverse: false, 0, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(101, ECharacterPropertyDisplayType.Attraction, LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Name_101"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "ShortName_101"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Desc_101"), null, "mousetip_meili_big", "mousetip_meili", isPercent: false, "brightblue", "brightred", isInverse: false, 0, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(102, ECharacterPropertyDisplayType.Fertility, LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Name_102"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "ShortName_102"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Desc_102"), null, "mousetip_shengyu_big", "mousetip_shengyu", isPercent: false, "brightblue", "brightred", isInverse: false, 0, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(103, ECharacterPropertyDisplayType.HobbyChangingPeriod, LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Name_103"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "ShortName_103"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Desc_103"), null, "mousetip_xiwu_big", "mousetip_xiwu", isPercent: false, "yellow", "yellow", isInverse: false, 0, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(104, ECharacterPropertyDisplayType.Experience, LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Name_104"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "ShortName_104"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Desc_104"), "sp_icon_liliankuang", null, null, isPercent: false, null, null, isInverse: false, 0, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(105, ECharacterPropertyDisplayType.MaxHealth, LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Name_105"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "ShortName_105"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Desc_105"), null, "mousetip_shouming_big", "mousetip_shouming", isPercent: false, null, null, isInverse: false, 0, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(106, ECharacterPropertyDisplayType.MaxNeili, LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Name_106"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "ShortName_106"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Desc_106"), null, "mousetip_neilizongliang_big", "mousetip_neilizongliang", isPercent: false, null, null, isInverse: false, 0, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(107, ECharacterPropertyDisplayType.AttainmentDivinePower, LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Name_107"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "ShortName_107"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Desc_107"), "sp_18_iconwuxuezhanshi_14", "mousetip_gongfa_big_14", "mousetip_gongfa_14", isPercent: false, "brightblue", "brightred", isInverse: false, 0, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(108, ECharacterPropertyDisplayType.AttainmentGhostTechnique, LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Name_108"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "ShortName_108"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Desc_108"), "sp_18_iconwuxuezhanshi_15", "mousetip_gongfa_big_15", "mousetip_gongfa_15", isPercent: false, "brightblue", "brightred", isInverse: false, 0, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(109, ECharacterPropertyDisplayType.LifeSkillBookReadEfficiency, LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Name_109"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "ShortName_109"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Desc_109"), null, null, "mousetip_readingefficiency", isPercent: false, "brightblue", "brightred", isInverse: false, 0, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(110, ECharacterPropertyDisplayType.CombatSkillBookReadEfficiency, LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Name_110"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "ShortName_110"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Desc_110"), null, null, "mousetip_readingefficiency", isPercent: false, "brightblue", "brightred", isInverse: false, 0, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(111, ECharacterPropertyDisplayType.CombatSkillProficiency, LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Name_111"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "ShortName_111"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Desc_111"), null, "mousetip_actualcombat_big", "ui9_icon_mousetip_actualcombat_small", isPercent: false, "brightblue", "brightred", isInverse: false, 0, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(112, ECharacterPropertyDisplayType.CricketLuckPoint, LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Name_112"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "ShortName_112"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Desc_112"), null, null, null, isPercent: false, "brightblue", "brightred", isInverse: false, 0, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(113, ECharacterPropertyDisplayType.RecoveryStrength, LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Name_113"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "ShortName_113"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Desc_113"), "sp_icon_attribute_0", "mousetip_zhuyao_big_0", "mousetip_zhuyao_0", isPercent: false, "brightblue", "brightred", isInverse: false, 0, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(114, ECharacterPropertyDisplayType.RecoveryDexterity, LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Name_114"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "ShortName_114"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Desc_114"), "sp_icon_attribute_1", "mousetip_zhuyao_big_1", "mousetip_zhuyao_1", isPercent: false, "brightblue", "brightred", isInverse: false, 0, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(115, ECharacterPropertyDisplayType.RecoveryConcentration, LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Name_115"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "ShortName_115"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Desc_115"), "sp_icon_attribute_2", "mousetip_zhuyao_big_2", "mousetip_zhuyao_2", isPercent: false, "brightblue", "brightred", isInverse: false, 0, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(116, ECharacterPropertyDisplayType.RecoveryVitality, LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Name_116"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "ShortName_116"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Desc_116"), "sp_icon_attribute_3", "mousetip_zhuyao_big_3", "mousetip_zhuyao_3", isPercent: false, "brightblue", "brightred", isInverse: false, 0, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(117, ECharacterPropertyDisplayType.RecoveryEnergy, LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Name_117"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "ShortName_117"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Desc_117"), "sp_icon_attribute_4", "mousetip_zhuyao_big_4", "mousetip_zhuyao_4", isPercent: false, "brightblue", "brightred", isInverse: false, 0, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(118, ECharacterPropertyDisplayType.RecoveryIntelligence, LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Name_118"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "ShortName_118"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Desc_118"), "sp_icon_attribute_5", "mousetip_zhuyao_big_5", "mousetip_zhuyao_5", isPercent: false, "brightblue", "brightred", isInverse: false, 0, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(119, ECharacterPropertyDisplayType.BaseDamageStep, LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Name_119"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "ShortName_119"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Desc_119"), "sp_14_iconjiyizhanshi_12", "mousetip_jiyi_big_12", "mousetip_jiyi_12", isPercent: false, "brightblue", "brightred", isInverse: false, 0, isDisplaySpecially: false));
	}

	private void CreateItems2()
	{
		_dataArray.Add(new CharacterPropertyDisplayItem(120, ECharacterPropertyDisplayType.BreakStepNeigong, LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Name_120"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "ShortName_120"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Desc_120"), "sp_14_iconjiyizhanshi_12", "mousetip_gongfa_0_0_big", "mousetip_gongfa_0", isPercent: false, "brightblue", "brightred", isInverse: false, 0, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(121, ECharacterPropertyDisplayType.BreakStepPosing, LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Name_121"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "ShortName_121"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Desc_121"), "sp_14_iconjiyizhanshi_12", "mousetip_gongfa_0_1_big", "mousetip_gongfa_1", isPercent: false, "brightblue", "brightred", isInverse: false, 0, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(122, ECharacterPropertyDisplayType.BreakStepStunt, LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Name_122"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "ShortName_122"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Desc_122"), "sp_14_iconjiyizhanshi_12", "mousetip_gongfa_0_2_big", "mousetip_gongfa_2", isPercent: false, "brightblue", "brightred", isInverse: false, 0, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(123, ECharacterPropertyDisplayType.BreakStepFistAndPalm, LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Name_123"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "ShortName_123"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Desc_123"), "sp_14_iconjiyizhanshi_12", "mousetip_gongfa_0_3_big", "mousetip_gongfa_3", isPercent: false, "brightblue", "brightred", isInverse: false, 0, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(124, ECharacterPropertyDisplayType.BreakStepFinger, LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Name_124"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "ShortName_124"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Desc_124"), "sp_14_iconjiyizhanshi_12", "mousetip_gongfa_0_4_big", "mousetip_gongfa_4", isPercent: false, "brightblue", "brightred", isInverse: false, 0, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(125, ECharacterPropertyDisplayType.BreakStepLeg, LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Name_125"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "ShortName_125"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Desc_125"), "sp_14_iconjiyizhanshi_12", "mousetip_gongfa_0_5_big", "mousetip_gongfa_5", isPercent: false, "brightblue", "brightred", isInverse: false, 0, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(126, ECharacterPropertyDisplayType.BreakStepThrow, LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Name_126"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "ShortName_126"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Desc_126"), "sp_14_iconjiyizhanshi_12", "mousetip_gongfa_0_6_big", "mousetip_gongfa_6", isPercent: false, "brightblue", "brightred", isInverse: false, 0, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(127, ECharacterPropertyDisplayType.BreakStepSword, LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Name_127"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "ShortName_127"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Desc_127"), "sp_14_iconjiyizhanshi_12", "mousetip_gongfa_0_7_big", "mousetip_gongfa_7", isPercent: false, "brightblue", "brightred", isInverse: false, 0, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(128, ECharacterPropertyDisplayType.BreakStepBlade, LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Name_128"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "ShortName_128"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Desc_128"), "sp_14_iconjiyizhanshi_12", "mousetip_gongfa_0_8_big", "mousetip_gongfa_8", isPercent: false, "brightblue", "brightred", isInverse: false, 0, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(129, ECharacterPropertyDisplayType.BreakStepPolearm, LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Name_129"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "ShortName_129"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Desc_129"), "sp_14_iconjiyizhanshi_12", "mousetip_gongfa_0_9_big", "mousetip_gongfa_9", isPercent: false, "brightblue", "brightred", isInverse: false, 0, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(130, ECharacterPropertyDisplayType.BreakStepSpecial, LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Name_130"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "ShortName_130"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Desc_130"), "sp_14_iconjiyizhanshi_12", "mousetip_gongfa_0_10_big", "mousetip_gongfa_10", isPercent: false, "brightblue", "brightred", isInverse: false, 0, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(131, ECharacterPropertyDisplayType.BreakStepWhip, LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Name_131"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "ShortName_131"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Desc_131"), "sp_14_iconjiyizhanshi_12", "mousetip_gongfa_0_11_big", "mousetip_gongfa_11", isPercent: false, "brightblue", "brightred", isInverse: false, 0, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(132, ECharacterPropertyDisplayType.BreakStepControllableShot, LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Name_132"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "ShortName_132"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Desc_132"), "sp_14_iconjiyizhanshi_12", "mousetip_gongfa_0_12_big", "mousetip_gongfa_12", isPercent: false, "brightblue", "brightred", isInverse: false, 0, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(133, ECharacterPropertyDisplayType.BreakStepCombatMusic, LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Name_133"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "ShortName_133"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Desc_133"), "sp_14_iconjiyizhanshi_12", "mousetip_gongfa_0_13_big", "mousetip_gongfa_13", isPercent: false, "brightblue", "brightred", isInverse: false, 0, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(134, ECharacterPropertyDisplayType.ConfessingLoveSuccessOdds, LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Name_134"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "ShortName_134"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Desc_134"), "sp_14_iconjiyizhanshi_12", "mousetip_jiyi_big_12", "mousetip_jiyi_12", isPercent: false, "brightblue", "brightred", isInverse: false, 0, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(135, ECharacterPropertyDisplayType.InnateGenericGrid, LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Name_135"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "ShortName_135"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Desc_135"), "sp_14_iconjiyizhanshi_12", "mousetip_jiyi_big_12", "ui9_icon_tip_generic_grid", isPercent: false, "brightblue", "brightred", isInverse: false, 0, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(136, ECharacterPropertyDisplayType.MysteryItemCompatibility, LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Name_136"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "ShortName_136"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Desc_136"), null, "ui9_icon_mouse_tip_qihe_big", "ui9_icon_mouse_tip_qihe_small", isPercent: false, "brightblue", "brightred", isInverse: false, 0, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(137, ECharacterPropertyDisplayType.SkillPowerNeigong, LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Name_137"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "ShortName_137"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Desc_137"), "sp_14_iconjiyizhanshi_12", "mousetip_zhenqi_big_5", "mousetip_zhenqi_5", isPercent: false, "brightblue", "brightred", isInverse: false, 0, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(138, ECharacterPropertyDisplayType.SkillPowerAttack, LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Name_138"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "ShortName_138"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Desc_138"), "sp_14_iconjiyizhanshi_12", "mousetip_zhenqi_big_0", "mousetip_zhenqi_0", isPercent: false, "brightblue", "brightred", isInverse: false, 0, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(139, ECharacterPropertyDisplayType.SkillPowerAgile, LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Name_139"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "ShortName_139"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Desc_139"), "sp_14_iconjiyizhanshi_12", "mousetip_zhenqi_big_1", "mousetip_zhenqi_1", isPercent: false, "brightblue", "brightred", isInverse: false, 0, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(140, ECharacterPropertyDisplayType.SkillPowerDefense, LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Name_140"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "ShortName_140"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Desc_140"), "sp_14_iconjiyizhanshi_12", "mousetip_zhenqi_big_2", "mousetip_zhenqi_2", isPercent: false, "brightblue", "brightred", isInverse: false, 0, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(141, ECharacterPropertyDisplayType.SkillPowerAssist, LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Name_141"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "ShortName_141"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Desc_141"), "sp_14_iconjiyizhanshi_12", "mousetip_zhenqi_big_3", "mousetip_zhenqi_3", isPercent: false, "brightblue", "brightred", isInverse: false, 0, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(142, ECharacterPropertyDisplayType.BaseDamageStepOuterHead, LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Name_142"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "ShortName_142"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Desc_142"), "sp_14_iconjiyizhanshi_12", "mousetip_waishang_big_0", "mousetip_waishang_0", isPercent: false, "brightblue", "brightred", isInverse: false, 0, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(143, ECharacterPropertyDisplayType.BaseDamageStepOuterChest, LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Name_143"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "ShortName_143"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Desc_143"), "sp_14_iconjiyizhanshi_12", "mousetip_waishang_big_1", "mousetip_waishang_1", isPercent: false, "brightblue", "brightred", isInverse: false, 0, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(144, ECharacterPropertyDisplayType.BaseDamageStepOuterHand, LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Name_144"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "ShortName_144"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Desc_144"), "sp_14_iconjiyizhanshi_12", "mousetip_waishang_big_7", "mousetip_waishang_7", isPercent: false, "brightblue", "brightred", isInverse: false, 0, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(145, ECharacterPropertyDisplayType.BaseDamageStepOuterBelly, LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Name_145"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "ShortName_145"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Desc_145"), "sp_14_iconjiyizhanshi_12", "mousetip_waishang_big_2", "mousetip_waishang_2", isPercent: false, "brightblue", "brightred", isInverse: false, 0, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(146, ECharacterPropertyDisplayType.BaseDamageStepOuterLeg, LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Name_146"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "ShortName_146"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Desc_146"), "sp_14_iconjiyizhanshi_12", "mousetip_waishang_big_8", "mousetip_waishang_8", isPercent: false, "brightblue", "brightred", isInverse: false, 0, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(147, ECharacterPropertyDisplayType.BaseDamageStepInnerHead, LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Name_147"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "ShortName_147"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Desc_147"), "sp_14_iconjiyizhanshi_12", "mousetip_neishang_big_0", "mousetip_neishang_0", isPercent: false, "brightblue", "brightred", isInverse: false, 0, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(148, ECharacterPropertyDisplayType.BaseDamageStepInnerChest, LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Name_148"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "ShortName_148"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Desc_148"), "sp_14_iconjiyizhanshi_12", "mousetip_neishang_big_1", "mousetip_neishang_1", isPercent: false, "brightblue", "brightred", isInverse: false, 0, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(149, ECharacterPropertyDisplayType.BaseDamageStepInnerHand, LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Name_149"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "ShortName_149"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Desc_149"), "sp_14_iconjiyizhanshi_12", "mousetip_neishang_big_7", "mousetip_neishang_7", isPercent: false, "brightblue", "brightred", isInverse: false, 0, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(150, ECharacterPropertyDisplayType.BaseDamageStepInnerBelly, LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Name_150"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "ShortName_150"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Desc_150"), "sp_14_iconjiyizhanshi_12", "mousetip_neishang_big_2", "mousetip_neishang_2", isPercent: false, "brightblue", "brightred", isInverse: false, 0, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(151, ECharacterPropertyDisplayType.BaseDamageStepInnerLeg, LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Name_151"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "ShortName_151"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Desc_151"), "sp_14_iconjiyizhanshi_12", "mousetip_neishang_big_8", "mousetip_neishang_8", isPercent: false, "brightblue", "brightred", isInverse: false, 0, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(152, ECharacterPropertyDisplayType.BaseDamageStepFatal, LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Name_152"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "ShortName_152"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Desc_152"), "sp_14_iconjiyizhanshi_12", "mousetip_zhongchuang_big", "mousetip_zhongchuang_0", isPercent: false, "brightblue", "brightred", isInverse: false, 0, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(153, ECharacterPropertyDisplayType.BaseDamageStepMind, LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Name_153"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "ShortName_153"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Desc_153"), "sp_14_iconjiyizhanshi_12", "mousetip_dongxin_big", "mousetip_dongxin_0", isPercent: false, "brightblue", "brightred", isInverse: false, 0, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(154, ECharacterPropertyDisplayType.Wisdom, LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Name_154"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "ShortName_154"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Desc_154"), "sp_14_iconjiyizhanshi_12", "sp_icon_renwutexing_2", "mousetip_characteristic_2", isPercent: false, "brightblue", "brightred", isInverse: false, 0, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(155, ECharacterPropertyDisplayType.NeiliAllocationAddSpeed, LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Name_155"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "ShortName_155"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Desc_155"), "sp_14_iconjiyizhanshi_12", "mousetip_zhenqi_big_4", "mousetip_zhenqi_4", isPercent: false, "brightblue", "brightred", isInverse: false, 0, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(156, ECharacterPropertyDisplayType.NeiliAllocationReduceSpeed, LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Name_156"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "ShortName_156"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Desc_156"), "sp_14_iconjiyizhanshi_12", "mousetip_zhenqi_big_4", "mousetip_zhenqi_4", isPercent: false, "brightblue", "brightred", isInverse: false, 0, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(157, ECharacterPropertyDisplayType.SkillSlotCountNeigong, LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Name_157"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "ShortName_157"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Desc_157"), "sp_14_iconjiyizhanshi_12", "mousetip_zhenqi_big_5", "mousetip_zhenqi_5", isPercent: false, "brightblue", "brightred", isInverse: false, 0, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(158, ECharacterPropertyDisplayType.SkillSlotCountAttack, LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Name_158"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "ShortName_158"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Desc_158"), "sp_14_iconjiyizhanshi_12", "mousetip_zhenqi_big_0", "mousetip_zhenqi_0", isPercent: false, "brightblue", "brightred", isInverse: false, 0, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(159, ECharacterPropertyDisplayType.SkillSlotCountAgile, LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Name_159"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "ShortName_159"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Desc_159"), "sp_14_iconjiyizhanshi_12", "mousetip_zhenqi_big_1", "mousetip_zhenqi_1", isPercent: false, "brightblue", "brightred", isInverse: false, 0, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(160, ECharacterPropertyDisplayType.SkillSlotCountDefense, LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Name_160"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "ShortName_160"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Desc_160"), "sp_14_iconjiyizhanshi_12", "mousetip_zhenqi_big_2", "mousetip_zhenqi_2", isPercent: false, "brightblue", "brightred", isInverse: false, 0, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(161, ECharacterPropertyDisplayType.SkillSlotCountAssist, LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Name_161"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "ShortName_161"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Desc_161"), "sp_14_iconjiyizhanshi_12", "mousetip_zhenqi_big_3", "mousetip_zhenqi_3", isPercent: false, "brightblue", "brightred", isInverse: false, 0, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(162, ECharacterPropertyDisplayType.EquipmentDefense, LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Name_162"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "ShortName_162"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Desc_162"), null, "ui9_mousetip_attribute_big_jianren", "ui9_mousetip_attribute_jianren", isPercent: true, "brightblue", "brightred", isInverse: false, 0, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(163, ECharacterPropertyDisplayType.EquipmentWeaponAttack, LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Name_163"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "ShortName_163"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Desc_163"), null, "ui9_mousetip_attribute_big_pojia", "ui9_mousetip_attribute_pojia", isPercent: true, "brightblue", "brightred", isInverse: false, 0, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(164, ECharacterPropertyDisplayType.EquipmentArmorAttack, LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Name_164"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "ShortName_164"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Desc_164"), null, "ui9_mousetip_attribute_big_poren", "ui9_mousetip_attribute_poren", isPercent: true, "brightblue", "brightred", isInverse: false, 0, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(165, ECharacterPropertyDisplayType.EquipmentWeight, LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Name_165"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "ShortName_165"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Desc_165"), null, "ui9_mousetip_attribute_big_zhongliang", "ui9_mousetip_attribute_zhongliiang", isPercent: true, "brightblue", "brightred", isInverse: true, 0, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(166, ECharacterPropertyDisplayType.EquipmentMaxDurability, LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Name_166"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "ShortName_166"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Desc_166"), null, "ui9_mousetip_equipment_big_2", "mousetip_naijiu", isPercent: true, "brightblue", "brightred", isInverse: false, 0, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(167, ECharacterPropertyDisplayType.EquipmentPenetration, LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Name_167"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "ShortName_167"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Desc_167"), null, "ui9_mousetip_attribute_big_gongji", "ui9_mousetip_attribute_gongji", isPercent: true, "brightblue", "brightred", isInverse: false, 0, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(168, ECharacterPropertyDisplayType.EquipmentPenetrationResist, LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Name_168"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "ShortName_168"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Desc_168"), null, "ui9_mousetip_attribute_big_fangyu", "ui9_mousetip_attribute_fangyu", isPercent: true, "brightblue", "brightred", isInverse: false, 0, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(169, ECharacterPropertyDisplayType.EquipmentPursueAttackFactor, LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Name_169"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "ShortName_169"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Desc_169"), null, "ui9_mousetip_attribute_big_zhuiji", "ui9_mousetip_attribute_zhuiji", isPercent: true, "brightblue", "brightred", isInverse: false, 0, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(170, ECharacterPropertyDisplayType.EquipmentChangeTrickPercent, LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Name_170"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "ShortName_170"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Desc_170"), null, "ui9_mousetip_attribute_big_bianzhao", "ui9_mousetip_attribute_bianzhao", isPercent: true, "brightblue", "brightred", isInverse: false, 0, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(171, ECharacterPropertyDisplayType.EquipmentInjuryFactorOuter, LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Name_171"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "ShortName_171"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Desc_171"), null, "ui9_mousetip_attribute_big_waishangjiangdi", "ui9_mousetip_attribute_waishangjiangdi", isPercent: true, "brightblue", "brightred", isInverse: false, 0, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(172, ECharacterPropertyDisplayType.EquipmentInjuryFactorInner, LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Name_172"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "ShortName_172"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Desc_172"), null, "ui9_mousetip_attribute_big_neishangjiangdi", "ui9_mousetip_attribute_neishangjiangdi", isPercent: true, "brightblue", "brightred", isInverse: false, 0, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(173, ECharacterPropertyDisplayType.EquipmentCounterAttackPower, LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Name_173"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "ShortName_173"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Desc_173"), null, "ui9_mousetip_attribute_big_fanzhenweili", "ui9_mousetip_attribute_fanzhenweili", isPercent: true, "brightblue", "brightred", isInverse: false, 0, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(174, ECharacterPropertyDisplayType.EquipmentCounterDamagePower, LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Name_174"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "ShortName_174"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Desc_174"), null, "ui9_mousetip_attribute_big_fanjiweili", "ui9_mousetip_attribute_fanjiweili", isPercent: true, "brightblue", "brightred", isInverse: false, 0, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(175, ECharacterPropertyDisplayType.EquipmentMinAttackRange, LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Name_175"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "ShortName_175"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Desc_175"), null, "ui9_mousetip_attribute_big_mingongjifanwei", "ui9_mousetip_attribute_mingongjifanwei", isPercent: false, "brightblue", "brightred", isInverse: false, 0, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(176, ECharacterPropertyDisplayType.EquipmentMaxAttackRange, LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Name_176"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "ShortName_176"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Desc_176"), null, "ui9_mousetip_attribute_big_maxgongjifanwei", "ui9_mousetip_attribute_maxgongjifanwei", isPercent: false, "brightblue", "brightred", isInverse: false, 0, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(177, ECharacterPropertyDisplayType.EquipmentMaxPower, LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Name_177"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "ShortName_177"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Desc_177"), null, "ui9_mousetip_attribute_maxpower", "ui9_mousetip_maxpower", isPercent: true, "brightblue", "brightred", isInverse: false, 0, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(178, ECharacterPropertyDisplayType.EquipmentUseRequirement, LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Name_178"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "ShortName_178"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Desc_178"), null, "ui9_mousetip_attribute_requirements", "ui9_mousetip_requirements", isPercent: true, "brightblue", "brightred", isInverse: true, 0, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(179, ECharacterPropertyDisplayType.EquipmentWeaponHitRateStrength, LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Name_179"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "ShortName_179"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Desc_179"), "sp_icon_attribute_10", "mousetip_mingzhong_big_0", "ui9_icon_attribute_hit_small_0", isPercent: true, "brightblue", "brightred", isInverse: false, 0, isDisplaySpecially: false));
	}

	private void CreateItems3()
	{
		_dataArray.Add(new CharacterPropertyDisplayItem(180, ECharacterPropertyDisplayType.EquipmentWeaponHitRateTechnique, LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Name_180"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "ShortName_180"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Desc_180"), "sp_icon_attribute_12", "mousetip_mingzhong_big_1", "ui9_icon_attribute_hit_small_1", isPercent: true, "brightblue", "brightred", isInverse: false, 0, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(181, ECharacterPropertyDisplayType.EquipmentWeaponHitRateSpeed, LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Name_181"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "ShortName_181"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Desc_181"), "sp_icon_attribute_14", "mousetip_mingzhong_big_2", "ui9_icon_attribute_hit_small_2", isPercent: true, "brightblue", "brightred", isInverse: false, 0, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(182, ECharacterPropertyDisplayType.EquipmentWeaponHitRateMind, LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Name_182"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "ShortName_182"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Desc_182"), "sp_icon_attribute_16", "mousetip_mingzhong_big_3", "ui9_icon_attribute_hit_small_3", isPercent: true, "brightblue", "brightred", isInverse: false, 0, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(183, ECharacterPropertyDisplayType.EquipmentArmorAvoidRateStrength, LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Name_183"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "ShortName_183"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Desc_183"), "sp_icon_attribute_11", "mousetip_huajie_big_0", "ui9_icon_attribute_avoid_small_0", isPercent: true, "brightblue", "brightred", isInverse: false, 0, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(184, ECharacterPropertyDisplayType.EquipmentArmorAvoidRateTechnique, LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Name_184"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "ShortName_184"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Desc_184"), "sp_icon_attribute_13", "mousetip_huajie_big_1", "ui9_icon_attribute_avoid_small_1", isPercent: true, "brightblue", "brightred", isInverse: false, 0, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(185, ECharacterPropertyDisplayType.EquipmentArmorAvoidRateSpeed, LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Name_185"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "ShortName_185"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Desc_185"), "sp_icon_attribute_15", "mousetip_huajie_big_2", "ui9_icon_attribute_avoid_small_2", isPercent: true, "brightblue", "brightred", isInverse: false, 0, isDisplaySpecially: false));
		_dataArray.Add(new CharacterPropertyDisplayItem(186, ECharacterPropertyDisplayType.EquipmentArmorAvoidRateMind, LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Name_186"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "ShortName_186"), LocalStringManager.GetConfig("CharacterPropertyDisplay_language", "Desc_186"), "sp_icon_attribute_17", "mousetip_huajie_big_3", "ui9_icon_attribute_avoid_small_3", isPercent: true, "brightblue", "brightred", isInverse: false, 0, isDisplaySpecially: false));
	}

	public override void Init()
	{
		base.Init();
		_dataArray = new List<CharacterPropertyDisplayItem>(187);
		CreateItems0();
		CreateItems1();
		CreateItems2();
		CreateItems3();
	}
}
