using System;
using System.Collections.Generic;
using Config.Common;

namespace Config;

[Serializable]
public class LifeSkillCombatEffect : ConfigData<LifeSkillCombatEffectItem, sbyte>
{
	public static LifeSkillCombatEffect Instance = new LifeSkillCombatEffect();

	private readonly HashSet<string> RequiredFields = new HashSet<string>
	{
		"Name", "Desc", "BanCardList", "TemplateId", "BaseAmount", "MaxAmount", "UsedCount", "Level", "Type", "Group",
		"BehaviorTypeAmounts", "SubEffect", "SubEffectParameters", "Imgae"
	};

	internal override int ToInt(sbyte value)
	{
		return value;
	}

	internal override sbyte ToTemplateId(int value)
	{
		return (sbyte)value;
	}

	private void CreateItems0()
	{
		_dataArray.Add(new LifeSkillCombatEffectItem(0, LocalStringManager.GetConfig("LifeSkillCombatEffect_language", "Name_0"), LocalStringManager.GetConfig("LifeSkillCombatEffect_language", "Desc_0"), 3, 3, 2, 0, ELifeSkillCombatEffectType.Common, ELifeSkillCombatEffectGroup.FlexibleFall, isInstant: false, isSelectGrid: false, isSelectBook: false, isSaveCard: false, isDecideAddEffect: false, isGetPointAddEffect: false, new List<sbyte>
		{
			1, 2, 9, 11, 10, 4, 21, 23, 22, 24,
			26
		}, new sbyte[5] { 0, 0, 3, 0, 0 }, new sbyte[5] { 0, 0, 30, 0, 0 }, ELifeSkillCombatEffectSubEffect.SelfExtraQuestionAroundHouseThesisLow, new sbyte[5] { -1, 1, 1, 0, 0 }, "lifeskillcombat_chahua_0"));
		_dataArray.Add(new LifeSkillCombatEffectItem(1, LocalStringManager.GetConfig("LifeSkillCombatEffect_language", "Name_1"), LocalStringManager.GetConfig("LifeSkillCombatEffect_language", "Desc_1"), 3, 3, 2, 0, ELifeSkillCombatEffectType.Common, ELifeSkillCombatEffectGroup.FlexibleFall, isInstant: false, isSelectGrid: false, isSelectBook: false, isSaveCard: false, isDecideAddEffect: false, isGetPointAddEffect: false, new List<sbyte>
		{
			0, 2, 9, 11, 10, 4, 21, 23, 22, 24,
			26
		}, new sbyte[5] { 3, 3, 0, 0, 0 }, new sbyte[5] { 0, 0, 30, 0, 0 }, ELifeSkillCombatEffectSubEffect.SelfExtraQuestionAroundHouseThesisBreakWhenAdversaryThesisHigh, new sbyte[5] { 1, 127, 0, 0, 0 }, "lifeskillcombat_chahua_1"));
		_dataArray.Add(new LifeSkillCombatEffectItem(2, LocalStringManager.GetConfig("LifeSkillCombatEffect_language", "Name_2"), LocalStringManager.GetConfig("LifeSkillCombatEffect_language", "Desc_2"), 3, 3, 2, 0, ELifeSkillCombatEffectType.Common, ELifeSkillCombatEffectGroup.FlexibleFall, isInstant: false, isSelectGrid: false, isSelectBook: false, isSaveCard: false, isDecideAddEffect: false, isGetPointAddEffect: false, new List<sbyte>
		{
			1, 0, 9, 11, 10, 4, 21, 23, 22, 24,
			26
		}, new sbyte[5] { 0, 0, 0, 3, 3 }, new sbyte[5] { 0, 0, 30, 0, 0 }, ELifeSkillCombatEffectSubEffect.SelfExtraQuestionAroundHouseThesisBreakWhenAdversaryThesisHigh, new sbyte[5] { 1, 0, 127, 0, 0 }, "lifeskillcombat_chahua_2"));
		_dataArray.Add(new LifeSkillCombatEffectItem(3, LocalStringManager.GetConfig("LifeSkillCombatEffect_language", "Name_3"), LocalStringManager.GetConfig("LifeSkillCombatEffect_language", "Desc_3"), 2, 3, 1, 0, ELifeSkillCombatEffectType.BUFF, ELifeSkillCombatEffectGroup.ReinforceArgument, isInstant: false, isSelectGrid: false, isSelectBook: false, isSaveCard: true, isDecideAddEffect: false, isGetPointAddEffect: true, new List<sbyte> { 5, 4, 7, 8, 6 }, new sbyte[5] { 3, 3, 0, 0, 0 }, new sbyte[5] { 0, 0, 0, 0, 30 }, ELifeSkillCombatEffectSubEffect.SelfThesisChangeAroundHouseActivePointWithParam, new sbyte[5] { 1, 1, 1, 10, 0 }, "lifeskillcombat_chahua_6"));
		_dataArray.Add(new LifeSkillCombatEffectItem(4, LocalStringManager.GetConfig("LifeSkillCombatEffect_language", "Name_4"), LocalStringManager.GetConfig("LifeSkillCombatEffect_language", "Desc_4"), 2, 3, 2, 0, ELifeSkillCombatEffectType.BUFF, ELifeSkillCombatEffectGroup.ReinforceArgument, isInstant: false, isSelectGrid: false, isSelectBook: false, isSaveCard: false, isDecideAddEffect: false, isGetPointAddEffect: false, new List<sbyte>
		{
			0, 1, 2, 9, 10, 21, 23, 3, 5, 7,
			8, 6
		}, new sbyte[5] { 3, 3, 0, 0, 0 }, new sbyte[5] { 0, 0, 0, 0, 30 }, ELifeSkillCombatEffectSubEffect.PointChange, new sbyte[5] { 0, 0, 0, 20, 0 }, "lifeskillcombat_chahua_7"));
		_dataArray.Add(new LifeSkillCombatEffectItem(5, LocalStringManager.GetConfig("LifeSkillCombatEffect_language", "Name_5"), LocalStringManager.GetConfig("LifeSkillCombatEffect_language", "Desc_5"), 2, 3, 1, 0, ELifeSkillCombatEffectType.BUFF, ELifeSkillCombatEffectGroup.ReinforceArgument, isInstant: false, isSelectGrid: false, isSelectBook: false, isSaveCard: true, isDecideAddEffect: false, isGetPointAddEffect: true, new List<sbyte> { 3, 4, 7, 8, 6 }, new sbyte[5] { 3, 3, 0, 0, 0 }, new sbyte[5] { 0, 0, 0, 0, 30 }, ELifeSkillCombatEffectSubEffect.SelfThesisChangeAroundHouseActivePointWithParam, new sbyte[5] { 1, 127, 0, 10, 0 }, "lifeskillcombat_chahua_8"));
		_dataArray.Add(new LifeSkillCombatEffectItem(6, LocalStringManager.GetConfig("LifeSkillCombatEffect_language", "Name_6"), LocalStringManager.GetConfig("LifeSkillCombatEffect_language", "Desc_6"), 2, 3, 2, 0, ELifeSkillCombatEffectType.BUFF, ELifeSkillCombatEffectGroup.WeakenArgument, isInstant: false, isSelectGrid: false, isSelectBook: false, isSaveCard: false, isDecideAddEffect: true, isGetPointAddEffect: false, new List<sbyte> { 3, 5, 4, 7, 8 }, new sbyte[5] { 0, 0, 0, 3, 3 }, new sbyte[5] { 0, 0, 0, 30, 0 }, ELifeSkillCombatEffectSubEffect.SelfTrapedInCell, new sbyte[5] { -1, 0, 0, -20, 0 }, "lifeskillcombat_chahua_9"));
		_dataArray.Add(new LifeSkillCombatEffectItem(7, LocalStringManager.GetConfig("LifeSkillCombatEffect_language", "Name_7"), LocalStringManager.GetConfig("LifeSkillCombatEffect_language", "Desc_7"), 2, 3, 1, 0, ELifeSkillCombatEffectType.BUFF, ELifeSkillCombatEffectGroup.WeakenArgument, isInstant: false, isSelectGrid: false, isSelectBook: false, isSaveCard: true, isDecideAddEffect: false, isGetPointAddEffect: true, new List<sbyte> { 3, 5, 4, 8, 6 }, new sbyte[5] { 0, 0, 0, 3, 3 }, new sbyte[5] { 0, 0, 0, 30, 0 }, ELifeSkillCombatEffectSubEffect.SelfThesisChangeAroundHouseActivePointWithParam, new sbyte[5] { -1, 1, 1, -10, 0 }, "lifeskillcombat_chahua_10"));
		_dataArray.Add(new LifeSkillCombatEffectItem(8, LocalStringManager.GetConfig("LifeSkillCombatEffect_language", "Name_8"), LocalStringManager.GetConfig("LifeSkillCombatEffect_language", "Desc_8"), 2, 3, 1, 0, ELifeSkillCombatEffectType.BUFF, ELifeSkillCombatEffectGroup.WeakenArgument, isInstant: false, isSelectGrid: false, isSelectBook: false, isSaveCard: true, isDecideAddEffect: false, isGetPointAddEffect: true, new List<sbyte> { 3, 5, 4, 7, 6 }, new sbyte[5] { 0, 0, 0, 3, 3 }, new sbyte[5] { 0, 0, 0, 30, 0 }, ELifeSkillCombatEffectSubEffect.SelfThesisChangeAroundHouseActivePointWithParam, new sbyte[5] { -1, 127, 0, -10, 0 }, "lifeskillcombat_chahua_11"));
		_dataArray.Add(new LifeSkillCombatEffectItem(9, LocalStringManager.GetConfig("LifeSkillCombatEffect_language", "Name_9"), LocalStringManager.GetConfig("LifeSkillCombatEffect_language", "Desc_9"), 2, 3, 1, 0, ELifeSkillCombatEffectType.Common, ELifeSkillCombatEffectGroup.EliminateArgument, isInstant: false, isSelectGrid: false, isSelectBook: false, isSaveCard: false, isDecideAddEffect: true, isGetPointAddEffect: false, new List<sbyte> { 0, 1, 2, 11, 10, 21, 23, 22, 24, 26 }, new sbyte[5] { 0, 0, 0, 2, 2 }, new sbyte[5], ELifeSkillCombatEffectSubEffect.SelfThesisWhenFixedDoCancelAroundHouseAllQuestionLowAndThesisLow, new sbyte[5] { -1, 1, 1, 0, 0 }, "lifeskillcombat_chahua_18"));
		_dataArray.Add(new LifeSkillCombatEffectItem(10, LocalStringManager.GetConfig("LifeSkillCombatEffect_language", "Name_10"), LocalStringManager.GetConfig("LifeSkillCombatEffect_language", "Desc_10"), 2, 3, 2, 0, ELifeSkillCombatEffectType.Common, ELifeSkillCombatEffectGroup.EliminateArgument, isInstant: true, isSelectGrid: true, isSelectBook: false, isSaveCard: false, isDecideAddEffect: true, isGetPointAddEffect: false, new List<sbyte> { 0, 1, 2, 9, 11, 21, 23, 22 }, new sbyte[5] { 0, 0, 0, 2, 2 }, new sbyte[5], ELifeSkillCombatEffectSubEffect.SelfEraseAroundSelfThesisHouseQuestionThesis, new sbyte[5] { -1, 0, 0, 0, 0 }, "lifeskillcombat_chahua_19"));
		_dataArray.Add(new LifeSkillCombatEffectItem(11, LocalStringManager.GetConfig("LifeSkillCombatEffect_language", "Name_11"), LocalStringManager.GetConfig("LifeSkillCombatEffect_language", "Desc_11"), 2, 3, 1, 0, ELifeSkillCombatEffectType.Common, ELifeSkillCombatEffectGroup.EliminateArgument, isInstant: false, isSelectGrid: false, isSelectBook: false, isSaveCard: false, isDecideAddEffect: false, isGetPointAddEffect: false, new List<sbyte> { 0, 1, 2, 9, 10, 21, 23, 22, 24, 26 }, new sbyte[5] { 0, 0, 0, 2, 2 }, new sbyte[5], ELifeSkillCombatEffectSubEffect.SelfThesisWhenFixedDoCancelAroundHouseAllQuestionLowAndThesisLow, new sbyte[5] { -1, 127, 0, 0, 0 }, "lifeskillcombat_chahua_20"));
		_dataArray.Add(new LifeSkillCombatEffectItem(12, LocalStringManager.GetConfig("LifeSkillCombatEffect_language", "Name_12"), LocalStringManager.GetConfig("LifeSkillCombatEffect_language", "Desc_12"), 1, 2, 1, 1, ELifeSkillCombatEffectType.Strategy, ELifeSkillCombatEffectGroup.DissembleArgument, isInstant: false, isSelectGrid: false, isSelectBook: false, isSaveCard: false, isDecideAddEffect: true, isGetPointAddEffect: false, new List<sbyte> { 16, 17, 15, 13, 14, 24, 26 }, new sbyte[5] { 0, 0, 3, 0, 0 }, new sbyte[5] { 30, 0, 0, 0, 0 }, ELifeSkillCombatEffectSubEffect.SelfTrapedInCell, new sbyte[5] { 1, 0, 0, 0, 0 }, "lifeskillcombat_chahua_3"));
		_dataArray.Add(new LifeSkillCombatEffectItem(13, LocalStringManager.GetConfig("LifeSkillCombatEffect_language", "Name_13"), LocalStringManager.GetConfig("LifeSkillCombatEffect_language", "Desc_13"), 1, 2, 1, 1, ELifeSkillCombatEffectType.Strategy, ELifeSkillCombatEffectGroup.DissembleArgument, isInstant: false, isSelectGrid: false, isSelectBook: false, isSaveCard: false, isDecideAddEffect: true, isGetPointAddEffect: false, new List<sbyte> { 16, 17, 15, 12, 14, 24, 26 }, new sbyte[5] { 0, 0, 3, 0, 0 }, new sbyte[5] { 30, 0, 0, 0, 0 }, ELifeSkillCombatEffectSubEffect.SelfGridCoverBookStatesWhenAllQuestion, new sbyte[5] { 1, 0, 0, 3, 0 }, "lifeskillcombat_chahua_4"));
		_dataArray.Add(new LifeSkillCombatEffectItem(14, LocalStringManager.GetConfig("LifeSkillCombatEffect_language", "Name_14"), LocalStringManager.GetConfig("LifeSkillCombatEffect_language", "Desc_14"), 2, 2, 1, 1, ELifeSkillCombatEffectType.Strategy, ELifeSkillCombatEffectGroup.DissembleArgument, isInstant: false, isSelectGrid: false, isSelectBook: false, isSaveCard: false, isDecideAddEffect: true, isGetPointAddEffect: false, new List<sbyte> { 16, 17, 15, 12, 13, 24, 26 }, new sbyte[5] { 0, 0, 3, 0, 0 }, new sbyte[5] { 30, 0, 0, 0, 0 }, ELifeSkillCombatEffectSubEffect.SelfGridCoverBookStatesWhenAllQuestion, new sbyte[5] { 1, 0, 0, -3, 0 }, "lifeskillcombat_chahua_5"));
		_dataArray.Add(new LifeSkillCombatEffectItem(15, LocalStringManager.GetConfig("LifeSkillCombatEffect_language", "Name_15"), LocalStringManager.GetConfig("LifeSkillCombatEffect_language", "Desc_15"), 1, 2, 1, 1, ELifeSkillCombatEffectType.Strategy, ELifeSkillCombatEffectGroup.RemoveEffect, isInstant: true, isSelectGrid: true, isSelectBook: false, isSaveCard: false, isDecideAddEffect: false, isGetPointAddEffect: false, new List<sbyte> { 16, 17, 12, 13, 14 }, new sbyte[5] { 0, 0, 2, 0, 0 }, new sbyte[5], ELifeSkillCombatEffectSubEffect.SelfEraseAroundHouseQuestionEffects, new sbyte[5] { -1, 0, 0, 0, 0 }, "lifeskillcombat_chahua_12"));
		_dataArray.Add(new LifeSkillCombatEffectItem(16, LocalStringManager.GetConfig("LifeSkillCombatEffect_language", "Name_16"), LocalStringManager.GetConfig("LifeSkillCombatEffect_language", "Desc_16"), 1, 2, 1, 1, ELifeSkillCombatEffectType.Strategy, ELifeSkillCombatEffectGroup.RemoveEffect, isInstant: false, isSelectGrid: false, isSelectBook: false, isSaveCard: false, isDecideAddEffect: true, isGetPointAddEffect: false, new List<sbyte> { 17, 15, 12, 13, 14, 24, 26 }, new sbyte[5] { 0, 0, 2, 0, 0 }, new sbyte[5], ELifeSkillCombatEffectSubEffect.SelfThesisWhenFixedEraseEffectsAroundHouseAllQuestionLowAndThesisLow, new sbyte[5] { -1, 1, 1, 0, 0 }, "lifeskillcombat_chahua_13"));
		_dataArray.Add(new LifeSkillCombatEffectItem(17, LocalStringManager.GetConfig("LifeSkillCombatEffect_language", "Name_17"), LocalStringManager.GetConfig("LifeSkillCombatEffect_language", "Desc_17"), 2, 2, 1, 1, ELifeSkillCombatEffectType.Strategy, ELifeSkillCombatEffectGroup.RemoveEffect, isInstant: false, isSelectGrid: false, isSelectBook: false, isSaveCard: false, isDecideAddEffect: true, isGetPointAddEffect: false, new List<sbyte> { 16, 15, 12, 13, 14, 24, 26 }, new sbyte[5] { 0, 0, 2, 0, 0 }, new sbyte[5], ELifeSkillCombatEffectSubEffect.SelfThesisWhenFixedEraseEffectsAroundHouseAllQuestionLowAndThesisLow, new sbyte[5] { -1, 127, 0, 0, 0 }, "lifeskillcombat_chahua_14"));
		_dataArray.Add(new LifeSkillCombatEffectItem(18, LocalStringManager.GetConfig("LifeSkillCombatEffect_language", "Name_18"), LocalStringManager.GetConfig("LifeSkillCombatEffect_language", "Desc_18"), 1, 2, 1, 1, ELifeSkillCombatEffectType.Cooling, ELifeSkillCombatEffectGroup.ReduceCooling, isInstant: true, isSelectGrid: false, isSelectBook: false, isSaveCard: false, isDecideAddEffect: false, isGetPointAddEffect: false, new List<sbyte> { 19, 20 }, new sbyte[5] { 0, 0, 3, 0, 0 }, new sbyte[5] { 0, 0, 30, 0, 0 }, ELifeSkillCombatEffectSubEffect.SelfChangeBookCd, new sbyte[5] { 1, 0, 0, 3, 1 }, "lifeskillcombat_chahua_24"));
		_dataArray.Add(new LifeSkillCombatEffectItem(19, LocalStringManager.GetConfig("LifeSkillCombatEffect_language", "Name_19"), LocalStringManager.GetConfig("LifeSkillCombatEffect_language", "Desc_19"), 1, 2, 1, 1, ELifeSkillCombatEffectType.Cooling, ELifeSkillCombatEffectGroup.AddCooling, isInstant: true, isSelectGrid: false, isSelectBook: false, isSaveCard: false, isDecideAddEffect: false, isGetPointAddEffect: false, new List<sbyte> { 18, 20 }, new sbyte[5] { 3, 3, 0, 0, 0 }, new sbyte[5] { 0, 0, 30, 0, 0 }, ELifeSkillCombatEffectSubEffect.SelfChangeBookCd, new sbyte[5] { -1, 0, 0, 3, 1 }, "lifeskillcombat_chahua_25"));
		_dataArray.Add(new LifeSkillCombatEffectItem(20, LocalStringManager.GetConfig("LifeSkillCombatEffect_language", "Name_20"), LocalStringManager.GetConfig("LifeSkillCombatEffect_language", "Desc_20"), 2, 2, 1, 1, ELifeSkillCombatEffectType.Cooling, ELifeSkillCombatEffectGroup.CompleteCooling, isInstant: true, isSelectGrid: false, isSelectBook: true, isSaveCard: false, isDecideAddEffect: false, isGetPointAddEffect: false, new List<sbyte> { 18, 19 }, new sbyte[5] { 0, 0, 0, 3, 3 }, new sbyte[5] { 0, 0, 30, 0, 0 }, ELifeSkillCombatEffectSubEffect.SelfChangeBookCd, new sbyte[5] { 1, 0, 0, 1, 127 }, "lifeskillcombat_chahua_26"));
		_dataArray.Add(new LifeSkillCombatEffectItem(21, LocalStringManager.GetConfig("LifeSkillCombatEffect_language", "Name_21"), LocalStringManager.GetConfig("LifeSkillCombatEffect_language", "Desc_21"), 0, 1, 0, 2, ELifeSkillCombatEffectType.Common, ELifeSkillCombatEffectGroup.ExtractCard, isInstant: false, isSelectGrid: false, isSelectBook: false, isSaveCard: false, isDecideAddEffect: true, isGetPointAddEffect: false, new List<sbyte> { 0, 1, 2, 9, 11, 10, 23, 22, 24, 26 }, new sbyte[5] { 2, 2, 0, 0, 0 }, new sbyte[5] { 0, 30, 0, 0, 0 }, ELifeSkillCombatEffectSubEffect.SelfThesisWhenFixedDoPickWithAroundHouseThesisCount, new sbyte[5] { 1, 1, 1, 0, 0 }, "lifeskillcombat_chahua_15"));
		_dataArray.Add(new LifeSkillCombatEffectItem(22, LocalStringManager.GetConfig("LifeSkillCombatEffect_language", "Name_22"), LocalStringManager.GetConfig("LifeSkillCombatEffect_language", "Desc_22"), 1, 1, 1, 2, ELifeSkillCombatEffectType.Common, ELifeSkillCombatEffectGroup.ExtractCard, isInstant: true, isSelectGrid: true, isSelectBook: false, isSaveCard: false, isDecideAddEffect: false, isGetPointAddEffect: false, new List<sbyte> { 0, 1, 2, 9, 11, 10, 21, 23 }, new sbyte[5] { 2, 2, 0, 0, 0 }, new sbyte[5] { 0, 30, 0, 0, 0 }, ELifeSkillCombatEffectSubEffect.SelfDoPickByPoint, new sbyte[5] { 1, 0, 0, 0, 0 }, "lifeskillcombat_chahua_16"));
		_dataArray.Add(new LifeSkillCombatEffectItem(23, LocalStringManager.GetConfig("LifeSkillCombatEffect_language", "Name_23"), LocalStringManager.GetConfig("LifeSkillCombatEffect_language", "Desc_23"), 0, 1, 0, 2, ELifeSkillCombatEffectType.Common, ELifeSkillCombatEffectGroup.ExtractCard, isInstant: false, isSelectGrid: false, isSelectBook: false, isSaveCard: false, isDecideAddEffect: true, isGetPointAddEffect: false, new List<sbyte> { 0, 1, 2, 9, 11, 10, 21, 22, 24, 26 }, new sbyte[5] { 2, 2, 0, 0, 0 }, new sbyte[5] { 0, 30, 0, 0, 0 }, ELifeSkillCombatEffectSubEffect.SelfThesisWhenFixedDoPickWithAroundHouseThesisCount, new sbyte[5] { 1, 127, 0, 0, 0 }, "lifeskillcombat_chahua_17"));
		_dataArray.Add(new LifeSkillCombatEffectItem(24, LocalStringManager.GetConfig("LifeSkillCombatEffect_language", "Name_24"), LocalStringManager.GetConfig("LifeSkillCombatEffect_language", "Desc_24"), 1, 1, 1, 2, ELifeSkillCombatEffectType.Special, ELifeSkillCombatEffectGroup.RecycleCard, isInstant: false, isSelectGrid: false, isSelectBook: false, isSaveCard: false, isDecideAddEffect: false, isGetPointAddEffect: false, new List<sbyte>
		{
			0, 1, 2, 9, 11, 21, 23, 4, 16, 17,
			12, 13, 14, 25, 26
		}, new sbyte[5] { 0, 0, 1, 0, 0 }, new sbyte[5], ELifeSkillCombatEffectSubEffect.SelfExtraQuestionOnHouseThesisLowAndRecycleCardAndExchangeOperation, new sbyte[5] { 1, 0, 0, 0, 0 }, "lifeskillcombat_chahua_21"));
		_dataArray.Add(new LifeSkillCombatEffectItem(25, LocalStringManager.GetConfig("LifeSkillCombatEffect_language", "Name_25"), LocalStringManager.GetConfig("LifeSkillCombatEffect_language", "Desc_25"), 0, 1, 0, 2, ELifeSkillCombatEffectType.Special, ELifeSkillCombatEffectGroup.QuickArgument, isInstant: false, isSelectGrid: false, isSelectBook: false, isSaveCard: false, isDecideAddEffect: false, isGetPointAddEffect: false, new List<sbyte> { 24, 26 }, new sbyte[5] { 1, 1, 0, 0, 0 }, new sbyte[5], ELifeSkillCombatEffectSubEffect.SelfNotCostBookStates, new sbyte[5], "lifeskillcombat_chahua_22"));
		_dataArray.Add(new LifeSkillCombatEffectItem(26, LocalStringManager.GetConfig("LifeSkillCombatEffect_language", "Name_26"), LocalStringManager.GetConfig("LifeSkillCombatEffect_language", "Desc_26"), 1, 1, 1, 2, ELifeSkillCombatEffectType.Special, ELifeSkillCombatEffectGroup.CaptureArgument, isInstant: false, isSelectGrid: false, isSelectBook: false, isSaveCard: false, isDecideAddEffect: false, isGetPointAddEffect: false, new List<sbyte>
		{
			0, 1, 2, 9, 11, 21, 23, 4, 6, 16,
			17, 12, 13, 14, 24, 25
		}, new sbyte[5] { 0, 0, 0, 1, 1 }, new sbyte[5], ELifeSkillCombatEffectSubEffect.SelfExtraQuestionOnHouseThesisLowAndTransition, new sbyte[5] { -1, 0, 0, 0, 0 }, "lifeskillcombat_chahua_23"));
	}

	public override void Init()
	{
		base.Init();
		_dataArray = new List<LifeSkillCombatEffectItem>(27);
		CreateItems0();
	}
}
