using System;
using System.Collections.Generic;
using Config.Common;

namespace Config;

[Serializable]
public class LocalTownNames : IConfigData
{
	public static LocalTownNames Instance = new LocalTownNames();

	public short VillageStart = 1;

	public short VillageEnd = 136;

	public short TownStart = 300;

	public short TownEnd = 435;

	public short WalledTownStart = 600;

	public short WalledTownEnd = 735;

	public TownNameItem[] TownNameCore;

	public IReadOnlyDictionary<string, int> RefNameMap
	{
		get
		{
			throw new NotImplementedException();
		}
	}

	public int GetItemId(string refName)
	{
		throw new NotImplementedException();
	}

	public int AddExtraItem(string identifier, string refName, object configItem)
	{
		throw new NotImplementedException();
	}

	public void Init()
	{
		TownNameCore = new TownNameItem[736]
		{
			null,
			new TownNameItem(1, LocalStringManager.GetConfig("Name_language", "TownName_1")),
			new TownNameItem(2, LocalStringManager.GetConfig("Name_language", "TownName_2")),
			new TownNameItem(3, LocalStringManager.GetConfig("Name_language", "TownName_3")),
			new TownNameItem(4, LocalStringManager.GetConfig("Name_language", "TownName_4")),
			new TownNameItem(5, LocalStringManager.GetConfig("Name_language", "TownName_5")),
			new TownNameItem(6, LocalStringManager.GetConfig("Name_language", "TownName_6")),
			new TownNameItem(7, LocalStringManager.GetConfig("Name_language", "TownName_7")),
			new TownNameItem(8, LocalStringManager.GetConfig("Name_language", "TownName_8")),
			new TownNameItem(9, LocalStringManager.GetConfig("Name_language", "TownName_9")),
			new TownNameItem(10, LocalStringManager.GetConfig("Name_language", "TownName_10")),
			new TownNameItem(11, LocalStringManager.GetConfig("Name_language", "TownName_11")),
			new TownNameItem(12, LocalStringManager.GetConfig("Name_language", "TownName_12")),
			new TownNameItem(13, LocalStringManager.GetConfig("Name_language", "TownName_13")),
			new TownNameItem(14, LocalStringManager.GetConfig("Name_language", "TownName_14")),
			new TownNameItem(15, LocalStringManager.GetConfig("Name_language", "TownName_15")),
			new TownNameItem(16, LocalStringManager.GetConfig("Name_language", "TownName_16")),
			new TownNameItem(17, LocalStringManager.GetConfig("Name_language", "TownName_17")),
			new TownNameItem(18, LocalStringManager.GetConfig("Name_language", "TownName_18")),
			new TownNameItem(19, LocalStringManager.GetConfig("Name_language", "TownName_19")),
			new TownNameItem(20, LocalStringManager.GetConfig("Name_language", "TownName_20")),
			new TownNameItem(21, LocalStringManager.GetConfig("Name_language", "TownName_21")),
			new TownNameItem(22, LocalStringManager.GetConfig("Name_language", "TownName_22")),
			new TownNameItem(23, LocalStringManager.GetConfig("Name_language", "TownName_23")),
			new TownNameItem(24, LocalStringManager.GetConfig("Name_language", "TownName_24")),
			new TownNameItem(25, LocalStringManager.GetConfig("Name_language", "TownName_25")),
			new TownNameItem(26, LocalStringManager.GetConfig("Name_language", "TownName_26")),
			new TownNameItem(27, LocalStringManager.GetConfig("Name_language", "TownName_27")),
			new TownNameItem(28, LocalStringManager.GetConfig("Name_language", "TownName_28")),
			new TownNameItem(29, LocalStringManager.GetConfig("Name_language", "TownName_29")),
			new TownNameItem(30, LocalStringManager.GetConfig("Name_language", "TownName_30")),
			new TownNameItem(31, LocalStringManager.GetConfig("Name_language", "TownName_31")),
			new TownNameItem(32, LocalStringManager.GetConfig("Name_language", "TownName_32")),
			new TownNameItem(33, LocalStringManager.GetConfig("Name_language", "TownName_33")),
			new TownNameItem(34, LocalStringManager.GetConfig("Name_language", "TownName_34")),
			new TownNameItem(35, LocalStringManager.GetConfig("Name_language", "TownName_35")),
			new TownNameItem(36, LocalStringManager.GetConfig("Name_language", "TownName_36")),
			new TownNameItem(37, LocalStringManager.GetConfig("Name_language", "TownName_37")),
			new TownNameItem(38, LocalStringManager.GetConfig("Name_language", "TownName_38")),
			new TownNameItem(39, LocalStringManager.GetConfig("Name_language", "TownName_39")),
			new TownNameItem(40, LocalStringManager.GetConfig("Name_language", "TownName_40")),
			new TownNameItem(41, LocalStringManager.GetConfig("Name_language", "TownName_41")),
			new TownNameItem(42, LocalStringManager.GetConfig("Name_language", "TownName_42")),
			new TownNameItem(43, LocalStringManager.GetConfig("Name_language", "TownName_43")),
			new TownNameItem(44, LocalStringManager.GetConfig("Name_language", "TownName_44")),
			new TownNameItem(45, LocalStringManager.GetConfig("Name_language", "TownName_45")),
			new TownNameItem(46, LocalStringManager.GetConfig("Name_language", "TownName_46")),
			new TownNameItem(47, LocalStringManager.GetConfig("Name_language", "TownName_47")),
			new TownNameItem(48, LocalStringManager.GetConfig("Name_language", "TownName_48")),
			new TownNameItem(49, LocalStringManager.GetConfig("Name_language", "TownName_49")),
			new TownNameItem(50, LocalStringManager.GetConfig("Name_language", "TownName_50")),
			new TownNameItem(51, LocalStringManager.GetConfig("Name_language", "TownName_51")),
			new TownNameItem(52, LocalStringManager.GetConfig("Name_language", "TownName_52")),
			new TownNameItem(53, LocalStringManager.GetConfig("Name_language", "TownName_53")),
			new TownNameItem(54, LocalStringManager.GetConfig("Name_language", "TownName_54")),
			new TownNameItem(55, LocalStringManager.GetConfig("Name_language", "TownName_55")),
			new TownNameItem(56, LocalStringManager.GetConfig("Name_language", "TownName_56")),
			new TownNameItem(57, LocalStringManager.GetConfig("Name_language", "TownName_57")),
			new TownNameItem(58, LocalStringManager.GetConfig("Name_language", "TownName_58")),
			new TownNameItem(59, LocalStringManager.GetConfig("Name_language", "TownName_59")),
			new TownNameItem(60, LocalStringManager.GetConfig("Name_language", "TownName_60")),
			new TownNameItem(61, LocalStringManager.GetConfig("Name_language", "TownName_61")),
			new TownNameItem(62, LocalStringManager.GetConfig("Name_language", "TownName_62")),
			new TownNameItem(63, LocalStringManager.GetConfig("Name_language", "TownName_63")),
			new TownNameItem(64, LocalStringManager.GetConfig("Name_language", "TownName_64")),
			new TownNameItem(65, LocalStringManager.GetConfig("Name_language", "TownName_65")),
			new TownNameItem(66, LocalStringManager.GetConfig("Name_language", "TownName_66")),
			new TownNameItem(67, LocalStringManager.GetConfig("Name_language", "TownName_67")),
			new TownNameItem(68, LocalStringManager.GetConfig("Name_language", "TownName_68")),
			new TownNameItem(69, LocalStringManager.GetConfig("Name_language", "TownName_69")),
			new TownNameItem(70, LocalStringManager.GetConfig("Name_language", "TownName_70")),
			new TownNameItem(71, LocalStringManager.GetConfig("Name_language", "TownName_71")),
			new TownNameItem(72, LocalStringManager.GetConfig("Name_language", "TownName_72")),
			new TownNameItem(73, LocalStringManager.GetConfig("Name_language", "TownName_73")),
			new TownNameItem(74, LocalStringManager.GetConfig("Name_language", "TownName_74")),
			new TownNameItem(75, LocalStringManager.GetConfig("Name_language", "TownName_75")),
			new TownNameItem(76, LocalStringManager.GetConfig("Name_language", "TownName_76")),
			new TownNameItem(77, LocalStringManager.GetConfig("Name_language", "TownName_77")),
			new TownNameItem(78, LocalStringManager.GetConfig("Name_language", "TownName_78")),
			new TownNameItem(79, LocalStringManager.GetConfig("Name_language", "TownName_79")),
			new TownNameItem(80, LocalStringManager.GetConfig("Name_language", "TownName_80")),
			new TownNameItem(81, LocalStringManager.GetConfig("Name_language", "TownName_81")),
			new TownNameItem(82, LocalStringManager.GetConfig("Name_language", "TownName_82")),
			new TownNameItem(83, LocalStringManager.GetConfig("Name_language", "TownName_83")),
			new TownNameItem(84, LocalStringManager.GetConfig("Name_language", "TownName_84")),
			new TownNameItem(85, LocalStringManager.GetConfig("Name_language", "TownName_85")),
			new TownNameItem(86, LocalStringManager.GetConfig("Name_language", "TownName_86")),
			new TownNameItem(87, LocalStringManager.GetConfig("Name_language", "TownName_87")),
			new TownNameItem(88, LocalStringManager.GetConfig("Name_language", "TownName_88")),
			new TownNameItem(89, LocalStringManager.GetConfig("Name_language", "TownName_89")),
			new TownNameItem(90, LocalStringManager.GetConfig("Name_language", "TownName_90")),
			new TownNameItem(91, LocalStringManager.GetConfig("Name_language", "TownName_91")),
			new TownNameItem(92, LocalStringManager.GetConfig("Name_language", "TownName_92")),
			new TownNameItem(93, LocalStringManager.GetConfig("Name_language", "TownName_93")),
			new TownNameItem(94, LocalStringManager.GetConfig("Name_language", "TownName_94")),
			new TownNameItem(95, LocalStringManager.GetConfig("Name_language", "TownName_95")),
			new TownNameItem(96, LocalStringManager.GetConfig("Name_language", "TownName_96")),
			new TownNameItem(97, LocalStringManager.GetConfig("Name_language", "TownName_97")),
			new TownNameItem(98, LocalStringManager.GetConfig("Name_language", "TownName_98")),
			new TownNameItem(99, LocalStringManager.GetConfig("Name_language", "TownName_99")),
			new TownNameItem(100, LocalStringManager.GetConfig("Name_language", "TownName_100")),
			new TownNameItem(101, LocalStringManager.GetConfig("Name_language", "TownName_101")),
			new TownNameItem(102, LocalStringManager.GetConfig("Name_language", "TownName_102")),
			new TownNameItem(103, LocalStringManager.GetConfig("Name_language", "TownName_103")),
			new TownNameItem(104, LocalStringManager.GetConfig("Name_language", "TownName_104")),
			new TownNameItem(105, LocalStringManager.GetConfig("Name_language", "TownName_105")),
			new TownNameItem(106, LocalStringManager.GetConfig("Name_language", "TownName_106")),
			new TownNameItem(107, LocalStringManager.GetConfig("Name_language", "TownName_107")),
			new TownNameItem(108, LocalStringManager.GetConfig("Name_language", "TownName_108")),
			new TownNameItem(109, LocalStringManager.GetConfig("Name_language", "TownName_109")),
			new TownNameItem(110, LocalStringManager.GetConfig("Name_language", "TownName_110")),
			new TownNameItem(111, LocalStringManager.GetConfig("Name_language", "TownName_111")),
			new TownNameItem(112, LocalStringManager.GetConfig("Name_language", "TownName_112")),
			new TownNameItem(113, LocalStringManager.GetConfig("Name_language", "TownName_113")),
			new TownNameItem(114, LocalStringManager.GetConfig("Name_language", "TownName_114")),
			new TownNameItem(115, LocalStringManager.GetConfig("Name_language", "TownName_115")),
			new TownNameItem(116, LocalStringManager.GetConfig("Name_language", "TownName_116")),
			new TownNameItem(117, LocalStringManager.GetConfig("Name_language", "TownName_117")),
			new TownNameItem(118, LocalStringManager.GetConfig("Name_language", "TownName_118")),
			new TownNameItem(119, LocalStringManager.GetConfig("Name_language", "TownName_119")),
			new TownNameItem(120, LocalStringManager.GetConfig("Name_language", "TownName_120")),
			new TownNameItem(121, LocalStringManager.GetConfig("Name_language", "TownName_121")),
			new TownNameItem(122, LocalStringManager.GetConfig("Name_language", "TownName_122")),
			new TownNameItem(123, LocalStringManager.GetConfig("Name_language", "TownName_123")),
			new TownNameItem(124, LocalStringManager.GetConfig("Name_language", "TownName_124")),
			new TownNameItem(125, LocalStringManager.GetConfig("Name_language", "TownName_125")),
			new TownNameItem(126, LocalStringManager.GetConfig("Name_language", "TownName_126")),
			new TownNameItem(127, LocalStringManager.GetConfig("Name_language", "TownName_127")),
			new TownNameItem(128, LocalStringManager.GetConfig("Name_language", "TownName_128")),
			new TownNameItem(129, LocalStringManager.GetConfig("Name_language", "TownName_129")),
			new TownNameItem(130, LocalStringManager.GetConfig("Name_language", "TownName_130")),
			new TownNameItem(131, LocalStringManager.GetConfig("Name_language", "TownName_131")),
			new TownNameItem(132, LocalStringManager.GetConfig("Name_language", "TownName_132")),
			new TownNameItem(133, LocalStringManager.GetConfig("Name_language", "TownName_133")),
			new TownNameItem(134, LocalStringManager.GetConfig("Name_language", "TownName_134")),
			new TownNameItem(135, LocalStringManager.GetConfig("Name_language", "TownName_135")),
			new TownNameItem(136, LocalStringManager.GetConfig("Name_language", "TownName_136")),
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			new TownNameItem(300, LocalStringManager.GetConfig("Name_language", "TownName_300")),
			new TownNameItem(301, LocalStringManager.GetConfig("Name_language", "TownName_301")),
			new TownNameItem(302, LocalStringManager.GetConfig("Name_language", "TownName_302")),
			new TownNameItem(303, LocalStringManager.GetConfig("Name_language", "TownName_303")),
			new TownNameItem(304, LocalStringManager.GetConfig("Name_language", "TownName_304")),
			new TownNameItem(305, LocalStringManager.GetConfig("Name_language", "TownName_305")),
			new TownNameItem(306, LocalStringManager.GetConfig("Name_language", "TownName_306")),
			new TownNameItem(307, LocalStringManager.GetConfig("Name_language", "TownName_307")),
			new TownNameItem(308, LocalStringManager.GetConfig("Name_language", "TownName_308")),
			new TownNameItem(309, LocalStringManager.GetConfig("Name_language", "TownName_309")),
			new TownNameItem(310, LocalStringManager.GetConfig("Name_language", "TownName_310")),
			new TownNameItem(311, LocalStringManager.GetConfig("Name_language", "TownName_311")),
			new TownNameItem(312, LocalStringManager.GetConfig("Name_language", "TownName_312")),
			new TownNameItem(313, LocalStringManager.GetConfig("Name_language", "TownName_313")),
			new TownNameItem(314, LocalStringManager.GetConfig("Name_language", "TownName_314")),
			new TownNameItem(315, LocalStringManager.GetConfig("Name_language", "TownName_315")),
			new TownNameItem(316, LocalStringManager.GetConfig("Name_language", "TownName_316")),
			new TownNameItem(317, LocalStringManager.GetConfig("Name_language", "TownName_317")),
			new TownNameItem(318, LocalStringManager.GetConfig("Name_language", "TownName_318")),
			new TownNameItem(319, LocalStringManager.GetConfig("Name_language", "TownName_319")),
			new TownNameItem(320, LocalStringManager.GetConfig("Name_language", "TownName_320")),
			new TownNameItem(321, LocalStringManager.GetConfig("Name_language", "TownName_321")),
			new TownNameItem(322, LocalStringManager.GetConfig("Name_language", "TownName_322")),
			new TownNameItem(323, LocalStringManager.GetConfig("Name_language", "TownName_323")),
			new TownNameItem(324, LocalStringManager.GetConfig("Name_language", "TownName_324")),
			new TownNameItem(325, LocalStringManager.GetConfig("Name_language", "TownName_325")),
			new TownNameItem(326, LocalStringManager.GetConfig("Name_language", "TownName_326")),
			new TownNameItem(327, LocalStringManager.GetConfig("Name_language", "TownName_327")),
			new TownNameItem(328, LocalStringManager.GetConfig("Name_language", "TownName_328")),
			new TownNameItem(329, LocalStringManager.GetConfig("Name_language", "TownName_329")),
			new TownNameItem(330, LocalStringManager.GetConfig("Name_language", "TownName_330")),
			new TownNameItem(331, LocalStringManager.GetConfig("Name_language", "TownName_331")),
			new TownNameItem(332, LocalStringManager.GetConfig("Name_language", "TownName_332")),
			new TownNameItem(333, LocalStringManager.GetConfig("Name_language", "TownName_333")),
			new TownNameItem(334, LocalStringManager.GetConfig("Name_language", "TownName_334")),
			new TownNameItem(335, LocalStringManager.GetConfig("Name_language", "TownName_335")),
			new TownNameItem(336, LocalStringManager.GetConfig("Name_language", "TownName_336")),
			new TownNameItem(337, LocalStringManager.GetConfig("Name_language", "TownName_337")),
			new TownNameItem(338, LocalStringManager.GetConfig("Name_language", "TownName_338")),
			new TownNameItem(339, LocalStringManager.GetConfig("Name_language", "TownName_339")),
			new TownNameItem(340, LocalStringManager.GetConfig("Name_language", "TownName_340")),
			new TownNameItem(341, LocalStringManager.GetConfig("Name_language", "TownName_341")),
			new TownNameItem(342, LocalStringManager.GetConfig("Name_language", "TownName_342")),
			new TownNameItem(343, LocalStringManager.GetConfig("Name_language", "TownName_343")),
			new TownNameItem(344, LocalStringManager.GetConfig("Name_language", "TownName_344")),
			new TownNameItem(345, LocalStringManager.GetConfig("Name_language", "TownName_345")),
			new TownNameItem(346, LocalStringManager.GetConfig("Name_language", "TownName_346")),
			new TownNameItem(347, LocalStringManager.GetConfig("Name_language", "TownName_347")),
			new TownNameItem(348, LocalStringManager.GetConfig("Name_language", "TownName_348")),
			new TownNameItem(349, LocalStringManager.GetConfig("Name_language", "TownName_349")),
			new TownNameItem(350, LocalStringManager.GetConfig("Name_language", "TownName_350")),
			new TownNameItem(351, LocalStringManager.GetConfig("Name_language", "TownName_351")),
			new TownNameItem(352, LocalStringManager.GetConfig("Name_language", "TownName_352")),
			new TownNameItem(353, LocalStringManager.GetConfig("Name_language", "TownName_353")),
			new TownNameItem(354, LocalStringManager.GetConfig("Name_language", "TownName_354")),
			new TownNameItem(355, LocalStringManager.GetConfig("Name_language", "TownName_355")),
			new TownNameItem(356, LocalStringManager.GetConfig("Name_language", "TownName_356")),
			new TownNameItem(357, LocalStringManager.GetConfig("Name_language", "TownName_357")),
			new TownNameItem(358, LocalStringManager.GetConfig("Name_language", "TownName_358")),
			new TownNameItem(359, LocalStringManager.GetConfig("Name_language", "TownName_359")),
			new TownNameItem(360, LocalStringManager.GetConfig("Name_language", "TownName_360")),
			new TownNameItem(361, LocalStringManager.GetConfig("Name_language", "TownName_361")),
			new TownNameItem(362, LocalStringManager.GetConfig("Name_language", "TownName_362")),
			new TownNameItem(363, LocalStringManager.GetConfig("Name_language", "TownName_363")),
			new TownNameItem(364, LocalStringManager.GetConfig("Name_language", "TownName_364")),
			new TownNameItem(365, LocalStringManager.GetConfig("Name_language", "TownName_365")),
			new TownNameItem(366, LocalStringManager.GetConfig("Name_language", "TownName_366")),
			new TownNameItem(367, LocalStringManager.GetConfig("Name_language", "TownName_367")),
			new TownNameItem(368, LocalStringManager.GetConfig("Name_language", "TownName_368")),
			new TownNameItem(369, LocalStringManager.GetConfig("Name_language", "TownName_369")),
			new TownNameItem(370, LocalStringManager.GetConfig("Name_language", "TownName_370")),
			new TownNameItem(371, LocalStringManager.GetConfig("Name_language", "TownName_371")),
			new TownNameItem(372, LocalStringManager.GetConfig("Name_language", "TownName_372")),
			new TownNameItem(373, LocalStringManager.GetConfig("Name_language", "TownName_373")),
			new TownNameItem(374, LocalStringManager.GetConfig("Name_language", "TownName_374")),
			new TownNameItem(375, LocalStringManager.GetConfig("Name_language", "TownName_375")),
			new TownNameItem(376, LocalStringManager.GetConfig("Name_language", "TownName_376")),
			new TownNameItem(377, LocalStringManager.GetConfig("Name_language", "TownName_377")),
			new TownNameItem(378, LocalStringManager.GetConfig("Name_language", "TownName_378")),
			new TownNameItem(379, LocalStringManager.GetConfig("Name_language", "TownName_379")),
			new TownNameItem(380, LocalStringManager.GetConfig("Name_language", "TownName_380")),
			new TownNameItem(381, LocalStringManager.GetConfig("Name_language", "TownName_381")),
			new TownNameItem(382, LocalStringManager.GetConfig("Name_language", "TownName_382")),
			new TownNameItem(383, LocalStringManager.GetConfig("Name_language", "TownName_383")),
			new TownNameItem(384, LocalStringManager.GetConfig("Name_language", "TownName_384")),
			new TownNameItem(385, LocalStringManager.GetConfig("Name_language", "TownName_385")),
			new TownNameItem(386, LocalStringManager.GetConfig("Name_language", "TownName_386")),
			new TownNameItem(387, LocalStringManager.GetConfig("Name_language", "TownName_387")),
			new TownNameItem(388, LocalStringManager.GetConfig("Name_language", "TownName_388")),
			new TownNameItem(389, LocalStringManager.GetConfig("Name_language", "TownName_389")),
			new TownNameItem(390, LocalStringManager.GetConfig("Name_language", "TownName_390")),
			new TownNameItem(391, LocalStringManager.GetConfig("Name_language", "TownName_391")),
			new TownNameItem(392, LocalStringManager.GetConfig("Name_language", "TownName_392")),
			new TownNameItem(393, LocalStringManager.GetConfig("Name_language", "TownName_393")),
			new TownNameItem(394, LocalStringManager.GetConfig("Name_language", "TownName_394")),
			new TownNameItem(395, LocalStringManager.GetConfig("Name_language", "TownName_395")),
			new TownNameItem(396, LocalStringManager.GetConfig("Name_language", "TownName_396")),
			new TownNameItem(397, LocalStringManager.GetConfig("Name_language", "TownName_397")),
			new TownNameItem(398, LocalStringManager.GetConfig("Name_language", "TownName_398")),
			new TownNameItem(399, LocalStringManager.GetConfig("Name_language", "TownName_399")),
			new TownNameItem(400, LocalStringManager.GetConfig("Name_language", "TownName_400")),
			new TownNameItem(401, LocalStringManager.GetConfig("Name_language", "TownName_401")),
			new TownNameItem(402, LocalStringManager.GetConfig("Name_language", "TownName_402")),
			new TownNameItem(403, LocalStringManager.GetConfig("Name_language", "TownName_403")),
			new TownNameItem(404, LocalStringManager.GetConfig("Name_language", "TownName_404")),
			new TownNameItem(405, LocalStringManager.GetConfig("Name_language", "TownName_405")),
			new TownNameItem(406, LocalStringManager.GetConfig("Name_language", "TownName_406")),
			new TownNameItem(407, LocalStringManager.GetConfig("Name_language", "TownName_407")),
			new TownNameItem(408, LocalStringManager.GetConfig("Name_language", "TownName_408")),
			new TownNameItem(409, LocalStringManager.GetConfig("Name_language", "TownName_409")),
			new TownNameItem(410, LocalStringManager.GetConfig("Name_language", "TownName_410")),
			new TownNameItem(411, LocalStringManager.GetConfig("Name_language", "TownName_411")),
			new TownNameItem(412, LocalStringManager.GetConfig("Name_language", "TownName_412")),
			new TownNameItem(413, LocalStringManager.GetConfig("Name_language", "TownName_413")),
			new TownNameItem(414, LocalStringManager.GetConfig("Name_language", "TownName_414")),
			new TownNameItem(415, LocalStringManager.GetConfig("Name_language", "TownName_415")),
			new TownNameItem(416, LocalStringManager.GetConfig("Name_language", "TownName_416")),
			new TownNameItem(417, LocalStringManager.GetConfig("Name_language", "TownName_417")),
			new TownNameItem(418, LocalStringManager.GetConfig("Name_language", "TownName_418")),
			new TownNameItem(419, LocalStringManager.GetConfig("Name_language", "TownName_419")),
			new TownNameItem(420, LocalStringManager.GetConfig("Name_language", "TownName_420")),
			new TownNameItem(421, LocalStringManager.GetConfig("Name_language", "TownName_421")),
			new TownNameItem(422, LocalStringManager.GetConfig("Name_language", "TownName_422")),
			new TownNameItem(423, LocalStringManager.GetConfig("Name_language", "TownName_423")),
			new TownNameItem(424, LocalStringManager.GetConfig("Name_language", "TownName_424")),
			new TownNameItem(425, LocalStringManager.GetConfig("Name_language", "TownName_425")),
			new TownNameItem(426, LocalStringManager.GetConfig("Name_language", "TownName_426")),
			new TownNameItem(427, LocalStringManager.GetConfig("Name_language", "TownName_427")),
			new TownNameItem(428, LocalStringManager.GetConfig("Name_language", "TownName_428")),
			new TownNameItem(429, LocalStringManager.GetConfig("Name_language", "TownName_429")),
			new TownNameItem(430, LocalStringManager.GetConfig("Name_language", "TownName_430")),
			new TownNameItem(431, LocalStringManager.GetConfig("Name_language", "TownName_431")),
			new TownNameItem(432, LocalStringManager.GetConfig("Name_language", "TownName_432")),
			new TownNameItem(433, LocalStringManager.GetConfig("Name_language", "TownName_433")),
			new TownNameItem(434, LocalStringManager.GetConfig("Name_language", "TownName_434")),
			new TownNameItem(435, LocalStringManager.GetConfig("Name_language", "TownName_435")),
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			new TownNameItem(600, LocalStringManager.GetConfig("Name_language", "TownName_600")),
			new TownNameItem(601, LocalStringManager.GetConfig("Name_language", "TownName_601")),
			new TownNameItem(602, LocalStringManager.GetConfig("Name_language", "TownName_602")),
			new TownNameItem(603, LocalStringManager.GetConfig("Name_language", "TownName_603")),
			new TownNameItem(604, LocalStringManager.GetConfig("Name_language", "TownName_604")),
			new TownNameItem(605, LocalStringManager.GetConfig("Name_language", "TownName_605")),
			new TownNameItem(606, LocalStringManager.GetConfig("Name_language", "TownName_606")),
			new TownNameItem(607, LocalStringManager.GetConfig("Name_language", "TownName_607")),
			new TownNameItem(608, LocalStringManager.GetConfig("Name_language", "TownName_608")),
			new TownNameItem(609, LocalStringManager.GetConfig("Name_language", "TownName_609")),
			new TownNameItem(610, LocalStringManager.GetConfig("Name_language", "TownName_610")),
			new TownNameItem(611, LocalStringManager.GetConfig("Name_language", "TownName_611")),
			new TownNameItem(612, LocalStringManager.GetConfig("Name_language", "TownName_612")),
			new TownNameItem(613, LocalStringManager.GetConfig("Name_language", "TownName_613")),
			new TownNameItem(614, LocalStringManager.GetConfig("Name_language", "TownName_614")),
			new TownNameItem(615, LocalStringManager.GetConfig("Name_language", "TownName_615")),
			new TownNameItem(616, LocalStringManager.GetConfig("Name_language", "TownName_616")),
			new TownNameItem(617, LocalStringManager.GetConfig("Name_language", "TownName_617")),
			new TownNameItem(618, LocalStringManager.GetConfig("Name_language", "TownName_618")),
			new TownNameItem(619, LocalStringManager.GetConfig("Name_language", "TownName_619")),
			new TownNameItem(620, LocalStringManager.GetConfig("Name_language", "TownName_620")),
			new TownNameItem(621, LocalStringManager.GetConfig("Name_language", "TownName_621")),
			new TownNameItem(622, LocalStringManager.GetConfig("Name_language", "TownName_622")),
			new TownNameItem(623, LocalStringManager.GetConfig("Name_language", "TownName_623")),
			new TownNameItem(624, LocalStringManager.GetConfig("Name_language", "TownName_624")),
			new TownNameItem(625, LocalStringManager.GetConfig("Name_language", "TownName_625")),
			new TownNameItem(626, LocalStringManager.GetConfig("Name_language", "TownName_626")),
			new TownNameItem(627, LocalStringManager.GetConfig("Name_language", "TownName_627")),
			new TownNameItem(628, LocalStringManager.GetConfig("Name_language", "TownName_628")),
			new TownNameItem(629, LocalStringManager.GetConfig("Name_language", "TownName_629")),
			new TownNameItem(630, LocalStringManager.GetConfig("Name_language", "TownName_630")),
			new TownNameItem(631, LocalStringManager.GetConfig("Name_language", "TownName_631")),
			new TownNameItem(632, LocalStringManager.GetConfig("Name_language", "TownName_632")),
			new TownNameItem(633, LocalStringManager.GetConfig("Name_language", "TownName_633")),
			new TownNameItem(634, LocalStringManager.GetConfig("Name_language", "TownName_634")),
			new TownNameItem(635, LocalStringManager.GetConfig("Name_language", "TownName_635")),
			new TownNameItem(636, LocalStringManager.GetConfig("Name_language", "TownName_636")),
			new TownNameItem(637, LocalStringManager.GetConfig("Name_language", "TownName_637")),
			new TownNameItem(638, LocalStringManager.GetConfig("Name_language", "TownName_638")),
			new TownNameItem(639, LocalStringManager.GetConfig("Name_language", "TownName_639")),
			new TownNameItem(640, LocalStringManager.GetConfig("Name_language", "TownName_640")),
			new TownNameItem(641, LocalStringManager.GetConfig("Name_language", "TownName_641")),
			new TownNameItem(642, LocalStringManager.GetConfig("Name_language", "TownName_642")),
			new TownNameItem(643, LocalStringManager.GetConfig("Name_language", "TownName_643")),
			new TownNameItem(644, LocalStringManager.GetConfig("Name_language", "TownName_644")),
			new TownNameItem(645, LocalStringManager.GetConfig("Name_language", "TownName_645")),
			new TownNameItem(646, LocalStringManager.GetConfig("Name_language", "TownName_646")),
			new TownNameItem(647, LocalStringManager.GetConfig("Name_language", "TownName_647")),
			new TownNameItem(648, LocalStringManager.GetConfig("Name_language", "TownName_648")),
			new TownNameItem(649, LocalStringManager.GetConfig("Name_language", "TownName_649")),
			new TownNameItem(650, LocalStringManager.GetConfig("Name_language", "TownName_650")),
			new TownNameItem(651, LocalStringManager.GetConfig("Name_language", "TownName_651")),
			new TownNameItem(652, LocalStringManager.GetConfig("Name_language", "TownName_652")),
			new TownNameItem(653, LocalStringManager.GetConfig("Name_language", "TownName_653")),
			new TownNameItem(654, LocalStringManager.GetConfig("Name_language", "TownName_654")),
			new TownNameItem(655, LocalStringManager.GetConfig("Name_language", "TownName_655")),
			new TownNameItem(656, LocalStringManager.GetConfig("Name_language", "TownName_656")),
			new TownNameItem(657, LocalStringManager.GetConfig("Name_language", "TownName_657")),
			new TownNameItem(658, LocalStringManager.GetConfig("Name_language", "TownName_658")),
			new TownNameItem(659, LocalStringManager.GetConfig("Name_language", "TownName_659")),
			new TownNameItem(660, LocalStringManager.GetConfig("Name_language", "TownName_660")),
			new TownNameItem(661, LocalStringManager.GetConfig("Name_language", "TownName_661")),
			new TownNameItem(662, LocalStringManager.GetConfig("Name_language", "TownName_662")),
			new TownNameItem(663, LocalStringManager.GetConfig("Name_language", "TownName_663")),
			new TownNameItem(664, LocalStringManager.GetConfig("Name_language", "TownName_664")),
			new TownNameItem(665, LocalStringManager.GetConfig("Name_language", "TownName_665")),
			new TownNameItem(666, LocalStringManager.GetConfig("Name_language", "TownName_666")),
			new TownNameItem(667, LocalStringManager.GetConfig("Name_language", "TownName_667")),
			new TownNameItem(668, LocalStringManager.GetConfig("Name_language", "TownName_668")),
			new TownNameItem(669, LocalStringManager.GetConfig("Name_language", "TownName_669")),
			new TownNameItem(670, LocalStringManager.GetConfig("Name_language", "TownName_670")),
			new TownNameItem(671, LocalStringManager.GetConfig("Name_language", "TownName_671")),
			new TownNameItem(672, LocalStringManager.GetConfig("Name_language", "TownName_672")),
			new TownNameItem(673, LocalStringManager.GetConfig("Name_language", "TownName_673")),
			new TownNameItem(674, LocalStringManager.GetConfig("Name_language", "TownName_674")),
			new TownNameItem(675, LocalStringManager.GetConfig("Name_language", "TownName_675")),
			new TownNameItem(676, LocalStringManager.GetConfig("Name_language", "TownName_676")),
			new TownNameItem(677, LocalStringManager.GetConfig("Name_language", "TownName_677")),
			new TownNameItem(678, LocalStringManager.GetConfig("Name_language", "TownName_678")),
			new TownNameItem(679, LocalStringManager.GetConfig("Name_language", "TownName_679")),
			new TownNameItem(680, LocalStringManager.GetConfig("Name_language", "TownName_680")),
			new TownNameItem(681, LocalStringManager.GetConfig("Name_language", "TownName_681")),
			new TownNameItem(682, LocalStringManager.GetConfig("Name_language", "TownName_682")),
			new TownNameItem(683, LocalStringManager.GetConfig("Name_language", "TownName_683")),
			new TownNameItem(684, LocalStringManager.GetConfig("Name_language", "TownName_684")),
			new TownNameItem(685, LocalStringManager.GetConfig("Name_language", "TownName_685")),
			new TownNameItem(686, LocalStringManager.GetConfig("Name_language", "TownName_686")),
			new TownNameItem(687, LocalStringManager.GetConfig("Name_language", "TownName_687")),
			new TownNameItem(688, LocalStringManager.GetConfig("Name_language", "TownName_688")),
			new TownNameItem(689, LocalStringManager.GetConfig("Name_language", "TownName_689")),
			new TownNameItem(690, LocalStringManager.GetConfig("Name_language", "TownName_690")),
			new TownNameItem(691, LocalStringManager.GetConfig("Name_language", "TownName_691")),
			new TownNameItem(692, LocalStringManager.GetConfig("Name_language", "TownName_692")),
			new TownNameItem(693, LocalStringManager.GetConfig("Name_language", "TownName_693")),
			new TownNameItem(694, LocalStringManager.GetConfig("Name_language", "TownName_694")),
			new TownNameItem(695, LocalStringManager.GetConfig("Name_language", "TownName_695")),
			new TownNameItem(696, LocalStringManager.GetConfig("Name_language", "TownName_696")),
			new TownNameItem(697, LocalStringManager.GetConfig("Name_language", "TownName_697")),
			new TownNameItem(698, LocalStringManager.GetConfig("Name_language", "TownName_698")),
			new TownNameItem(699, LocalStringManager.GetConfig("Name_language", "TownName_699")),
			new TownNameItem(700, LocalStringManager.GetConfig("Name_language", "TownName_700")),
			new TownNameItem(701, LocalStringManager.GetConfig("Name_language", "TownName_701")),
			new TownNameItem(702, LocalStringManager.GetConfig("Name_language", "TownName_702")),
			new TownNameItem(703, LocalStringManager.GetConfig("Name_language", "TownName_703")),
			new TownNameItem(704, LocalStringManager.GetConfig("Name_language", "TownName_704")),
			new TownNameItem(705, LocalStringManager.GetConfig("Name_language", "TownName_705")),
			new TownNameItem(706, LocalStringManager.GetConfig("Name_language", "TownName_706")),
			new TownNameItem(707, LocalStringManager.GetConfig("Name_language", "TownName_707")),
			new TownNameItem(708, LocalStringManager.GetConfig("Name_language", "TownName_708")),
			new TownNameItem(709, LocalStringManager.GetConfig("Name_language", "TownName_709")),
			new TownNameItem(710, LocalStringManager.GetConfig("Name_language", "TownName_710")),
			new TownNameItem(711, LocalStringManager.GetConfig("Name_language", "TownName_711")),
			new TownNameItem(712, LocalStringManager.GetConfig("Name_language", "TownName_712")),
			new TownNameItem(713, LocalStringManager.GetConfig("Name_language", "TownName_713")),
			new TownNameItem(714, LocalStringManager.GetConfig("Name_language", "TownName_714")),
			new TownNameItem(715, LocalStringManager.GetConfig("Name_language", "TownName_715")),
			new TownNameItem(716, LocalStringManager.GetConfig("Name_language", "TownName_716")),
			new TownNameItem(717, LocalStringManager.GetConfig("Name_language", "TownName_717")),
			new TownNameItem(718, LocalStringManager.GetConfig("Name_language", "TownName_718")),
			new TownNameItem(719, LocalStringManager.GetConfig("Name_language", "TownName_719")),
			new TownNameItem(720, LocalStringManager.GetConfig("Name_language", "TownName_720")),
			new TownNameItem(721, LocalStringManager.GetConfig("Name_language", "TownName_721")),
			new TownNameItem(722, LocalStringManager.GetConfig("Name_language", "TownName_722")),
			new TownNameItem(723, LocalStringManager.GetConfig("Name_language", "TownName_723")),
			new TownNameItem(724, LocalStringManager.GetConfig("Name_language", "TownName_724")),
			new TownNameItem(725, LocalStringManager.GetConfig("Name_language", "TownName_725")),
			new TownNameItem(726, LocalStringManager.GetConfig("Name_language", "TownName_726")),
			new TownNameItem(727, LocalStringManager.GetConfig("Name_language", "TownName_727")),
			new TownNameItem(728, LocalStringManager.GetConfig("Name_language", "TownName_728")),
			new TownNameItem(729, LocalStringManager.GetConfig("Name_language", "TownName_729")),
			new TownNameItem(730, LocalStringManager.GetConfig("Name_language", "TownName_730")),
			new TownNameItem(731, LocalStringManager.GetConfig("Name_language", "TownName_731")),
			new TownNameItem(732, LocalStringManager.GetConfig("Name_language", "TownName_732")),
			new TownNameItem(733, LocalStringManager.GetConfig("Name_language", "TownName_733")),
			new TownNameItem(734, LocalStringManager.GetConfig("Name_language", "TownName_734")),
			new TownNameItem(735, LocalStringManager.GetConfig("Name_language", "TownName_735"))
		};
	}
}
