using System;
using System.Collections.Generic;
using Config.Common;

namespace Config;

[Serializable]
public class MonthlyNotificationSortingGroup : ConfigData<MonthlyNotificationSortingGroupItem, short>
{
	public static MonthlyNotificationSortingGroup Instance = new MonthlyNotificationSortingGroup();

	private readonly HashSet<string> RequiredFields = new HashSet<string> { "Name", "Desc", "TemplateId" };

	internal override int ToInt(short value)
	{
		return value;
	}

	internal override short ToTemplateId(int value)
	{
		return (short)value;
	}

	private void CreateItems0()
	{
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(0, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_0"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_0"), 0, onTop: true, hidden: true, 0u));
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(1, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_1"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_1"), 10, onTop: true, hidden: true, 0u));
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(2, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_2"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_2"), 10, onTop: true, hidden: true, 0u));
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(3, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_3"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_3"), 10, onTop: true, hidden: true, 0u));
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(4, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_4"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_4"), 10, onTop: true, hidden: true, 0u));
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(5, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_5"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_5"), 10, onTop: true, hidden: true, 0u));
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(6, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_6"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_6"), 10, onTop: true, hidden: true, 0u));
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(7, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_7"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_7"), 10, onTop: true, hidden: true, 0u));
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(8, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_8"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_8"), 10, onTop: true, hidden: true, 0u));
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(9, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_9"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_9"), 10, onTop: true, hidden: true, 0u));
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(10, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_10"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_10"), 10, onTop: true, hidden: true, 0u));
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(11, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_11"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_11"), 10, onTop: true, hidden: true, 0u));
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(12, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_12"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_12"), 10, onTop: true, hidden: true, 0u));
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(13, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_13"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_13"), 10, onTop: true, hidden: true, 0u));
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(14, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_14"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_14"), 10, onTop: true, hidden: true, 0u));
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(15, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_15"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_15"), 10, onTop: true, hidden: true, 0u));
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(16, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_16"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_16"), 10, onTop: true, hidden: true, 0u));
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(17, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_17"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_17"), 10, onTop: true, hidden: true, 0u));
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(18, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_18"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_18"), 10, onTop: true, hidden: true, 0u));
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(19, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_19"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_19"), 10, onTop: true, hidden: true, 0u));
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(20, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_20"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_20"), 10, onTop: true, hidden: true, 0u));
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(21, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_21"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_21"), 10, onTop: true, hidden: true, 0u));
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(22, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_22"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_22"), 10, onTop: true, hidden: true, 0u));
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(23, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_23"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_23"), 10, onTop: true, hidden: true, 0u));
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(24, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_24"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_24"), 10, onTop: true, hidden: true, 0u));
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(25, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_25"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_25"), 10, onTop: true, hidden: true, 0u));
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(26, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_26"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_26"), 10, onTop: true, hidden: true, 0u));
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(27, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_27"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_27"), 10, onTop: true, hidden: true, 0u));
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(28, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_28"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_28"), 10, onTop: true, hidden: true, 0u));
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(29, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_29"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_29"), 10, onTop: true, hidden: true, 0u));
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(30, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_30"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_30"), 10, onTop: true, hidden: true, 0u));
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(31, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_31"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_31"), 10, onTop: true, hidden: true, 0u));
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(32, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_32"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_32"), 10, onTop: true, hidden: true, 0u));
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(33, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_33"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_33"), 10, onTop: true, hidden: true, 0u));
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(34, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_34"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_34"), 10, onTop: true, hidden: true, 0u));
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(35, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_35"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_35"), 10, onTop: true, hidden: true, 0u));
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(36, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_36"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_36"), 10, onTop: true, hidden: true, 0u));
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(37, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_37"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_37"), 10, onTop: true, hidden: true, 2305890u));
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(38, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_38"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_38"), 10, onTop: true, hidden: true, 0u));
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(39, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_39"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_39"), 10, onTop: true, hidden: true, 0u));
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(40, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_40"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_40"), 10, onTop: true, hidden: true, 0u));
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(41, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_41"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_41"), 10, onTop: true, hidden: true, 0u));
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(42, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_42"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_42"), 10, onTop: true, hidden: true, 0u));
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(43, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_43"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_43"), 10, onTop: true, hidden: true, 0u));
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(44, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_44"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_44"), 10, onTop: true, hidden: true, 0u));
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(45, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_45"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_45"), 10, onTop: true, hidden: true, 0u));
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(46, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_46"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_46"), 10, onTop: true, hidden: true, 0u));
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(47, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_47"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_47"), 9000, onTop: true, hidden: true, 2764950u));
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(48, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_48"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_48"), 9000, onTop: true, hidden: true, 2764950u));
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(49, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_49"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_49"), 9000, onTop: true, hidden: true, 2764950u));
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(50, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_50"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_50"), 9000, onTop: true, hidden: true, 2764950u));
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(51, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_51"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_51"), 9000, onTop: true, hidden: true, 2764950u));
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(52, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_52"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_52"), 9000, onTop: true, hidden: true, 2764950u));
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(53, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_53"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_53"), 9000, onTop: true, hidden: true, 2764950u));
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(54, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_54"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_54"), 9000, onTop: true, hidden: true, 2764950u));
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(55, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_55"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_55"), 9000, onTop: true, hidden: true, 2764950u));
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(56, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_56"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_56"), 9000, onTop: true, hidden: true, 2764950u));
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(57, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_57"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_57"), 9000, onTop: true, hidden: true, 2764950u));
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(58, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_58"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_58"), 9000, onTop: true, hidden: true, 2764950u));
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(59, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_59"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_59"), 9000, onTop: true, hidden: true, 2764950u));
	}

	private void CreateItems1()
	{
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(60, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_60"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_60"), 800, onTop: true, hidden: true, 0u));
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(61, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_61"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_61"), 800, onTop: true, hidden: true, 0u));
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(62, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_62"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_62"), 800, onTop: true, hidden: true, 0u));
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(63, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_63"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_63"), 800, onTop: true, hidden: true, 0u));
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(64, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_64"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_64"), 800, onTop: true, hidden: true, 0u));
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(65, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_65"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_65"), 800, onTop: true, hidden: true, 0u));
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(66, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_66"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_66"), 800, onTop: true, hidden: true, 0u));
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(67, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_67"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_67"), 800, onTop: true, hidden: true, 0u));
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(68, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_68"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_68"), 1200, onTop: true, hidden: false, 0u));
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(69, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_69"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_69"), 1200, onTop: true, hidden: false, 0u));
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(70, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_70"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_70"), 1200, onTop: true, hidden: false, 0u));
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(71, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_71"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_71"), 1200, onTop: true, hidden: false, 0u));
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(72, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_72"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_72"), 1200, onTop: true, hidden: true, 0u));
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(73, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_73"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_73"), 1200, onTop: true, hidden: true, 0u));
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(74, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_74"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_74"), 1200, onTop: true, hidden: true, 0u));
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(75, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_75"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_75"), 1300, onTop: true, hidden: false, 0u));
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(76, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_76"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_76"), 1315, onTop: true, hidden: false, 0u));
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(77, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_77"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_77"), 1306, onTop: true, hidden: false, 0u));
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(78, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_78"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_78"), 1302, onTop: true, hidden: false, 0u));
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(79, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_79"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_79"), 1310, onTop: true, hidden: false, 0u));
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(80, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_80"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_80"), 1304, onTop: true, hidden: false, 0u));
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(81, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_81"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_81"), 1312, onTop: true, hidden: false, 0u));
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(82, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_82"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_82"), 1311, onTop: true, hidden: false, 0u));
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(83, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_83"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_83"), 1307, onTop: true, hidden: false, 0u));
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(84, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_84"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_84"), 1303, onTop: true, hidden: false, 0u));
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(85, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_85"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_85"), 1100, onTop: true, hidden: true, 0u));
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(86, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_86"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_86"), 1100, onTop: true, hidden: true, 0u));
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(87, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_87"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_87"), 1100, onTop: true, hidden: true, 0u));
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(88, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_88"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_88"), 1100, onTop: true, hidden: true, 0u));
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(89, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_89"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_89"), 1100, onTop: true, hidden: true, 0u));
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(90, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_90"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_90"), 900, onTop: true, hidden: true, 0u));
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(91, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_91"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_91"), 900, onTop: true, hidden: true, 0u));
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(92, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_92"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_92"), 900, onTop: true, hidden: true, 0u));
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(93, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_93"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_93"), 900, onTop: true, hidden: true, 0u));
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(94, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_94"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_94"), 900, onTop: true, hidden: true, 0u));
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(95, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_95"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_95"), 900, onTop: true, hidden: true, 0u));
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(96, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_96"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_96"), 900, onTop: true, hidden: true, 0u));
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(97, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_97"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_97"), 900, onTop: true, hidden: true, 0u));
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(98, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_98"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_98"), 900, onTop: true, hidden: true, 0u));
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(99, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_99"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_99"), 1000, onTop: true, hidden: true, 0u));
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(100, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_100"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_100"), 1000, onTop: true, hidden: true, 0u));
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(101, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_101"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_101"), 1000, onTop: true, hidden: true, 0u));
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(102, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_102"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_102"), 1000, onTop: true, hidden: true, 0u));
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(103, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_103"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_103"), 1000, onTop: true, hidden: true, 0u));
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(104, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_104"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_104"), 1000, onTop: true, hidden: true, 0u));
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(105, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_105"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_105"), 1000, onTop: true, hidden: true, 0u));
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(106, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_106"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_106"), 1000, onTop: true, hidden: true, 0u));
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(107, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_107"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_107"), 1000, onTop: true, hidden: true, 0u));
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(108, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_108"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_108"), 1000, onTop: true, hidden: true, 0u));
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(109, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_109"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_109"), 1000, onTop: true, hidden: true, 0u));
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(110, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_110"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_110"), 1000, onTop: true, hidden: true, 0u));
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(111, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_111"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_111"), 1000, onTop: true, hidden: true, 0u));
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(112, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_112"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_112"), 1000, onTop: true, hidden: true, 0u));
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(113, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_113"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_113"), 1000, onTop: true, hidden: true, 0u));
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(114, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_114"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_114"), 1000, onTop: true, hidden: true, 0u));
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(115, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_115"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_115"), 1000, onTop: true, hidden: true, 0u));
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(116, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_116"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_116"), 1000, onTop: true, hidden: true, 0u));
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(117, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_117"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_117"), 700, onTop: true, hidden: true, 0u));
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(118, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_118"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_118"), 700, onTop: true, hidden: true, 0u));
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(119, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_119"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_119"), 700, onTop: true, hidden: true, 0u));
	}

	private void CreateItems2()
	{
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(120, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_120"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_120"), 700, onTop: true, hidden: true, 0u));
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(121, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_121"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_121"), 500, onTop: true, hidden: true, 0u));
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(122, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_122"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_122"), 500, onTop: true, hidden: true, 0u));
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(123, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_123"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_123"), 500, onTop: true, hidden: true, 0u));
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(124, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_124"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_124"), 500, onTop: true, hidden: true, 0u));
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(125, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_125"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_125"), 500, onTop: true, hidden: true, 0u));
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(126, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_126"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_126"), 500, onTop: true, hidden: true, 0u));
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(127, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_127"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_127"), 500, onTop: true, hidden: true, 0u));
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(128, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_128"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_128"), 500, onTop: true, hidden: true, 0u));
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(129, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_129"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_129"), 500, onTop: true, hidden: true, 0u));
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(130, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_130"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_130"), 500, onTop: true, hidden: true, 0u));
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(131, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_131"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_131"), 500, onTop: true, hidden: true, 0u));
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(132, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_132"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_132"), 500, onTop: true, hidden: true, 0u));
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(133, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_133"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_133"), 500, onTop: true, hidden: true, 0u));
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(134, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_134"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_134"), 500, onTop: true, hidden: true, 0u));
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(135, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_135"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_135"), 500, onTop: true, hidden: true, 0u));
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(136, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_136"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_136"), 600, onTop: true, hidden: true, 0u));
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(137, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_137"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_137"), 600, onTop: true, hidden: true, 0u));
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(138, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_138"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_138"), 600, onTop: true, hidden: true, 0u));
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(139, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_139"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_139"), 600, onTop: true, hidden: true, 0u));
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(140, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_140"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_140"), 600, onTop: true, hidden: true, 0u));
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(141, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_141"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_141"), 600, onTop: true, hidden: true, 0u));
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(142, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_142"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_142"), 600, onTop: true, hidden: true, 0u));
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(143, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_143"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_143"), 600, onTop: true, hidden: true, 0u));
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(144, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_144"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_144"), 600, onTop: true, hidden: true, 0u));
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(145, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_145"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_145"), 600, onTop: true, hidden: true, 0u));
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(146, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_146"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_146"), 600, onTop: true, hidden: true, 0u));
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(147, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_147"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_147"), 600, onTop: true, hidden: true, 0u));
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(148, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_148"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_148"), 600, onTop: true, hidden: true, 0u));
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(149, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_149"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_149"), 600, onTop: true, hidden: true, 0u));
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(150, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_150"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_150"), 600, onTop: true, hidden: true, 0u));
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(151, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_151"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_151"), 600, onTop: true, hidden: true, 0u));
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(152, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_152"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_152"), 100, onTop: true, hidden: true, 0u));
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(153, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_153"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_153"), 100, onTop: true, hidden: true, 0u));
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(154, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_154"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_154"), 100, onTop: true, hidden: true, 0u));
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(155, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_155"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_155"), 100, onTop: true, hidden: true, 0u));
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(156, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_156"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_156"), 100, onTop: true, hidden: true, 0u));
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(157, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_157"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_157"), 200, onTop: true, hidden: true, 0u));
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(158, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_158"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_158"), 200, onTop: true, hidden: true, 0u));
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(159, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_159"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_159"), 200, onTop: true, hidden: true, 0u));
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(160, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_160"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_160"), 200, onTop: true, hidden: true, 0u));
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(161, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_161"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_161"), 200, onTop: true, hidden: true, 0u));
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(162, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_162"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_162"), 200, onTop: true, hidden: true, 0u));
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(163, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_163"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_163"), 200, onTop: true, hidden: true, 0u));
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(164, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_164"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_164"), 200, onTop: true, hidden: true, 0u));
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(165, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_165"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_165"), 1, onTop: true, hidden: true, 0u));
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(166, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_166"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_166"), 1, onTop: true, hidden: true, 0u));
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(167, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_167"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_167"), 1, onTop: true, hidden: true, 0u));
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(168, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_168"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_168"), 300, onTop: true, hidden: true, 0u));
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(169, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_169"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_169"), 300, onTop: true, hidden: true, 0u));
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(170, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_170"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_170"), 300, onTop: true, hidden: true, 0u));
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(171, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_171"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_171"), 300, onTop: true, hidden: true, 0u));
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(172, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_172"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_172"), 300, onTop: true, hidden: true, 0u));
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(173, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_173"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_173"), 300, onTop: true, hidden: true, 0u));
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(174, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_174"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_174"), 300, onTop: true, hidden: true, 0u));
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(175, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_175"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_175"), 300, onTop: true, hidden: true, 0u));
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(176, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_176"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_176"), 300, onTop: true, hidden: true, 0u));
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(177, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_177"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_177"), 300, onTop: true, hidden: true, 0u));
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(178, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_178"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_178"), 300, onTop: true, hidden: true, 0u));
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(179, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_179"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_179"), 300, onTop: true, hidden: true, 0u));
	}

	private void CreateItems3()
	{
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(180, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_180"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_180"), 300, onTop: true, hidden: true, 0u));
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(181, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_181"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_181"), 300, onTop: true, hidden: true, 0u));
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(182, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_182"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_182"), 300, onTop: true, hidden: true, 0u));
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(183, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_183"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_183"), 300, onTop: true, hidden: true, 0u));
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(184, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_184"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_184"), 400, onTop: true, hidden: true, 0u));
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(185, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_185"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_185"), 400, onTop: true, hidden: true, 0u));
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(186, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_186"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_186"), 400, onTop: true, hidden: true, 0u));
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(187, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_187"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_187"), 400, onTop: true, hidden: true, 0u));
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(188, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_188"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_188"), 400, onTop: true, hidden: true, 0u));
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(189, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_189"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_189"), 400, onTop: true, hidden: true, 0u));
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(190, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_190"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_190"), 400, onTop: true, hidden: true, 0u));
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(191, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_191"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_191"), 600, onTop: true, hidden: true, 0u));
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(192, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_192"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_192"), 900, onTop: true, hidden: true, 0u));
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(193, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_193"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_193"), 400, onTop: true, hidden: true, 0u));
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(194, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_194"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_194"), 1314, onTop: true, hidden: false, 0u));
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(195, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_195"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_195"), 1309, onTop: true, hidden: false, 0u));
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(196, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_196"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_196"), 601, onTop: true, hidden: true, 0u));
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(197, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_197"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_197"), 100, onTop: true, hidden: true, 0u));
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(198, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_198"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_198"), 200, onTop: true, hidden: true, 0u));
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(199, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_199"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_199"), 1316, onTop: true, hidden: false, 0u));
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(200, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_200"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_200"), 100, onTop: true, hidden: true, 0u));
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(201, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_201"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_201"), 1320, onTop: true, hidden: true, 0u));
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(202, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_202"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_202"), 300, onTop: true, hidden: true, 0u));
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(203, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_203"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_203"), 600, onTop: true, hidden: true, 0u));
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(204, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_204"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_204"), 400, onTop: true, hidden: true, 0u));
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(205, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_205"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_205"), 300, onTop: true, hidden: true, 0u));
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(206, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_206"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_206"), 300, onTop: true, hidden: true, 0u));
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(207, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_207"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_207"), 600, onTop: true, hidden: true, 0u));
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(208, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_208"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_208"), 600, onTop: true, hidden: true, 0u));
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(209, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_209"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_209"), 1321, onTop: true, hidden: false, 0u));
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(210, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_210"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_210"), 300, onTop: true, hidden: true, 0u));
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(211, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_211"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_211"), 300, onTop: true, hidden: true, 0u));
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(212, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_212"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_212"), 150, onTop: true, hidden: true, 0u));
		_dataArray.Add(new MonthlyNotificationSortingGroupItem(213, LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Name_213"), LocalStringManager.GetConfig("MonthlyNotificationSortingGroup_language", "Desc_213"), 1000, onTop: true, hidden: true, 0u));
	}

	public override void Init()
	{
		base.Init();
		_dataArray = new List<MonthlyNotificationSortingGroupItem>(214);
		CreateItems0();
		CreateItems1();
		CreateItems2();
		CreateItems3();
	}
}
