using System;
using System.Collections.Generic;
using Config.Common;

namespace Config;

[Serializable]
public class SecretInformationSpecialCondition : ConfigData<SecretInformationSpecialConditionItem, short>
{
	/// <summary>
	/// 配置表定义Key
	/// </summary>
	public static class DefKey
	{
		/// <summary>
		/// 无
		/// </summary>
		public const short None = 0;

		/// <summary>
		/// 敌对门派
		/// </summary>
		public const short SectBecomeEnemy = 3;

		/// <summary>
		/// 玩家战斗
		/// </summary>
		public const short TaiwuFight = 17;

		/// <summary>
		/// 战力比拼
		/// </summary>
		public const short CompareCombatPoint = 23;

		/// <summary>
		/// 违法犯罪
		/// </summary>
		public const short BreakTheLaw = 54;
	}

	/// <summary>
	/// 配置表快捷访问
	/// </summary>
	public static class DefValue
	{
		/// <summary>
		/// 无
		/// </summary>
		public static SecretInformationSpecialConditionItem None => Instance[(short)0];

		/// <summary>
		/// 敌对门派
		/// </summary>
		public static SecretInformationSpecialConditionItem SectBecomeEnemy => Instance[(short)3];

		/// <summary>
		/// 玩家战斗
		/// </summary>
		public static SecretInformationSpecialConditionItem TaiwuFight => Instance[(short)17];

		/// <summary>
		/// 战力比拼
		/// </summary>
		public static SecretInformationSpecialConditionItem CompareCombatPoint => Instance[(short)23];

		/// <summary>
		/// 违法犯罪
		/// </summary>
		public static SecretInformationSpecialConditionItem BreakTheLaw => Instance[(short)54];
	}

	/// <summary>
	/// 配置表实例
	/// </summary>
	public static SecretInformationSpecialCondition Instance = new SecretInformationSpecialCondition();

	private readonly HashSet<string> RequiredFields = new HashSet<string> { "Name", "CalcSectRule", "CalcOrganization", "TemplateId" };

	internal override int ToInt(short value)
	{
		return value;
	}

	internal override short ToTemplateId(int value)
	{
		return (short)value;
	}

	private void CreateItems0()
	{
		_dataArray.Add(new SecretInformationSpecialConditionItem(0, LocalStringManager.GetConfig("SecretInformationSpecialCondition_language", "Name_0"), new short[5], ESecretInformationSpecialConditionCalculate.None, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, -1));
		_dataArray.Add(new SecretInformationSpecialConditionItem(1, LocalStringManager.GetConfig("SecretInformationSpecialCondition_language", "Name_1"), new short[5] { 20, 10, 40, 30, 50 }, ESecretInformationSpecialConditionCalculate.SameSect, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, -1));
		_dataArray.Add(new SecretInformationSpecialConditionItem(2, LocalStringManager.GetConfig("SecretInformationSpecialCondition_language", "Name_2"), new short[5], ESecretInformationSpecialConditionCalculate.SectJustice, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, -1));
		_dataArray.Add(new SecretInformationSpecialConditionItem(3, LocalStringManager.GetConfig("SecretInformationSpecialCondition_language", "Name_3"), new short[5] { 0, 10, 20, -10, 30 }, ESecretInformationSpecialConditionCalculate.SectBecomeEnemy, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, -1));
		_dataArray.Add(new SecretInformationSpecialConditionItem(4, LocalStringManager.GetConfig("SecretInformationSpecialCondition_language", "Name_4"), new short[5] { 30, 20, 40, 50, 60 }, ESecretInformationSpecialConditionCalculate.ForbidMarriage, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, -1));
		_dataArray.Add(new SecretInformationSpecialConditionItem(5, LocalStringManager.GetConfig("SecretInformationSpecialCondition_language", "Name_5"), new short[5], ESecretInformationSpecialConditionCalculate.IsPublished, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, -1));
		_dataArray.Add(new SecretInformationSpecialConditionItem(6, LocalStringManager.GetConfig("SecretInformationSpecialCondition_language", "Name_6"), new short[5] { 20, 10, 30, 0, 40 }, ESecretInformationSpecialConditionCalculate.IsRevealed, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, -1));
		_dataArray.Add(new SecretInformationSpecialConditionItem(7, LocalStringManager.GetConfig("SecretInformationSpecialCondition_language", "Name_7"), new short[5] { 20, 0, 10, 0, 30 }, ESecretInformationSpecialConditionCalculate.IsRevealedSingle, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, -1));
		_dataArray.Add(new SecretInformationSpecialConditionItem(8, LocalStringManager.GetConfig("SecretInformationSpecialCondition_language", "Name_8"), new short[5] { 20, 0, 10, 0, 30 }, ESecretInformationSpecialConditionCalculate.HasCouple, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, -1));
		_dataArray.Add(new SecretInformationSpecialConditionItem(9, LocalStringManager.GetConfig("SecretInformationSpecialCondition_language", "Name_9"), new short[5], ESecretInformationSpecialConditionCalculate.NotFame, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, -1));
		_dataArray.Add(new SecretInformationSpecialConditionItem(10, LocalStringManager.GetConfig("SecretInformationSpecialCondition_language", "Name_10"), new short[5], ESecretInformationSpecialConditionCalculate.IsMonk, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, -1));
		_dataArray.Add(new SecretInformationSpecialConditionItem(11, LocalStringManager.GetConfig("SecretInformationSpecialCondition_language", "Name_11"), new short[5], ESecretInformationSpecialConditionCalculate.ForbidWine, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, -1));
		_dataArray.Add(new SecretInformationSpecialConditionItem(12, LocalStringManager.GetConfig("SecretInformationSpecialCondition_language", "Name_12"), new short[5], ESecretInformationSpecialConditionCalculate.ForbidPoison, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, -1));
		_dataArray.Add(new SecretInformationSpecialConditionItem(13, LocalStringManager.GetConfig("SecretInformationSpecialCondition_language", "Name_13"), new short[5], ESecretInformationSpecialConditionCalculate.ForbidItem, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, -1));
		_dataArray.Add(new SecretInformationSpecialConditionItem(14, LocalStringManager.GetConfig("SecretInformationSpecialCondition_language", "Name_14"), new short[5], ESecretInformationSpecialConditionCalculate.HasLove, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, -1));
		_dataArray.Add(new SecretInformationSpecialConditionItem(15, LocalStringManager.GetConfig("SecretInformationSpecialCondition_language", "Name_15"), new short[5], ESecretInformationSpecialConditionCalculate.HasRelation, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, -1));
		_dataArray.Add(new SecretInformationSpecialConditionItem(16, LocalStringManager.GetConfig("SecretInformationSpecialCondition_language", "Name_16"), new short[5], ESecretInformationSpecialConditionCalculate.IsKidnapped, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, -1));
		_dataArray.Add(new SecretInformationSpecialConditionItem(17, LocalStringManager.GetConfig("SecretInformationSpecialCondition_language", "Name_17"), new short[5], ESecretInformationSpecialConditionCalculate.TaiwuFight, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, -1));
		_dataArray.Add(new SecretInformationSpecialConditionItem(18, LocalStringManager.GetConfig("SecretInformationSpecialCondition_language", "Name_18"), new short[5], ESecretInformationSpecialConditionCalculate.TaiwuSteal, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, -1));
		_dataArray.Add(new SecretInformationSpecialConditionItem(19, LocalStringManager.GetConfig("SecretInformationSpecialCondition_language", "Name_19"), new short[5], ESecretInformationSpecialConditionCalculate.TaiwuScam, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, -1));
		_dataArray.Add(new SecretInformationSpecialConditionItem(20, LocalStringManager.GetConfig("SecretInformationSpecialCondition_language", "Name_20"), new short[5], ESecretInformationSpecialConditionCalculate.TaiwuRob, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, -1));
		_dataArray.Add(new SecretInformationSpecialConditionItem(21, LocalStringManager.GetConfig("SecretInformationSpecialCondition_language", "Name_21"), new short[5], ESecretInformationSpecialConditionCalculate.TaiwuRescueEscape, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, -1));
		_dataArray.Add(new SecretInformationSpecialConditionItem(22, LocalStringManager.GetConfig("SecretInformationSpecialCondition_language", "Name_22"), new short[5], ESecretInformationSpecialConditionCalculate.CharRescueEscape, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, -1));
		_dataArray.Add(new SecretInformationSpecialConditionItem(23, LocalStringManager.GetConfig("SecretInformationSpecialCondition_language", "Name_23"), new short[5], ESecretInformationSpecialConditionCalculate.CompareCombatPoint, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, -1));
		_dataArray.Add(new SecretInformationSpecialConditionItem(24, LocalStringManager.GetConfig("SecretInformationSpecialCondition_language", "Name_24"), new short[5], ESecretInformationSpecialConditionCalculate.CharFight, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, -1));
		_dataArray.Add(new SecretInformationSpecialConditionItem(25, LocalStringManager.GetConfig("SecretInformationSpecialCondition_language", "Name_25"), new short[5], ESecretInformationSpecialConditionCalculate.RefuseKeep, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, -1));
		_dataArray.Add(new SecretInformationSpecialConditionItem(26, LocalStringManager.GetConfig("SecretInformationSpecialCondition_language", "Name_26"), new short[5], ESecretInformationSpecialConditionCalculate.CharRescue, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, -1));
		_dataArray.Add(new SecretInformationSpecialConditionItem(27, LocalStringManager.GetConfig("SecretInformationSpecialCondition_language", "Name_27"), new short[5], ESecretInformationSpecialConditionCalculate.CharWin, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, -1));
		_dataArray.Add(new SecretInformationSpecialConditionItem(28, LocalStringManager.GetConfig("SecretInformationSpecialCondition_language", "Name_28"), new short[5], ESecretInformationSpecialConditionCalculate.CharJudge, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, -1));
		_dataArray.Add(new SecretInformationSpecialConditionItem(29, LocalStringManager.GetConfig("SecretInformationSpecialCondition_language", "Name_29"), new short[5], ESecretInformationSpecialConditionCalculate.CharKidnap, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, -1));
		_dataArray.Add(new SecretInformationSpecialConditionItem(30, LocalStringManager.GetConfig("SecretInformationSpecialCondition_language", "Name_30"), new short[5], ESecretInformationSpecialConditionCalculate.TaiwuEscape, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, -1));
		_dataArray.Add(new SecretInformationSpecialConditionItem(31, LocalStringManager.GetConfig("SecretInformationSpecialCondition_language", "Name_31"), new short[5], ESecretInformationSpecialConditionCalculate.CharEscape, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, -1));
		_dataArray.Add(new SecretInformationSpecialConditionItem(32, LocalStringManager.GetConfig("SecretInformationSpecialCondition_language", "Name_32"), new short[5], ESecretInformationSpecialConditionCalculate.StartFight, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, -1));
		_dataArray.Add(new SecretInformationSpecialConditionItem(33, LocalStringManager.GetConfig("SecretInformationSpecialCondition_language", "Name_33"), new short[5], ESecretInformationSpecialConditionCalculate.StartLifeSkillCombat, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, -1));
		_dataArray.Add(new SecretInformationSpecialConditionItem(34, LocalStringManager.GetConfig("SecretInformationSpecialCondition_language", "Name_34"), new short[5], ESecretInformationSpecialConditionCalculate.ChooseRope, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, -1));
		_dataArray.Add(new SecretInformationSpecialConditionItem(35, LocalStringManager.GetConfig("SecretInformationSpecialCondition_language", "Name_35"), new short[5], ESecretInformationSpecialConditionCalculate.KidnapWithRope, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, -1));
		_dataArray.Add(new SecretInformationSpecialConditionItem(36, LocalStringManager.GetConfig("SecretInformationSpecialCondition_language", "Name_36"), new short[5], ESecretInformationSpecialConditionCalculate.CharAdore, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, -1));
		_dataArray.Add(new SecretInformationSpecialConditionItem(37, LocalStringManager.GetConfig("SecretInformationSpecialCondition_language", "Name_37"), new short[5], ESecretInformationSpecialConditionCalculate.TaiwuAdore, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, -1));
		_dataArray.Add(new SecretInformationSpecialConditionItem(38, LocalStringManager.GetConfig("SecretInformationSpecialCondition_language", "Name_38"), new short[5], ESecretInformationSpecialConditionCalculate.TaiwuDeleteInfomation, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, -1));
		_dataArray.Add(new SecretInformationSpecialConditionItem(39, LocalStringManager.GetConfig("SecretInformationSpecialCondition_language", "Name_39"), new short[5], ESecretInformationSpecialConditionCalculate.CharDeleteInfomation, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, -1));
		_dataArray.Add(new SecretInformationSpecialConditionItem(40, LocalStringManager.GetConfig("SecretInformationSpecialCondition_language", "Name_40"), new short[5], ESecretInformationSpecialConditionCalculate.CharBreakUp, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, -1));
		_dataArray.Add(new SecretInformationSpecialConditionItem(41, LocalStringManager.GetConfig("SecretInformationSpecialCondition_language", "Name_41"), new short[5], ESecretInformationSpecialConditionCalculate.TaiwuEndAdored, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, -1));
		_dataArray.Add(new SecretInformationSpecialConditionItem(42, LocalStringManager.GetConfig("SecretInformationSpecialCondition_language", "Name_42"), new short[5], ESecretInformationSpecialConditionCalculate.CharEndAdored, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, -1));
		_dataArray.Add(new SecretInformationSpecialConditionItem(43, LocalStringManager.GetConfig("SecretInformationSpecialCondition_language", "Name_43"), new short[5], ESecretInformationSpecialConditionCalculate.Forgive, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, -1));
		_dataArray.Add(new SecretInformationSpecialConditionItem(44, LocalStringManager.GetConfig("SecretInformationSpecialCondition_language", "Name_44"), new short[5], ESecretInformationSpecialConditionCalculate.NotForgiveRape, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, -1));
		_dataArray.Add(new SecretInformationSpecialConditionItem(45, LocalStringManager.GetConfig("SecretInformationSpecialCondition_language", "Name_45"), new short[5], ESecretInformationSpecialConditionCalculate.ApplyOfLeader, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, -1));
		_dataArray.Add(new SecretInformationSpecialConditionItem(46, LocalStringManager.GetConfig("SecretInformationSpecialCondition_language", "Name_46"), new short[5], ESecretInformationSpecialConditionCalculate.LawBreaker, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, -1));
		_dataArray.Add(new SecretInformationSpecialConditionItem(47, LocalStringManager.GetConfig("SecretInformationSpecialCondition_language", "Name_47"), new short[5], ESecretInformationSpecialConditionCalculate.AskCharKeep, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, -1));
		_dataArray.Add(new SecretInformationSpecialConditionItem(48, LocalStringManager.GetConfig("SecretInformationSpecialCondition_language", "Name_48"), new short[5], ESecretInformationSpecialConditionCalculate.AskCharRelease, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, -1));
		_dataArray.Add(new SecretInformationSpecialConditionItem(49, LocalStringManager.GetConfig("SecretInformationSpecialCondition_language", "Name_49"), new short[5], ESecretInformationSpecialConditionCalculate.AskCharBreakup, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, -1));
		_dataArray.Add(new SecretInformationSpecialConditionItem(50, LocalStringManager.GetConfig("SecretInformationSpecialCondition_language", "Name_50"), new short[5], ESecretInformationSpecialConditionCalculate.BreakupWithChar, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, -1));
		_dataArray.Add(new SecretInformationSpecialConditionItem(51, LocalStringManager.GetConfig("SecretInformationSpecialCondition_language", "Name_51"), new short[5], ESecretInformationSpecialConditionCalculate.ForceBreakupWithChar, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, -1));
		_dataArray.Add(new SecretInformationSpecialConditionItem(52, LocalStringManager.GetConfig("SecretInformationSpecialCondition_language", "Name_52"), new short[5], ESecretInformationSpecialConditionCalculate.ShowFristContent, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, -1));
		_dataArray.Add(new SecretInformationSpecialConditionItem(53, LocalStringManager.GetConfig("SecretInformationSpecialCondition_language", "Name_53"), new short[5], ESecretInformationSpecialConditionCalculate.ActorAlive, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, -1));
		_dataArray.Add(new SecretInformationSpecialConditionItem(54, LocalStringManager.GetConfig("SecretInformationSpecialCondition_language", "Name_54"), new short[5], ESecretInformationSpecialConditionCalculate.BreakTheLaw, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, -1));
		_dataArray.Add(new SecretInformationSpecialConditionItem(55, LocalStringManager.GetConfig("SecretInformationSpecialCondition_language", "Name_55"), new short[5], ESecretInformationSpecialConditionCalculate.CasualtyInSect, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, -1));
		_dataArray.Add(new SecretInformationSpecialConditionItem(56, LocalStringManager.GetConfig("SecretInformationSpecialCondition_language", "Name_56"), new short[5], ESecretInformationSpecialConditionCalculate.KillFameLine, ESecretInformationSpecialConditionCalcFameLine.Renowned, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, -1));
		_dataArray.Add(new SecretInformationSpecialConditionItem(57, LocalStringManager.GetConfig("SecretInformationSpecialCondition_language", "Name_57"), new short[5], ESecretInformationSpecialConditionCalculate.KillFameLine, ESecretInformationSpecialConditionCalcFameLine.Badboy, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, -1));
		_dataArray.Add(new SecretInformationSpecialConditionItem(58, LocalStringManager.GetConfig("SecretInformationSpecialCondition_language", "Name_58"), new short[5], ESecretInformationSpecialConditionCalculate.KillFameLine, ESecretInformationSpecialConditionCalcFameLine.SuperStar, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, -1));
		_dataArray.Add(new SecretInformationSpecialConditionItem(59, LocalStringManager.GetConfig("SecretInformationSpecialCondition_language", "Name_59"), new short[5], ESecretInformationSpecialConditionCalculate.KidnapFameLine, ESecretInformationSpecialConditionCalcFameLine.Renowned, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, -1));
	}

	private void CreateItems1()
	{
		_dataArray.Add(new SecretInformationSpecialConditionItem(60, LocalStringManager.GetConfig("SecretInformationSpecialCondition_language", "Name_60"), new short[5], ESecretInformationSpecialConditionCalculate.KidnapFameLine, ESecretInformationSpecialConditionCalcFameLine.Badboy, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, -1));
		_dataArray.Add(new SecretInformationSpecialConditionItem(61, LocalStringManager.GetConfig("SecretInformationSpecialCondition_language", "Name_61"), new short[5], ESecretInformationSpecialConditionCalculate.KidnapFameLine, ESecretInformationSpecialConditionCalcFameLine.SuperStar, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, -1));
		_dataArray.Add(new SecretInformationSpecialConditionItem(62, LocalStringManager.GetConfig("SecretInformationSpecialCondition_language", "Name_62"), new short[5], ESecretInformationSpecialConditionCalculate.AlliedSectMember, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, 1));
		_dataArray.Add(new SecretInformationSpecialConditionItem(63, LocalStringManager.GetConfig("SecretInformationSpecialCondition_language", "Name_63"), new short[5], ESecretInformationSpecialConditionCalculate.AlliedSectMember, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, 2));
		_dataArray.Add(new SecretInformationSpecialConditionItem(64, LocalStringManager.GetConfig("SecretInformationSpecialCondition_language", "Name_64"), new short[5], ESecretInformationSpecialConditionCalculate.AlliedSectMember, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, 3));
		_dataArray.Add(new SecretInformationSpecialConditionItem(65, LocalStringManager.GetConfig("SecretInformationSpecialCondition_language", "Name_65"), new short[5], ESecretInformationSpecialConditionCalculate.AlliedSectMember, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, 4));
		_dataArray.Add(new SecretInformationSpecialConditionItem(66, LocalStringManager.GetConfig("SecretInformationSpecialCondition_language", "Name_66"), new short[5], ESecretInformationSpecialConditionCalculate.AlliedSectMember, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, 5));
		_dataArray.Add(new SecretInformationSpecialConditionItem(67, LocalStringManager.GetConfig("SecretInformationSpecialCondition_language", "Name_67"), new short[5], ESecretInformationSpecialConditionCalculate.AlliedSectMember, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, 6));
		_dataArray.Add(new SecretInformationSpecialConditionItem(68, LocalStringManager.GetConfig("SecretInformationSpecialCondition_language", "Name_68"), new short[5], ESecretInformationSpecialConditionCalculate.AlliedSectMember, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, 7));
		_dataArray.Add(new SecretInformationSpecialConditionItem(69, LocalStringManager.GetConfig("SecretInformationSpecialCondition_language", "Name_69"), new short[5], ESecretInformationSpecialConditionCalculate.AlliedSectMember, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, 8));
		_dataArray.Add(new SecretInformationSpecialConditionItem(70, LocalStringManager.GetConfig("SecretInformationSpecialCondition_language", "Name_70"), new short[5], ESecretInformationSpecialConditionCalculate.AlliedSectMember, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, 9));
		_dataArray.Add(new SecretInformationSpecialConditionItem(71, LocalStringManager.GetConfig("SecretInformationSpecialCondition_language", "Name_71"), new short[5], ESecretInformationSpecialConditionCalculate.AlliedSectMember, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, 10));
		_dataArray.Add(new SecretInformationSpecialConditionItem(72, LocalStringManager.GetConfig("SecretInformationSpecialCondition_language", "Name_72"), new short[5], ESecretInformationSpecialConditionCalculate.AlliedSectMember, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, 11));
		_dataArray.Add(new SecretInformationSpecialConditionItem(73, LocalStringManager.GetConfig("SecretInformationSpecialCondition_language", "Name_73"), new short[5], ESecretInformationSpecialConditionCalculate.AlliedSectMember, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, 12));
		_dataArray.Add(new SecretInformationSpecialConditionItem(74, LocalStringManager.GetConfig("SecretInformationSpecialCondition_language", "Name_74"), new short[5], ESecretInformationSpecialConditionCalculate.AlliedSectMember, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, 13));
		_dataArray.Add(new SecretInformationSpecialConditionItem(75, LocalStringManager.GetConfig("SecretInformationSpecialCondition_language", "Name_75"), new short[5], ESecretInformationSpecialConditionCalculate.AlliedSectMember, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, 14));
		_dataArray.Add(new SecretInformationSpecialConditionItem(76, LocalStringManager.GetConfig("SecretInformationSpecialCondition_language", "Name_76"), new short[5], ESecretInformationSpecialConditionCalculate.AlliedSectMember, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, 15));
		_dataArray.Add(new SecretInformationSpecialConditionItem(77, LocalStringManager.GetConfig("SecretInformationSpecialCondition_language", "Name_77"), new short[5], ESecretInformationSpecialConditionCalculate.BanSexualMate, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.GainChild, ESecretInformationSpecialConditionCalcSexualMateRule.AllMember, 44, -1));
		_dataArray.Add(new SecretInformationSpecialConditionItem(78, LocalStringManager.GetConfig("SecretInformationSpecialCondition_language", "Name_78"), new short[5], ESecretInformationSpecialConditionCalculate.BanSexualMate, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.GainChild, ESecretInformationSpecialConditionCalcSexualMateRule.NoCommonHuman, 45, -1));
		_dataArray.Add(new SecretInformationSpecialConditionItem(79, LocalStringManager.GetConfig("SecretInformationSpecialCondition_language", "Name_79"), new short[5], ESecretInformationSpecialConditionCalculate.BanSexualMate, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.GainChild, ESecretInformationSpecialConditionCalcSexualMateRule.GradeHigh, 46, -1));
		_dataArray.Add(new SecretInformationSpecialConditionItem(80, LocalStringManager.GetConfig("SecretInformationSpecialCondition_language", "Name_80"), new short[5], ESecretInformationSpecialConditionCalculate.BanSexualMate, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.BeLover, ESecretInformationSpecialConditionCalcSexualMateRule.AllMember, 47, -1));
		_dataArray.Add(new SecretInformationSpecialConditionItem(81, LocalStringManager.GetConfig("SecretInformationSpecialCondition_language", "Name_81"), new short[5], ESecretInformationSpecialConditionCalculate.BanSexualMate, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.BeLover, ESecretInformationSpecialConditionCalcSexualMateRule.NoCommonHuman, 48, -1));
		_dataArray.Add(new SecretInformationSpecialConditionItem(82, LocalStringManager.GetConfig("SecretInformationSpecialCondition_language", "Name_82"), new short[5], ESecretInformationSpecialConditionCalculate.BanSexualMate, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.BeLover, ESecretInformationSpecialConditionCalcSexualMateRule.GradeHigh, 49, -1));
		_dataArray.Add(new SecretInformationSpecialConditionItem(83, LocalStringManager.GetConfig("SecretInformationSpecialCondition_language", "Name_83"), new short[5], ESecretInformationSpecialConditionCalculate.BanSexualMate, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.BeHusband, ESecretInformationSpecialConditionCalcSexualMateRule.AllMember, 50, -1));
		_dataArray.Add(new SecretInformationSpecialConditionItem(84, LocalStringManager.GetConfig("SecretInformationSpecialCondition_language", "Name_84"), new short[5], ESecretInformationSpecialConditionCalculate.BanSexualMate, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.BeHusband, ESecretInformationSpecialConditionCalcSexualMateRule.NoCommonHuman, 51, -1));
		_dataArray.Add(new SecretInformationSpecialConditionItem(85, LocalStringManager.GetConfig("SecretInformationSpecialCondition_language", "Name_85"), new short[5], ESecretInformationSpecialConditionCalculate.BanSexualMate, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.BeHusband, ESecretInformationSpecialConditionCalcSexualMateRule.GradeHigh, 52, -1));
		_dataArray.Add(new SecretInformationSpecialConditionItem(86, LocalStringManager.GetConfig("SecretInformationSpecialCondition_language", "Name_86"), new short[5], ESecretInformationSpecialConditionCalculate.BanSexualMate, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.SexInvalid, ESecretInformationSpecialConditionCalcSexualMateRule.AllMember, 53, -1));
		_dataArray.Add(new SecretInformationSpecialConditionItem(87, LocalStringManager.GetConfig("SecretInformationSpecialCondition_language", "Name_87"), new short[5], ESecretInformationSpecialConditionCalculate.BanSexualMate, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.SexInvalid, ESecretInformationSpecialConditionCalcSexualMateRule.NoCommonHuman, 54, -1));
		_dataArray.Add(new SecretInformationSpecialConditionItem(88, LocalStringManager.GetConfig("SecretInformationSpecialCondition_language", "Name_88"), new short[5], ESecretInformationSpecialConditionCalculate.BanSexualMate, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.SexInvalid, ESecretInformationSpecialConditionCalcSexualMateRule.GradeHigh, 55, -1));
		_dataArray.Add(new SecretInformationSpecialConditionItem(89, LocalStringManager.GetConfig("SecretInformationSpecialCondition_language", "Name_89"), new short[5], ESecretInformationSpecialConditionCalculate.BanSexualMate, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.SexNotAllow, ESecretInformationSpecialConditionCalcSexualMateRule.AllMember, 56, -1));
		_dataArray.Add(new SecretInformationSpecialConditionItem(90, LocalStringManager.GetConfig("SecretInformationSpecialCondition_language", "Name_90"), new short[5], ESecretInformationSpecialConditionCalculate.BanSexualMate, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.SexNotAllow, ESecretInformationSpecialConditionCalcSexualMateRule.NoCommonHuman, 57, -1));
		_dataArray.Add(new SecretInformationSpecialConditionItem(91, LocalStringManager.GetConfig("SecretInformationSpecialCondition_language", "Name_91"), new short[5], ESecretInformationSpecialConditionCalculate.BanSexualMate, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.SexNotAllow, ESecretInformationSpecialConditionCalcSexualMateRule.GradeHigh, 58, -1));
		_dataArray.Add(new SecretInformationSpecialConditionItem(92, LocalStringManager.GetConfig("SecretInformationSpecialCondition_language", "Name_92"), new short[5], ESecretInformationSpecialConditionCalculate.BanSexualMate, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Date, ESecretInformationSpecialConditionCalcSexualMateRule.AllMember, 59, -1));
		_dataArray.Add(new SecretInformationSpecialConditionItem(93, LocalStringManager.GetConfig("SecretInformationSpecialCondition_language", "Name_93"), new short[5], ESecretInformationSpecialConditionCalculate.BanSexualMate, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Date, ESecretInformationSpecialConditionCalcSexualMateRule.NoCommonHuman, 60, -1));
		_dataArray.Add(new SecretInformationSpecialConditionItem(94, LocalStringManager.GetConfig("SecretInformationSpecialCondition_language", "Name_94"), new short[5], ESecretInformationSpecialConditionCalculate.BanSexualMate, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Date, ESecretInformationSpecialConditionCalcSexualMateRule.GradeHigh, 61, -1));
		_dataArray.Add(new SecretInformationSpecialConditionItem(95, LocalStringManager.GetConfig("SecretInformationSpecialCondition_language", "Name_95"), new short[5], ESecretInformationSpecialConditionCalculate.BeLoverSectMember, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, 1));
		_dataArray.Add(new SecretInformationSpecialConditionItem(96, LocalStringManager.GetConfig("SecretInformationSpecialCondition_language", "Name_96"), new short[5], ESecretInformationSpecialConditionCalculate.BeLoverSectMember, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, 2));
		_dataArray.Add(new SecretInformationSpecialConditionItem(97, LocalStringManager.GetConfig("SecretInformationSpecialCondition_language", "Name_97"), new short[5], ESecretInformationSpecialConditionCalculate.BeLoverSectMember, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, 3));
		_dataArray.Add(new SecretInformationSpecialConditionItem(98, LocalStringManager.GetConfig("SecretInformationSpecialCondition_language", "Name_98"), new short[5], ESecretInformationSpecialConditionCalculate.BeLoverSectMember, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, 4));
		_dataArray.Add(new SecretInformationSpecialConditionItem(99, LocalStringManager.GetConfig("SecretInformationSpecialCondition_language", "Name_99"), new short[5], ESecretInformationSpecialConditionCalculate.BeLoverSectMember, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, 5));
		_dataArray.Add(new SecretInformationSpecialConditionItem(100, LocalStringManager.GetConfig("SecretInformationSpecialCondition_language", "Name_100"), new short[5], ESecretInformationSpecialConditionCalculate.BeLoverSectMember, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, 6));
		_dataArray.Add(new SecretInformationSpecialConditionItem(101, LocalStringManager.GetConfig("SecretInformationSpecialCondition_language", "Name_101"), new short[5], ESecretInformationSpecialConditionCalculate.BeLoverSectMember, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, 7));
		_dataArray.Add(new SecretInformationSpecialConditionItem(102, LocalStringManager.GetConfig("SecretInformationSpecialCondition_language", "Name_102"), new short[5], ESecretInformationSpecialConditionCalculate.BeLoverSectMember, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, 8));
		_dataArray.Add(new SecretInformationSpecialConditionItem(103, LocalStringManager.GetConfig("SecretInformationSpecialCondition_language", "Name_103"), new short[5], ESecretInformationSpecialConditionCalculate.BeLoverSectMember, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, 9));
		_dataArray.Add(new SecretInformationSpecialConditionItem(104, LocalStringManager.GetConfig("SecretInformationSpecialCondition_language", "Name_104"), new short[5], ESecretInformationSpecialConditionCalculate.BeLoverSectMember, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, 10));
		_dataArray.Add(new SecretInformationSpecialConditionItem(105, LocalStringManager.GetConfig("SecretInformationSpecialCondition_language", "Name_105"), new short[5], ESecretInformationSpecialConditionCalculate.BeLoverSectMember, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, 11));
		_dataArray.Add(new SecretInformationSpecialConditionItem(106, LocalStringManager.GetConfig("SecretInformationSpecialCondition_language", "Name_106"), new short[5], ESecretInformationSpecialConditionCalculate.BeLoverSectMember, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, 12));
		_dataArray.Add(new SecretInformationSpecialConditionItem(107, LocalStringManager.GetConfig("SecretInformationSpecialCondition_language", "Name_107"), new short[5], ESecretInformationSpecialConditionCalculate.BeLoverSectMember, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, 13));
		_dataArray.Add(new SecretInformationSpecialConditionItem(108, LocalStringManager.GetConfig("SecretInformationSpecialCondition_language", "Name_108"), new short[5], ESecretInformationSpecialConditionCalculate.BeLoverSectMember, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, 14));
		_dataArray.Add(new SecretInformationSpecialConditionItem(109, LocalStringManager.GetConfig("SecretInformationSpecialCondition_language", "Name_109"), new short[5], ESecretInformationSpecialConditionCalculate.BeLoverSectMember, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, 15));
		_dataArray.Add(new SecretInformationSpecialConditionItem(110, LocalStringManager.GetConfig("SecretInformationSpecialCondition_language", "Name_110"), new short[5], ESecretInformationSpecialConditionCalculate.BeKyodaiSectMember, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, 1));
		_dataArray.Add(new SecretInformationSpecialConditionItem(111, LocalStringManager.GetConfig("SecretInformationSpecialCondition_language", "Name_111"), new short[5], ESecretInformationSpecialConditionCalculate.BeKyodaiSectMember, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, 2));
		_dataArray.Add(new SecretInformationSpecialConditionItem(112, LocalStringManager.GetConfig("SecretInformationSpecialCondition_language", "Name_112"), new short[5], ESecretInformationSpecialConditionCalculate.BeKyodaiSectMember, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, 3));
		_dataArray.Add(new SecretInformationSpecialConditionItem(113, LocalStringManager.GetConfig("SecretInformationSpecialCondition_language", "Name_113"), new short[5], ESecretInformationSpecialConditionCalculate.BeKyodaiSectMember, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, 4));
		_dataArray.Add(new SecretInformationSpecialConditionItem(114, LocalStringManager.GetConfig("SecretInformationSpecialCondition_language", "Name_114"), new short[5], ESecretInformationSpecialConditionCalculate.BeKyodaiSectMember, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, 5));
		_dataArray.Add(new SecretInformationSpecialConditionItem(115, LocalStringManager.GetConfig("SecretInformationSpecialCondition_language", "Name_115"), new short[5], ESecretInformationSpecialConditionCalculate.BeKyodaiSectMember, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, 6));
		_dataArray.Add(new SecretInformationSpecialConditionItem(116, LocalStringManager.GetConfig("SecretInformationSpecialCondition_language", "Name_116"), new short[5], ESecretInformationSpecialConditionCalculate.BeKyodaiSectMember, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, 7));
		_dataArray.Add(new SecretInformationSpecialConditionItem(117, LocalStringManager.GetConfig("SecretInformationSpecialCondition_language", "Name_117"), new short[5], ESecretInformationSpecialConditionCalculate.BeKyodaiSectMember, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, 8));
		_dataArray.Add(new SecretInformationSpecialConditionItem(118, LocalStringManager.GetConfig("SecretInformationSpecialCondition_language", "Name_118"), new short[5], ESecretInformationSpecialConditionCalculate.BeKyodaiSectMember, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, 9));
		_dataArray.Add(new SecretInformationSpecialConditionItem(119, LocalStringManager.GetConfig("SecretInformationSpecialCondition_language", "Name_119"), new short[5], ESecretInformationSpecialConditionCalculate.BeKyodaiSectMember, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, 10));
	}

	private void CreateItems2()
	{
		_dataArray.Add(new SecretInformationSpecialConditionItem(120, LocalStringManager.GetConfig("SecretInformationSpecialCondition_language", "Name_120"), new short[5], ESecretInformationSpecialConditionCalculate.BeKyodaiSectMember, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, 11));
		_dataArray.Add(new SecretInformationSpecialConditionItem(121, LocalStringManager.GetConfig("SecretInformationSpecialCondition_language", "Name_121"), new short[5], ESecretInformationSpecialConditionCalculate.BeKyodaiSectMember, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, 12));
		_dataArray.Add(new SecretInformationSpecialConditionItem(122, LocalStringManager.GetConfig("SecretInformationSpecialCondition_language", "Name_122"), new short[5], ESecretInformationSpecialConditionCalculate.BeKyodaiSectMember, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, 13));
		_dataArray.Add(new SecretInformationSpecialConditionItem(123, LocalStringManager.GetConfig("SecretInformationSpecialCondition_language", "Name_123"), new short[5], ESecretInformationSpecialConditionCalculate.BeKyodaiSectMember, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, 14));
		_dataArray.Add(new SecretInformationSpecialConditionItem(124, LocalStringManager.GetConfig("SecretInformationSpecialCondition_language", "Name_124"), new short[5], ESecretInformationSpecialConditionCalculate.BeKyodaiSectMember, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, 15));
		_dataArray.Add(new SecretInformationSpecialConditionItem(125, LocalStringManager.GetConfig("SecretInformationSpecialCondition_language", "Name_125"), new short[5], ESecretInformationSpecialConditionCalculate.GainParentSectMember, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, 1));
		_dataArray.Add(new SecretInformationSpecialConditionItem(126, LocalStringManager.GetConfig("SecretInformationSpecialCondition_language", "Name_126"), new short[5], ESecretInformationSpecialConditionCalculate.GainParentSectMember, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, 2));
		_dataArray.Add(new SecretInformationSpecialConditionItem(127, LocalStringManager.GetConfig("SecretInformationSpecialCondition_language", "Name_127"), new short[5], ESecretInformationSpecialConditionCalculate.GainParentSectMember, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, 3));
		_dataArray.Add(new SecretInformationSpecialConditionItem(128, LocalStringManager.GetConfig("SecretInformationSpecialCondition_language", "Name_128"), new short[5], ESecretInformationSpecialConditionCalculate.GainParentSectMember, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, 4));
		_dataArray.Add(new SecretInformationSpecialConditionItem(129, LocalStringManager.GetConfig("SecretInformationSpecialCondition_language", "Name_129"), new short[5], ESecretInformationSpecialConditionCalculate.GainParentSectMember, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, 5));
		_dataArray.Add(new SecretInformationSpecialConditionItem(130, LocalStringManager.GetConfig("SecretInformationSpecialCondition_language", "Name_130"), new short[5], ESecretInformationSpecialConditionCalculate.GainParentSectMember, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, 6));
		_dataArray.Add(new SecretInformationSpecialConditionItem(131, LocalStringManager.GetConfig("SecretInformationSpecialCondition_language", "Name_131"), new short[5], ESecretInformationSpecialConditionCalculate.GainParentSectMember, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, 7));
		_dataArray.Add(new SecretInformationSpecialConditionItem(132, LocalStringManager.GetConfig("SecretInformationSpecialCondition_language", "Name_132"), new short[5], ESecretInformationSpecialConditionCalculate.GainParentSectMember, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, 8));
		_dataArray.Add(new SecretInformationSpecialConditionItem(133, LocalStringManager.GetConfig("SecretInformationSpecialCondition_language", "Name_133"), new short[5], ESecretInformationSpecialConditionCalculate.GainParentSectMember, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, 9));
		_dataArray.Add(new SecretInformationSpecialConditionItem(134, LocalStringManager.GetConfig("SecretInformationSpecialCondition_language", "Name_134"), new short[5], ESecretInformationSpecialConditionCalculate.GainParentSectMember, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, 10));
		_dataArray.Add(new SecretInformationSpecialConditionItem(135, LocalStringManager.GetConfig("SecretInformationSpecialCondition_language", "Name_135"), new short[5], ESecretInformationSpecialConditionCalculate.GainParentSectMember, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, 11));
		_dataArray.Add(new SecretInformationSpecialConditionItem(136, LocalStringManager.GetConfig("SecretInformationSpecialCondition_language", "Name_136"), new short[5], ESecretInformationSpecialConditionCalculate.GainParentSectMember, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, 12));
		_dataArray.Add(new SecretInformationSpecialConditionItem(137, LocalStringManager.GetConfig("SecretInformationSpecialCondition_language", "Name_137"), new short[5], ESecretInformationSpecialConditionCalculate.GainParentSectMember, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, 13));
		_dataArray.Add(new SecretInformationSpecialConditionItem(138, LocalStringManager.GetConfig("SecretInformationSpecialCondition_language", "Name_138"), new short[5], ESecretInformationSpecialConditionCalculate.GainParentSectMember, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, 14));
		_dataArray.Add(new SecretInformationSpecialConditionItem(139, LocalStringManager.GetConfig("SecretInformationSpecialCondition_language", "Name_139"), new short[5], ESecretInformationSpecialConditionCalculate.GainParentSectMember, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, 15));
		_dataArray.Add(new SecretInformationSpecialConditionItem(140, LocalStringManager.GetConfig("SecretInformationSpecialCondition_language", "Name_140"), new short[5], ESecretInformationSpecialConditionCalculate.GainChildSectMember, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, 1));
		_dataArray.Add(new SecretInformationSpecialConditionItem(141, LocalStringManager.GetConfig("SecretInformationSpecialCondition_language", "Name_141"), new short[5], ESecretInformationSpecialConditionCalculate.GainChildSectMember, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, 2));
		_dataArray.Add(new SecretInformationSpecialConditionItem(142, LocalStringManager.GetConfig("SecretInformationSpecialCondition_language", "Name_142"), new short[5], ESecretInformationSpecialConditionCalculate.GainChildSectMember, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, 3));
		_dataArray.Add(new SecretInformationSpecialConditionItem(143, LocalStringManager.GetConfig("SecretInformationSpecialCondition_language", "Name_143"), new short[5], ESecretInformationSpecialConditionCalculate.GainChildSectMember, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, 4));
		_dataArray.Add(new SecretInformationSpecialConditionItem(144, LocalStringManager.GetConfig("SecretInformationSpecialCondition_language", "Name_144"), new short[5], ESecretInformationSpecialConditionCalculate.GainChildSectMember, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, 5));
		_dataArray.Add(new SecretInformationSpecialConditionItem(145, LocalStringManager.GetConfig("SecretInformationSpecialCondition_language", "Name_145"), new short[5], ESecretInformationSpecialConditionCalculate.GainChildSectMember, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, 6));
		_dataArray.Add(new SecretInformationSpecialConditionItem(146, LocalStringManager.GetConfig("SecretInformationSpecialCondition_language", "Name_146"), new short[5], ESecretInformationSpecialConditionCalculate.GainChildSectMember, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, 7));
		_dataArray.Add(new SecretInformationSpecialConditionItem(147, LocalStringManager.GetConfig("SecretInformationSpecialCondition_language", "Name_147"), new short[5], ESecretInformationSpecialConditionCalculate.GainChildSectMember, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, 8));
		_dataArray.Add(new SecretInformationSpecialConditionItem(148, LocalStringManager.GetConfig("SecretInformationSpecialCondition_language", "Name_148"), new short[5], ESecretInformationSpecialConditionCalculate.GainChildSectMember, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, 9));
		_dataArray.Add(new SecretInformationSpecialConditionItem(149, LocalStringManager.GetConfig("SecretInformationSpecialCondition_language", "Name_149"), new short[5], ESecretInformationSpecialConditionCalculate.GainChildSectMember, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, 10));
		_dataArray.Add(new SecretInformationSpecialConditionItem(150, LocalStringManager.GetConfig("SecretInformationSpecialCondition_language", "Name_150"), new short[5], ESecretInformationSpecialConditionCalculate.GainChildSectMember, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, 11));
		_dataArray.Add(new SecretInformationSpecialConditionItem(151, LocalStringManager.GetConfig("SecretInformationSpecialCondition_language", "Name_151"), new short[5], ESecretInformationSpecialConditionCalculate.GainChildSectMember, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, 12));
		_dataArray.Add(new SecretInformationSpecialConditionItem(152, LocalStringManager.GetConfig("SecretInformationSpecialCondition_language", "Name_152"), new short[5], ESecretInformationSpecialConditionCalculate.GainChildSectMember, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, 13));
		_dataArray.Add(new SecretInformationSpecialConditionItem(153, LocalStringManager.GetConfig("SecretInformationSpecialCondition_language", "Name_153"), new short[5], ESecretInformationSpecialConditionCalculate.GainChildSectMember, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, 14));
		_dataArray.Add(new SecretInformationSpecialConditionItem(154, LocalStringManager.GetConfig("SecretInformationSpecialCondition_language", "Name_154"), new short[5], ESecretInformationSpecialConditionCalculate.GainChildSectMember, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, 15));
		_dataArray.Add(new SecretInformationSpecialConditionItem(155, LocalStringManager.GetConfig("SecretInformationSpecialCondition_language", "Name_155"), new short[5], ESecretInformationSpecialConditionCalculate.DateSectMember, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, 1));
		_dataArray.Add(new SecretInformationSpecialConditionItem(156, LocalStringManager.GetConfig("SecretInformationSpecialCondition_language", "Name_156"), new short[5], ESecretInformationSpecialConditionCalculate.DateSectMember, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, 2));
		_dataArray.Add(new SecretInformationSpecialConditionItem(157, LocalStringManager.GetConfig("SecretInformationSpecialCondition_language", "Name_157"), new short[5], ESecretInformationSpecialConditionCalculate.DateSectMember, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, 3));
		_dataArray.Add(new SecretInformationSpecialConditionItem(158, LocalStringManager.GetConfig("SecretInformationSpecialCondition_language", "Name_158"), new short[5], ESecretInformationSpecialConditionCalculate.DateSectMember, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, 4));
		_dataArray.Add(new SecretInformationSpecialConditionItem(159, LocalStringManager.GetConfig("SecretInformationSpecialCondition_language", "Name_159"), new short[5], ESecretInformationSpecialConditionCalculate.DateSectMember, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, 5));
		_dataArray.Add(new SecretInformationSpecialConditionItem(160, LocalStringManager.GetConfig("SecretInformationSpecialCondition_language", "Name_160"), new short[5], ESecretInformationSpecialConditionCalculate.DateSectMember, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, 6));
		_dataArray.Add(new SecretInformationSpecialConditionItem(161, LocalStringManager.GetConfig("SecretInformationSpecialCondition_language", "Name_161"), new short[5], ESecretInformationSpecialConditionCalculate.DateSectMember, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, 7));
		_dataArray.Add(new SecretInformationSpecialConditionItem(162, LocalStringManager.GetConfig("SecretInformationSpecialCondition_language", "Name_162"), new short[5], ESecretInformationSpecialConditionCalculate.DateSectMember, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, 8));
		_dataArray.Add(new SecretInformationSpecialConditionItem(163, LocalStringManager.GetConfig("SecretInformationSpecialCondition_language", "Name_163"), new short[5], ESecretInformationSpecialConditionCalculate.DateSectMember, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, 9));
		_dataArray.Add(new SecretInformationSpecialConditionItem(164, LocalStringManager.GetConfig("SecretInformationSpecialCondition_language", "Name_164"), new short[5], ESecretInformationSpecialConditionCalculate.DateSectMember, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, 10));
		_dataArray.Add(new SecretInformationSpecialConditionItem(165, LocalStringManager.GetConfig("SecretInformationSpecialCondition_language", "Name_165"), new short[5], ESecretInformationSpecialConditionCalculate.DateSectMember, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, 11));
		_dataArray.Add(new SecretInformationSpecialConditionItem(166, LocalStringManager.GetConfig("SecretInformationSpecialCondition_language", "Name_166"), new short[5], ESecretInformationSpecialConditionCalculate.DateSectMember, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, 12));
		_dataArray.Add(new SecretInformationSpecialConditionItem(167, LocalStringManager.GetConfig("SecretInformationSpecialCondition_language", "Name_167"), new short[5], ESecretInformationSpecialConditionCalculate.DateSectMember, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, 13));
		_dataArray.Add(new SecretInformationSpecialConditionItem(168, LocalStringManager.GetConfig("SecretInformationSpecialCondition_language", "Name_168"), new short[5], ESecretInformationSpecialConditionCalculate.DateSectMember, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, 14));
		_dataArray.Add(new SecretInformationSpecialConditionItem(169, LocalStringManager.GetConfig("SecretInformationSpecialCondition_language", "Name_169"), new short[5], ESecretInformationSpecialConditionCalculate.DateSectMember, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, 15));
		_dataArray.Add(new SecretInformationSpecialConditionItem(170, LocalStringManager.GetConfig("SecretInformationSpecialCondition_language", "Name_170"), new short[5], ESecretInformationSpecialConditionCalculate.ReFoundChildSectMember, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, 1));
		_dataArray.Add(new SecretInformationSpecialConditionItem(171, LocalStringManager.GetConfig("SecretInformationSpecialCondition_language", "Name_171"), new short[5], ESecretInformationSpecialConditionCalculate.ReFoundChildSectMember, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, 2));
		_dataArray.Add(new SecretInformationSpecialConditionItem(172, LocalStringManager.GetConfig("SecretInformationSpecialCondition_language", "Name_172"), new short[5], ESecretInformationSpecialConditionCalculate.ReFoundChildSectMember, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, 3));
		_dataArray.Add(new SecretInformationSpecialConditionItem(173, LocalStringManager.GetConfig("SecretInformationSpecialCondition_language", "Name_173"), new short[5], ESecretInformationSpecialConditionCalculate.ReFoundChildSectMember, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, 4));
		_dataArray.Add(new SecretInformationSpecialConditionItem(174, LocalStringManager.GetConfig("SecretInformationSpecialCondition_language", "Name_174"), new short[5], ESecretInformationSpecialConditionCalculate.ReFoundChildSectMember, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, 5));
		_dataArray.Add(new SecretInformationSpecialConditionItem(175, LocalStringManager.GetConfig("SecretInformationSpecialCondition_language", "Name_175"), new short[5], ESecretInformationSpecialConditionCalculate.ReFoundChildSectMember, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, 6));
		_dataArray.Add(new SecretInformationSpecialConditionItem(176, LocalStringManager.GetConfig("SecretInformationSpecialCondition_language", "Name_176"), new short[5], ESecretInformationSpecialConditionCalculate.ReFoundChildSectMember, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, 7));
		_dataArray.Add(new SecretInformationSpecialConditionItem(177, LocalStringManager.GetConfig("SecretInformationSpecialCondition_language", "Name_177"), new short[5], ESecretInformationSpecialConditionCalculate.ReFoundChildSectMember, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, 8));
		_dataArray.Add(new SecretInformationSpecialConditionItem(178, LocalStringManager.GetConfig("SecretInformationSpecialCondition_language", "Name_178"), new short[5], ESecretInformationSpecialConditionCalculate.ReFoundChildSectMember, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, 9));
		_dataArray.Add(new SecretInformationSpecialConditionItem(179, LocalStringManager.GetConfig("SecretInformationSpecialCondition_language", "Name_179"), new short[5], ESecretInformationSpecialConditionCalculate.ReFoundChildSectMember, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, 10));
	}

	private void CreateItems3()
	{
		_dataArray.Add(new SecretInformationSpecialConditionItem(180, LocalStringManager.GetConfig("SecretInformationSpecialCondition_language", "Name_180"), new short[5], ESecretInformationSpecialConditionCalculate.ReFoundChildSectMember, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, 11));
		_dataArray.Add(new SecretInformationSpecialConditionItem(181, LocalStringManager.GetConfig("SecretInformationSpecialCondition_language", "Name_181"), new short[5], ESecretInformationSpecialConditionCalculate.ReFoundChildSectMember, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, 12));
		_dataArray.Add(new SecretInformationSpecialConditionItem(182, LocalStringManager.GetConfig("SecretInformationSpecialCondition_language", "Name_182"), new short[5], ESecretInformationSpecialConditionCalculate.ReFoundChildSectMember, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, 13));
		_dataArray.Add(new SecretInformationSpecialConditionItem(183, LocalStringManager.GetConfig("SecretInformationSpecialCondition_language", "Name_183"), new short[5], ESecretInformationSpecialConditionCalculate.ReFoundChildSectMember, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, 14));
		_dataArray.Add(new SecretInformationSpecialConditionItem(184, LocalStringManager.GetConfig("SecretInformationSpecialCondition_language", "Name_184"), new short[5], ESecretInformationSpecialConditionCalculate.ReFoundChildSectMember, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, -1, 15));
		_dataArray.Add(new SecretInformationSpecialConditionItem(185, LocalStringManager.GetConfig("SecretInformationSpecialCondition_language", "Name_185"), new short[5], ESecretInformationSpecialConditionCalculate.BanEating, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, 162, -1));
		_dataArray.Add(new SecretInformationSpecialConditionItem(186, LocalStringManager.GetConfig("SecretInformationSpecialCondition_language", "Name_186"), new short[5], ESecretInformationSpecialConditionCalculate.BanEating, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, 163, -1));
		_dataArray.Add(new SecretInformationSpecialConditionItem(187, LocalStringManager.GetConfig("SecretInformationSpecialCondition_language", "Name_187"), new short[5], ESecretInformationSpecialConditionCalculate.BanEating, ESecretInformationSpecialConditionCalcFameLine.Invalid, ESecretInformationSpecialConditionCalcSexualMateCase.Invalid, ESecretInformationSpecialConditionCalcSexualMateRule.Invalid, 164, -1));
	}

	public override void Init()
	{
		base.Init();
		_dataArray = new List<SecretInformationSpecialConditionItem>(188);
		CreateItems0();
		CreateItems1();
		CreateItems2();
		CreateItems3();
	}
}
