using System;
using System.Collections.Generic;
using Config.Common;

namespace Config;

[Serializable]
public class SolarTerm : ConfigData<SolarTermItem, sbyte>
{
	public static SolarTerm Instance = new SolarTerm();

	private readonly HashSet<string> RequiredFields = new HashSet<string>
	{
		"Name", "Desc", "Poem", "Month", "MaterialIdsOfFoodBuff", "PoisonBuffType", "DetoxBuffType", "Goods", "GoodsDialog", "GoodsStateList",
		"TemplateId", "Type", "Image", "Sound", "FiveElementsTypesOfCombatSkillBuff"
	};

	internal override int ToInt(sbyte value)
	{
		return value;
	}

	internal override sbyte ToTemplateId(int value)
	{
		return (sbyte)value;
	}

	private void CreateItems0()
	{
		_dataArray.Add(new SolarTermItem(0, LocalStringManager.GetConfig("SolarTerm_language", "Name_0"), 0, LocalStringManager.GetConfig("SolarTerm_language", "Desc_0"), LocalStringManager.GetConfig("SolarTerm_language", "Poem_0"), "TurnChange_3", "se_solarterm_0", 1, new List<byte> { 1, 4 }, new List<short> { 70, 71, 72, 73, 74, 75, 76 }, 5, 4, outerHealingBuff: false, innerHealingBuff: false, qiDisorderRecoveringBuff: true, healthBuff: false, 444, LocalStringManager.GetConfig("SolarTerm_language", "GoodsDialog_0"), new List<sbyte> { 14, 12, 3 }));
		_dataArray.Add(new SolarTermItem(1, LocalStringManager.GetConfig("SolarTerm_language", "Name_1"), 1, LocalStringManager.GetConfig("SolarTerm_language", "Desc_1"), LocalStringManager.GetConfig("SolarTerm_language", "Poem_1"), "TurnChange_4", "se_solarterm_1", 1, new List<byte> { 1 }, new List<short> { 70, 71, 72, 73, 74, 75, 76 }, 5, 4, outerHealingBuff: false, innerHealingBuff: false, qiDisorderRecoveringBuff: true, healthBuff: false, 445, LocalStringManager.GetConfig("SolarTerm_language", "GoodsDialog_1"), new List<sbyte> { 8, 9, 15 }));
		_dataArray.Add(new SolarTermItem(2, LocalStringManager.GetConfig("SolarTerm_language", "Name_2"), 0, LocalStringManager.GetConfig("SolarTerm_language", "Desc_2"), LocalStringManager.GetConfig("SolarTerm_language", "Poem_2"), "TurnChange_5", "se_solarterm_2", 2, new List<byte> { 1 }, new List<short> { 70, 71, 72, 73, 74, 75, 76 }, 1, 0, outerHealingBuff: false, innerHealingBuff: false, qiDisorderRecoveringBuff: true, healthBuff: false, 446, LocalStringManager.GetConfig("SolarTerm_language", "GoodsDialog_2"), new List<sbyte> { 3, 9, 6 }));
		_dataArray.Add(new SolarTermItem(3, LocalStringManager.GetConfig("SolarTerm_language", "Name_3"), 1, LocalStringManager.GetConfig("SolarTerm_language", "Desc_3"), LocalStringManager.GetConfig("SolarTerm_language", "Poem_3"), "TurnChange_6", "se_solarterm_3", 2, new List<byte> { 1, 4 }, new List<short> { 70, 71, 72, 73, 74, 75, 76 }, 1, 0, outerHealingBuff: false, innerHealingBuff: false, qiDisorderRecoveringBuff: true, healthBuff: false, 447, LocalStringManager.GetConfig("SolarTerm_language", "GoodsDialog_3"), new List<sbyte> { 7, 14, 12 }));
		_dataArray.Add(new SolarTermItem(4, LocalStringManager.GetConfig("SolarTerm_language", "Name_4"), 0, LocalStringManager.GetConfig("SolarTerm_language", "Desc_4"), LocalStringManager.GetConfig("SolarTerm_language", "Poem_4"), "TurnChange_7", "se_solarterm_4", 3, new List<byte> { 1 }, new List<short> { 70, 71, 72, 73, 74, 75, 76 }, 1, 0, outerHealingBuff: false, innerHealingBuff: false, qiDisorderRecoveringBuff: true, healthBuff: false, 448, LocalStringManager.GetConfig("SolarTerm_language", "GoodsDialog_4"), new List<sbyte> { 13, 8, 2 }));
		_dataArray.Add(new SolarTermItem(5, LocalStringManager.GetConfig("SolarTerm_language", "Name_5"), 1, LocalStringManager.GetConfig("SolarTerm_language", "Desc_5"), LocalStringManager.GetConfig("SolarTerm_language", "Poem_5"), "TurnChange_8", "se_solarterm_5", 3, new List<byte> { 1 }, new List<short> { 70, 71, 72, 73, 74, 75, 76 }, 1, 0, outerHealingBuff: false, innerHealingBuff: false, qiDisorderRecoveringBuff: true, healthBuff: false, 449, LocalStringManager.GetConfig("SolarTerm_language", "GoodsDialog_5"), new List<sbyte> { 9, 2, 12 }));
		_dataArray.Add(new SolarTermItem(6, LocalStringManager.GetConfig("SolarTerm_language", "Name_6"), 0, LocalStringManager.GetConfig("SolarTerm_language", "Desc_6"), LocalStringManager.GetConfig("SolarTerm_language", "Poem_6"), "TurnChange_9", "se_solarterm_6", 4, new List<byte> { 3, 4 }, new List<short> { 56, 57, 58, 59, 60, 61, 62 }, 0, 1, outerHealingBuff: false, innerHealingBuff: true, qiDisorderRecoveringBuff: false, healthBuff: false, 450, LocalStringManager.GetConfig("SolarTerm_language", "GoodsDialog_6"), new List<sbyte> { 15, 8, 3 }));
		_dataArray.Add(new SolarTermItem(7, LocalStringManager.GetConfig("SolarTerm_language", "Name_7"), 1, LocalStringManager.GetConfig("SolarTerm_language", "Desc_7"), LocalStringManager.GetConfig("SolarTerm_language", "Poem_7"), "TurnChange_10", "se_solarterm_7", 4, new List<byte> { 3 }, new List<short> { 56, 57, 58, 59, 60, 61, 62 }, 0, 1, outerHealingBuff: false, innerHealingBuff: true, qiDisorderRecoveringBuff: false, healthBuff: false, 451, LocalStringManager.GetConfig("SolarTerm_language", "GoodsDialog_7"), new List<sbyte> { 14, 2, 8 }));
		_dataArray.Add(new SolarTermItem(8, LocalStringManager.GetConfig("SolarTerm_language", "Name_8"), 0, LocalStringManager.GetConfig("SolarTerm_language", "Desc_8"), LocalStringManager.GetConfig("SolarTerm_language", "Poem_8"), "TurnChange_11", "se_solarterm_8", 5, new List<byte> { 3 }, new List<short> { 56, 57, 58, 59, 60, 61, 62 }, 0, 1, outerHealingBuff: false, innerHealingBuff: true, qiDisorderRecoveringBuff: false, healthBuff: false, 452, LocalStringManager.GetConfig("SolarTerm_language", "GoodsDialog_8"), new List<sbyte> { 5, 7, 4 }));
		_dataArray.Add(new SolarTermItem(9, LocalStringManager.GetConfig("SolarTerm_language", "Name_9"), 1, LocalStringManager.GetConfig("SolarTerm_language", "Desc_9"), LocalStringManager.GetConfig("SolarTerm_language", "Poem_9"), "TurnChange_12", "se_solarterm_9", 5, new List<byte> { 3, 4 }, new List<short> { 56, 57, 58, 59, 60, 61, 62 }, 0, 1, outerHealingBuff: false, innerHealingBuff: true, qiDisorderRecoveringBuff: false, healthBuff: false, 453, LocalStringManager.GetConfig("SolarTerm_language", "GoodsDialog_9"), new List<sbyte> { 14, 3, 10 }));
		_dataArray.Add(new SolarTermItem(10, LocalStringManager.GetConfig("SolarTerm_language", "Name_10"), 0, LocalStringManager.GetConfig("SolarTerm_language", "Desc_10"), LocalStringManager.GetConfig("SolarTerm_language", "Poem_10"), "TurnChange_13", "se_solarterm_10", 6, new List<byte> { 3 }, new List<short> { 56, 57, 58, 59, 60, 61, 62 }, 3, 2, outerHealingBuff: false, innerHealingBuff: true, qiDisorderRecoveringBuff: false, healthBuff: false, 454, LocalStringManager.GetConfig("SolarTerm_language", "GoodsDialog_10"), new List<sbyte> { 1, 5, 7 }));
		_dataArray.Add(new SolarTermItem(11, LocalStringManager.GetConfig("SolarTerm_language", "Name_11"), 1, LocalStringManager.GetConfig("SolarTerm_language", "Desc_11"), LocalStringManager.GetConfig("SolarTerm_language", "Poem_11"), "TurnChange_14", "se_solarterm_11", 6, new List<byte> { 3 }, new List<short> { 56, 57, 58, 59, 60, 61, 62 }, 3, 2, outerHealingBuff: false, innerHealingBuff: true, qiDisorderRecoveringBuff: false, healthBuff: false, 455, LocalStringManager.GetConfig("SolarTerm_language", "GoodsDialog_11"), new List<sbyte> { 12, 2, 11 }));
		_dataArray.Add(new SolarTermItem(12, LocalStringManager.GetConfig("SolarTerm_language", "Name_12"), 0, LocalStringManager.GetConfig("SolarTerm_language", "Desc_12"), LocalStringManager.GetConfig("SolarTerm_language", "Poem_12"), "TurnChange_15", "se_solarterm_12", 7, new List<byte> { 0, 4 }, new List<short> { 77, 78, 79, 80, 81, 82, 83 }, 3, 2, outerHealingBuff: true, innerHealingBuff: false, qiDisorderRecoveringBuff: false, healthBuff: false, 456, LocalStringManager.GetConfig("SolarTerm_language", "GoodsDialog_12"), new List<sbyte> { 7, 5, 4 }));
		_dataArray.Add(new SolarTermItem(13, LocalStringManager.GetConfig("SolarTerm_language", "Name_13"), 1, LocalStringManager.GetConfig("SolarTerm_language", "Desc_13"), LocalStringManager.GetConfig("SolarTerm_language", "Poem_13"), "TurnChange_16", "se_solarterm_13", 7, new List<byte> { 0 }, new List<short> { 77, 78, 79, 80, 81, 82, 83 }, 3, 2, outerHealingBuff: true, innerHealingBuff: false, qiDisorderRecoveringBuff: false, healthBuff: false, 457, LocalStringManager.GetConfig("SolarTerm_language", "GoodsDialog_13"), new List<sbyte> { 14, 3, 11 }));
		_dataArray.Add(new SolarTermItem(14, LocalStringManager.GetConfig("SolarTerm_language", "Name_14"), 0, LocalStringManager.GetConfig("SolarTerm_language", "Desc_14"), LocalStringManager.GetConfig("SolarTerm_language", "Poem_14"), "TurnChange_17", "se_solarterm_14", 8, new List<byte> { 0 }, new List<short> { 77, 78, 79, 80, 81, 82, 83 }, 4, 5, outerHealingBuff: true, innerHealingBuff: false, qiDisorderRecoveringBuff: false, healthBuff: false, 458, LocalStringManager.GetConfig("SolarTerm_language", "GoodsDialog_14"), new List<sbyte> { 12, 2, 10 }));
		_dataArray.Add(new SolarTermItem(15, LocalStringManager.GetConfig("SolarTerm_language", "Name_15"), 1, LocalStringManager.GetConfig("SolarTerm_language", "Desc_15"), LocalStringManager.GetConfig("SolarTerm_language", "Poem_15"), "TurnChange_18", "se_solarterm_15", 8, new List<byte> { 0, 4 }, new List<short> { 77, 78, 79, 80, 81, 82, 83 }, 4, 5, outerHealingBuff: true, innerHealingBuff: false, qiDisorderRecoveringBuff: false, healthBuff: false, 459, LocalStringManager.GetConfig("SolarTerm_language", "GoodsDialog_15"), new List<sbyte> { 11, 12, 5 }));
		_dataArray.Add(new SolarTermItem(16, LocalStringManager.GetConfig("SolarTerm_language", "Name_16"), 0, LocalStringManager.GetConfig("SolarTerm_language", "Desc_16"), LocalStringManager.GetConfig("SolarTerm_language", "Poem_16"), "TurnChange_19", "se_solarterm_16", 9, new List<byte> { 0 }, new List<short> { 77, 78, 79, 80, 81, 82, 83 }, 4, 5, outerHealingBuff: true, innerHealingBuff: false, qiDisorderRecoveringBuff: false, healthBuff: false, 460, LocalStringManager.GetConfig("SolarTerm_language", "GoodsDialog_16"), new List<sbyte> { 1, 7, 6 }));
		_dataArray.Add(new SolarTermItem(17, LocalStringManager.GetConfig("SolarTerm_language", "Name_17"), 1, LocalStringManager.GetConfig("SolarTerm_language", "Desc_17"), LocalStringManager.GetConfig("SolarTerm_language", "Poem_17"), "TurnChange_20", "se_solarterm_17", 9, new List<byte> { 0 }, new List<short> { 77, 78, 79, 80, 81, 82, 83 }, 4, 5, outerHealingBuff: true, innerHealingBuff: false, qiDisorderRecoveringBuff: false, healthBuff: false, 461, LocalStringManager.GetConfig("SolarTerm_language", "GoodsDialog_17"), new List<sbyte> { 5, 13, 7 }));
		_dataArray.Add(new SolarTermItem(18, LocalStringManager.GetConfig("SolarTerm_language", "Name_18"), 0, LocalStringManager.GetConfig("SolarTerm_language", "Desc_18"), LocalStringManager.GetConfig("SolarTerm_language", "Poem_18"), "TurnChange_21", "se_solarterm_18", 10, new List<byte> { 2, 4 }, new List<short> { 63, 64, 65, 66, 67, 68, 69 }, 2, 3, outerHealingBuff: false, innerHealingBuff: false, qiDisorderRecoveringBuff: false, healthBuff: true, 462, LocalStringManager.GetConfig("SolarTerm_language", "GoodsDialog_18"), new List<sbyte> { 1, 5, 10 }));
		_dataArray.Add(new SolarTermItem(19, LocalStringManager.GetConfig("SolarTerm_language", "Name_19"), 1, LocalStringManager.GetConfig("SolarTerm_language", "Desc_19"), LocalStringManager.GetConfig("SolarTerm_language", "Poem_19"), "TurnChange_22", "se_solarterm_19", 10, new List<byte> { 2 }, new List<short> { 63, 64, 65, 66, 67, 68, 69 }, 2, 3, outerHealingBuff: false, innerHealingBuff: false, qiDisorderRecoveringBuff: false, healthBuff: true, 463, LocalStringManager.GetConfig("SolarTerm_language", "GoodsDialog_19"), new List<sbyte> { 10, 5, 4 }));
		_dataArray.Add(new SolarTermItem(20, LocalStringManager.GetConfig("SolarTerm_language", "Name_20"), 0, LocalStringManager.GetConfig("SolarTerm_language", "Desc_20"), LocalStringManager.GetConfig("SolarTerm_language", "Poem_20"), "TurnChange_23", "se_solarterm_20", 11, new List<byte> { 2 }, new List<short> { 63, 64, 65, 66, 67, 68, 69 }, 2, 3, outerHealingBuff: false, innerHealingBuff: false, qiDisorderRecoveringBuff: false, healthBuff: true, 464, LocalStringManager.GetConfig("SolarTerm_language", "GoodsDialog_20"), new List<sbyte> { 11, 10, 5 }));
		_dataArray.Add(new SolarTermItem(21, LocalStringManager.GetConfig("SolarTerm_language", "Name_21"), 1, LocalStringManager.GetConfig("SolarTerm_language", "Desc_21"), LocalStringManager.GetConfig("SolarTerm_language", "Poem_21"), "TurnChange_24", "se_solarterm_21", 11, new List<byte> { 2, 4 }, new List<short> { 63, 64, 65, 66, 67, 68, 69 }, 2, 3, outerHealingBuff: false, innerHealingBuff: false, qiDisorderRecoveringBuff: false, healthBuff: true, 465, LocalStringManager.GetConfig("SolarTerm_language", "GoodsDialog_21"), new List<sbyte> { 9, 6, 3 }));
		_dataArray.Add(new SolarTermItem(22, LocalStringManager.GetConfig("SolarTerm_language", "Name_22"), 0, LocalStringManager.GetConfig("SolarTerm_language", "Desc_22"), LocalStringManager.GetConfig("SolarTerm_language", "Poem_22"), "TurnChange_1", "se_solarterm_22", 0, new List<byte> { 2 }, new List<short> { 63, 64, 65, 66, 67, 68, 69 }, 5, 4, outerHealingBuff: false, innerHealingBuff: false, qiDisorderRecoveringBuff: false, healthBuff: true, 466, LocalStringManager.GetConfig("SolarTerm_language", "GoodsDialog_22"), new List<sbyte> { 14, 12, 9 }));
		_dataArray.Add(new SolarTermItem(23, LocalStringManager.GetConfig("SolarTerm_language", "Name_23"), 1, LocalStringManager.GetConfig("SolarTerm_language", "Desc_23"), LocalStringManager.GetConfig("SolarTerm_language", "Poem_23"), "TurnChange_2", "se_solarterm_23", 0, new List<byte> { 2 }, new List<short> { 63, 64, 65, 66, 67, 68, 69 }, 5, 4, outerHealingBuff: false, innerHealingBuff: false, qiDisorderRecoveringBuff: false, healthBuff: true, 467, LocalStringManager.GetConfig("SolarTerm_language", "GoodsDialog_23"), new List<sbyte> { 4, 1, 6 }));
	}

	public override void Init()
	{
		base.Init();
		_dataArray = new List<SolarTermItem>(24);
		CreateItems0();
	}
}
