using System.Collections.Generic;
using GameData.Serializer;

namespace GameData.Domains.Adventure;

[SerializableGameData(NotForDisplayModule = true, IsExtensible = true)]
public class AdventureAutoGenerateData : ISerializableGameData
{
	private static class FieldIds
	{
		public const ushort CooldownFinishedDate = 0;

		public const ushort Count = 1;

		public static readonly string[] FieldId2FieldName = new string[1] { "CooldownFinishedDate" };
	}

	[SerializableGameDataField(FieldIndex = 0)]
	public Dictionary<int, int> CooldownFinishedDate = new Dictionary<int, int>();

	public AdventureAutoGenerateData()
	{
	}

	public AdventureAutoGenerateData(AdventureAutoGenerateData other)
	{
		CooldownFinishedDate = ((other.CooldownFinishedDate == null) ? null : new Dictionary<int, int>(other.CooldownFinishedDate));
	}

	public void Assign(AdventureAutoGenerateData other)
	{
		CooldownFinishedDate = ((other.CooldownFinishedDate == null) ? null : new Dictionary<int, int>(other.CooldownFinishedDate));
	}

	public bool IsSerializedSizeFixed()
	{
		return false;
	}

	public int GetSerializedSize()
	{
		int totalSize = 2;
		totalSize += SerializationHelper.DictionaryOfBasicTypePair.GetSerializedSize(CooldownFinishedDate);
		return (totalSize <= 4) ? totalSize : ((totalSize + 3) / 4 * 4);
	}

	public unsafe int Serialize(byte* pData)
	{
		byte* pCurrData = pData;
		*(short*)pCurrData = 1;
		pCurrData += 2;
		pCurrData += SerializationHelper.DictionaryOfBasicTypePair.Serialize(pCurrData, ref CooldownFinishedDate);
		int totalSize = (int)(pCurrData - pData);
		return (totalSize <= 4) ? totalSize : ((totalSize + 3) / 4 * 4);
	}

	public unsafe int Deserialize(byte* pData)
	{
		byte* pCurrData = pData;
		ushort fieldCount = *(ushort*)pCurrData;
		pCurrData += 2;
		if (fieldCount > 0)
		{
			pCurrData += SerializationHelper.DictionaryOfBasicTypePair.Deserialize(pCurrData, ref CooldownFinishedDate);
		}
		int totalSize = (int)(pCurrData - pData);
		return (totalSize <= 4) ? totalSize : ((totalSize + 3) / 4 * 4);
	}
}
