return {
	BackendPlugins = {
		[1] = "TaiwuOptimization.dll",
	},
	FrontendPlugins = {
		[1] = "TaiwuOptimizationFront.dll",
	},
	Title = "[天幕心帷]过月性能优化",
	Version = "0.1.7.0",
	Author = "man!",
	Description = " [h1] 过月性能优化 [/h1]\n\n将部分远离太吾当前位置的低风险过月任务，延迟到过月后的帧中分批执行，减少点击过月时的集中卡顿。\n\n当前[i]（无论何时，包括快速旅行时）[/i]州域始终同步结算，可选同步结算相邻州域，避免太吾附近区域出现状态滞后。\n\n[h3][b]不会影响原版存档执行次序/执行屏障/二进制读写！可在已有存档中自由加入/取消本mod。[/b][/h3]\n\n[list] [h2]当前可用延迟[/h2]\n[*] 部分远区 NPC 普通月行动/准备行动\n[*] 破损地块恢复倒计时\n[*] 野生动物生态更新\n[*] 坟墓僵尸生成\n[*] 地图拾取物状态更新\n[/list]\n\n[h2]实验项[/h2]\n可选降低未受保护远区 NPC 的每月行动点增长。此项会让远区 NPC 行动推进变慢，不属于严格等价结算。\n\n[b] 使用 Harmony Patch，可能(大概率)与修改以上逻辑的mod冲突。[/b]\n\n[h2]兼容更新#260624[/h2]\n已修复退出至主界面时的红字报错，pending队列在退出世界前会清空，同时不再触发/延迟原版保存世界行为。\n在原版执行保存世界前将确保pending队列中的任务完全执行完毕以维护存档一致性。\n\n[spoiler]PS:根据我个人反编译出来的后端源码，螺舟把月结计算全部压在太吾点击下个月按钮后触发的AdvanceMonth函数里，这函数各个阶段虽然内部并行但是写回世界数据的时候是串行。瓶颈就在这里。以原版太吾绘卷这样的后端设计想要减少月结等待时间就只能把这个月的计算延迟到月结后。\n\n个人认为理想的情况应该是这个月开始的时候使用帧预算计算太吾不行动时下个月的世界快照，然后月结只根据太吾本月实际行动产生的diff更新原来的快照。\n\n而且一个按钮就得让橡树化身守电脑前硬等这对吗？\n[/spoiler] ",
	Source = 0,
	HasArchive = false,
	NeedRestartWhenSettingChanged = false,
	ChangeConfig = false,
	TagList = {
		[1] = "Compatible Mods",
		[2] = "Optimizations",
	},
	GameVersion = "1.0.24.0",
	DefaultSettings = {
		[1] = {
			SettingType = "Toggle",
			Key = "AdvanceMonthOptimizationEnabled",
			DisplayName = "启用过月优化",
			Description = "总开关。开启后，部分远离太吾保护区域的低风险过月任务会延迟到过月后的帧中分批执行，以减少点击过月时的集中卡顿。",
			GroupName = "通用配置",
			DefaultValue = true,
		},
		[2] = {
			SettingType = "Toggle",
			Key = "ProtectNeighborStatesForAdvanceMonthOptimization",
			DisplayName = "保护相邻州域",
			Description = "开启后，相邻州域也视为太吾保护区域：过月任务保持同步，实验性 NPC 行动点削减也不会影响这些区域。关闭后分摊更激进。",
			GroupName = "通用配置",
			DefaultValue = true,
		},
		[3] = {
			SettingType = "Slider",
			Key = "AdvanceMonthOptimizationFrameBudgetMs",
			DisplayName = "每帧处理预算(毫秒)",
			Description = "每帧用于处理缓存构建和延迟任务的时间预算。数值越高，pending 队列清空越快，但越可能影响帧率。",
			GroupName = "通用配置",
			MinValue = 1,
			MaxValue = 4,
			StepSize = 1,
			DefaultValue = 2,
		},
		[4] = {
			SettingType = "Slider",
			Key = "MaxPeriAdvanceMonthDeferredJobsPerFrame",
			DisplayName = "每帧最多任务数",
			Description = "每帧最多回放的延迟任务数。数值越低越平滑，数值越高越快消化 pending 队列；仍受帧时间预算限制。",
			GroupName = "通用配置",
			MinValue = 1,
			MaxValue = 16,
			StepSize = 1,
			DefaultValue = 4,
		},
		[5] = {
			SettingType = "Toggle",
			Key = "DeferPeriAdvanceMonthActivePreparationCombatSkillAndItemEquipping",
			DisplayName = "优化：延迟NPC装备/修理",
			Description = "将非保护区域 NPC 的装备选择、物品准备和修理等前置月结任务延迟到过月后分批执行。",
			GroupName = "帧时间延迟结算",
			DefaultValue = true,
		},
		[6] = {
			SettingType = "Toggle",
			Key = "DeferPeriAdvanceMonthLoseOverloadItems",
			DisplayName = "优化：延迟NPC超重丢弃",
			Description = "将非保护区域 NPC 的超重物品丢弃延迟到过月后分批执行。可能使远区物品整理稍后生效。",
			GroupName = "帧时间延迟结算",
			DefaultValue = true,
		},
		[7] = {
			SettingType = "Toggle",
			Key = "DeferParallelUpdateBrokenBlockOnMonthChange",
			DisplayName = "优化：延迟破损地块倒计时",
			Description = "将非保护区域破损地块的恢复倒计时更新延迟到过月后分批执行。",
			GroupName = "帧时间延迟结算",
			DefaultValue = true,
		},
		[8] = {
			SettingType = "Toggle",
			Key = "DeferUpdateAnimalAreaData",
			DisplayName = "优化：延迟野生动物生态",
			Description = "将非保护区域的野生动物自然死亡和生态生成延迟到过月后分批执行。",
			GroupName = "帧时间延迟结算",
			DefaultValue = true,
		},
		[9] = {
			SettingType = "Toggle",
			Key = "DeferGenerateSkeletons",
			DisplayName = "优化：延迟坟墓僵尸生成",
			Description = "将非保护区域废墟墓地的僵尸生成延迟到过月后分批执行。",
			GroupName = "帧时间延迟结算",
			DefaultValue = true,
		},
		[10] = {
			SettingType = "Toggle",
			Key = "DeferMapPickupsPostAdvanceMonth",
			DisplayName = "优化：延迟拾取物状态刷新",
			Description = "将非保护区域地图拾取物的可见性刷新和忽略/触发状态清理延迟到过月后分批执行。",
			GroupName = "帧时间延迟结算",
			DefaultValue = true,
		},
		[11] = {
			SettingType = "Toggle",
			Key = "ReduceRemoteNpcOfflineCurrentGoalActionPointGain",
			DisplayName = "实验：降低远区NPC月行动点增长",
			Description = "实验性选项。开启后，未受保护的远区 NPC 每月主/副目标行动点增长会被削减，使其行动推进更慢；不改变行动点上限。",
			GroupName = "实验性：NPC月行动点调整",
			DefaultValue = false,
		},
		[12] = {
			SettingType = "Slider",
			Key = "RemoteNpcOfflineCurrentGoalActionPointGainReduction",
			DisplayName = "远区NPC行动点增长削减",
			Description = "每月主/副目标行动点增长各自减少该数值。原版每月各增长 40，上限 60；默认削减 10。",
			GroupName = "实验性：NPC月行动点调整",
			MinValue = 0,
			MaxValue = 20,
			StepSize = 5,
			DefaultValue = 10,
		},
		[13] = {
			SettingType = "Toggle",
			Key = "ProtectTaiwuVillageResidentsFromOfflineActionPointReduction",
			DisplayName = "保护太吾村居民行动点",
			Description = "开启后，太吾村居民始终保留原版行动点增长，不受远区 NPC 行动点削减影响。",
			GroupName = "实验性：NPC月行动点调整",
			DefaultValue = true,
		},
		[14] = {
			SettingType = "Toggle",
			Key = "ProtectSectMembersFromOfflineActionPointReduction",
			DisplayName = "保护门派成员行动点",
			Description = "开启后，门派成员始终保留原版行动点增长。更保守，但会降低实验项收益。",
			GroupName = "实验性：NPC月行动点调整",
			DefaultValue = false,
		},
		[15] = {
			SettingType = "Toggle",
			Key = "AdvanceMonthOptimizationDiagnosticsEnabled",
			DisplayName = "启用运行时诊断日志",
			Description = "测试用选项，默认关闭。开启后按间隔向后端日志 Logs/GameData_*.log 写入一行聚合摘要，用于观察帧预算、pending 队列、超时和缓存构建情况。如果出现频繁卡顿，可检查日志中是否有频繁的帧预算超时。正常游玩建议关闭。",
			GroupName = "运行时诊断日志",
			DefaultValue = false,
		},
		[16] = {
			SettingType = "Slider",
			Key = "AdvanceMonthOptimizationDiagnosticsIntervalSeconds",
			DisplayName = "诊断日志间隔(秒)",
			Description = "运行时诊断日志的聚合输出间隔。间隔越短日志越密集，对性能和日志体积影响越大；测试时建议 5 秒或更高。",
			GroupName = "运行时诊断日志",
			MinValue = 1,
			MaxValue = 30,
			StepSize = 1,
			DefaultValue = 5,
		},
	},
	FileId = 3750430637,
	Visibility = 0,
	SettingGroups = {
		[1] = "通用配置",
		[2] = "帧时间延迟结算",
		[3] = "实验性：NPC月行动点调整",
		[4] = "运行时诊断日志",
	},
	UpdateLogList = {
		[1] = {
			Timestamp = 1782234802,
		},
		[2] = {
			Timestamp = 1782235028,
		},
		[3] = {
			Timestamp = 1782247859,
		},
		[4] = {
			Timestamp = 1782248233,
		},
		[5] = {
			Timestamp = 1782248252,
		},
		[6] = {
			Timestamp = 1782257461,
		},
		[7] = {
			Timestamp = 1782258542,
		},
		[8] = {
			Timestamp = 1782288454,
		},
		[9] = {
			Timestamp = 1782288500,
		},
		[10] = {
			Timestamp = 1782288782,
		},
	},
	Cover = "c04bb314ab8daa46832bb42193ddebfb.jpg",
	WorkshopCover = "c04bb314ab8daa46832bb42193ddebfb.jpg",
}
