return {
	BackendPlugins = {
		[1] = "TaiwuOptimization.dll",
	},
	FrontendPlugins = {
		[1] = "TaiwuOptimizationFront.dll",
	},
	Title = "[天幕心帷]过月优化",
	Version = "0.1.0.0",
	Author = "man!",
	Description = "通过将远离太吾的低风险过月计算任务延迟到过月后tick中分批执行，缩短过月伪死的时间。\n可中途添加，对原版存档无影响但是可能（大概率）与手动存档冲突",
	Source = 0,
	HasArchive = false,
	NeedRestartWhenSettingChanged = false,
	ChangeConfig = false,
	TagList = {
		[1] = "Compatible Mods",
		[2] = "Optimizations",
		[3] = "Configurations",
	},
	GameVersion = "1.0.20.0",
	DefaultSettings = {
		[1] = {
			SettingType = "Toggle",
			Key = "Enabled",
			DisplayName = "启用延迟过月",
			Description = "将远离太吾的低风险区域过月任务延迟到游玩帧中分批执行。",
			DefaultValue = true,
		},
		[2] = {
			SettingType = "Toggle",
			Key = "ImmediateNeighborAreas",
			DisplayName = "同步相邻区域",
			Description = "过月时立即结算太吾当前区域的相邻区域，降低短途移动后的补算风险。",
			DefaultValue = true,
		},
		[3] = {
			SettingType = "Slider",
			Key = "FrameBudgetMs",
			DisplayName = "每帧预算毫秒",
			GroupName = nil,
			MinValue = 1,
			MaxValue = 20,
			StepSize = 1,
			DefaultValue = 8,
		},
		[4] = {
			SettingType = "Toggle",
			Key = "DelayEquipment",
			DisplayName = "延迟装备整理",
			Description = "延迟非即时区域 NPC 的装备选择、修理和部分物品准备逻辑。",
			DefaultValue = true,
		},
		[5] = {
			SettingType = "Toggle",
			Key = "DelayMissionGoal",
			DisplayName = "延迟任务目标",
			Description = "延迟非即时区域 NPC 的任务刷新和目标规划刷新。",
			DefaultValue = true,
		},
		[6] = {
			SettingType = "Toggle",
			Key = "DelayLoseOverloadItems",
			DisplayName = "延迟超重丢弃",
			Description = "实验选项：延迟非即时区域 NPC 的超重物品丢弃逻辑。",
			DefaultValue = true,
		},
		[7] = {
			SettingType = "Toggle",
			Key = "DelayBrokenBlocks",
			DisplayName = "延迟破损地块",
			Description = "延迟非即时区域破损地块的每月倒计时更新。",
			DefaultValue = true,
		},
	},
	FileId = 3750430637,
	WorkshopCover = nil,
	Visibility = 0,
	SettingGroups = {
		[1] = "Default",
	},
	UpdateLogList = {
		[1] = {
			Timestamp = 1782234802,
		},
	},
	Cover = nil,
}
