return {
	BackendPlugins = {
		[1] = "TaiwuOptimization.dll",
	},
	FrontendPlugins = {
		[1] = "TaiwuOptimizationFront.dll",
	},
	Title = "[天幕心帷]过月性能优化",
	Version = "0.1.6.0",
	Author = "man!",
	Description = " [h1] 过月性能优化 [/h1]\n\n[h2]兼容更新#260624[/h2]\n\n已修复退出至主界面时的红字报错，pending队列在退出世界前会清空，同时不再触发/延迟原版保存世界行为。\n\n在原版执行保存世界前将确保pending队列中的任务完全执行完毕以维护存档一致性。\n\n\n将部分远离太吾当前位置的低风险过月任务，延迟到过月后的帧中分批执行，减少点击过月时的集中卡顿。\n\n当前[i]（无论何时，包括快速旅行时）[/i]州域始终同步结算，可选同步结算相邻州域，避免太吾附近区域出现状态滞后。\n\n[h3][b]不会影响原版存档执行次序/执行屏障/二进制读写！可在已有存档中自由加入/取消本mod。[/b][/h3]\n\n[list] [h2]当前可用延迟[/h2]\n[*] 部分远区 NPC 普通月行动/准备行动\n[*] 破损地块恢复倒计时\n[*] 野生动物生态更新\n[*] 坟墓僵尸生成\n[*] 地图拾取物状态更新\n[/list]\n\n[b] 使用 Harmony Patch，可能(大概率)与修改以上逻辑的mod冲突。[/b]\n\n[spoiler]PS:根据我个人反编译出来的后端源码，螺舟把月结计算全部压在太吾点击下个月按钮后触发的AdvanceMonth函数里，这函数各个阶段虽然内部并行但是写回世界数据的时候是串行。瓶颈就在这里。以原版太吾绘卷这样的后端设计想要减少月结等待时间就只能把这个月的计算延迟到月结后。\n\n个人认为理想的情况应该是这个月开始的时候使用帧预算计算太吾不行动时下个月的世界快照，然后月结只根据太吾本月实际行动产生的diff更新原来的快照。\n\n而且一个按钮就得让橡树化身守电脑前硬等这对吗？\n[/spoiler] ",
	Source = 0,
	HasArchive = false,
	NeedRestartWhenSettingChanged = false,
	ChangeConfig = false,
	TagList = {
		[1] = "Compatible Mods",
		[2] = "Optimizations",
	},
	GameVersion = "1.0.24.0",
	DefaultSettings = {
		[1] = {
			SettingType = "Toggle",
			Key = "Enabled",
			DisplayName = "启用过月优化",
			Description = "启用将使远离太吾的非实时区域中过月任务延迟到过月后与帧中分批执行。",
			DefaultValue = true,
		},
		[2] = {
			SettingType = "Toggle",
			Key = "SyncNeighborStates",
			DisplayName = "相邻州域同步结算",
			Description = "启用将使相邻州域保持同步计算，不参与延迟。",
			DefaultValue = true,
		},
		[3] = {
			SettingType = "Slider",
			Key = "FrameBudgetMs",
			DisplayName = "每帧处理预算(毫秒)",
			Description = "限制每帧最多预留的帧时间。数值越高对帧率影响越大，延迟任务队列清空越快。",
			MinValue = 1,
			MaxValue = 4,
			StepSize = 1,
			DefaultValue = 2,
		},
		[4] = {
			SettingType = "Slider",
			Key = "MaxJobsPerFrame",
			DisplayName = "每帧最多任务数",
			Description = "限制每帧最多处理的延迟任务数。数值越低帧率越平滑，延迟任务队列清空越慢。",
			MinValue = 1,
			MaxValue = 4,
			StepSize = 1,
			DefaultValue = 2,
		},
		[5] = {
			SettingType = "Toggle",
			Key = "DelayEquipment",
			DisplayName = "优化：延迟NPC装备/修理",
			Description = "延迟非实时区域 NPC 的装备选择、修理和部分物品准备逻辑。",
			DefaultValue = true,
		},
		[6] = {
			SettingType = "Toggle",
			Key = "DelayMissionGoal",
			DisplayName = "优化：延迟NPC行为规划",
			Description = "延迟非实时区域 NPC 的任务刷新和目标规划刷新。",
			DefaultValue = true,
		},
		[7] = {
			SettingType = "Toggle",
			Key = "DelayLoseOverloadItems",
			DisplayName = "优化：延迟NPC超重丢弃",
			Description = "延迟非实时区域 NPC 的超重物品丢弃逻辑。",
			DefaultValue = true,
		},
		[8] = {
			SettingType = "Toggle",
			Key = "DelayBrokenBlocks",
			DisplayName = "优化：延迟破损地块倒计时",
			Description = "延迟非实时区域破损地块的每月倒计时更新。",
			DefaultValue = true,
		},
		[9] = {
			SettingType = "Toggle",
			Key = "DelayAnimalAreaData",
			DisplayName = "优化：延迟野生动物生态",
			Description = "延迟非实时区域的野生动物生成和自然死亡结算。",
			DefaultValue = true,
		},
		[10] = {
			SettingType = "Toggle",
			Key = "DelaySkeletonGeneration",
			DisplayName = "优化：延迟坟墓僵尸生成",
			Description = "延迟非实时区域的坟墓僵尸生成。",
			DefaultValue = true,
		},
		[11] = {
			SettingType = "Toggle",
			Key = "DelayMapPickups",
			DisplayName = "优化：延迟拾取物状态刷新",
			Description = "延迟非实时区域的地图拾取可见性刷新和已忽略状态清理。",
			DefaultValue = true,
		},
	},
	FileId = 3750430637,
	Visibility = 0,
	SettingGroups = {
		[1] = "Default",
	},
	UpdateLogList = {
		[1] = {
			Timestamp = 1782234802,
		},
		[2] = {
			Timestamp = 1782235028,
		},
		[3] = {
			Timestamp = 1782247859,
		},
		[4] = {
			Timestamp = 1782248233,
		},
		[5] = {
			Timestamp = 1782248252,
		},
		[6] = {
			Timestamp = 1782257461,
		},
		[7] = {
			Timestamp = 1782258542,
		},
	},
	Cover = "c04bb314ab8daa46832bb42193ddebfb.jpg",
	WorkshopCover = "c04bb314ab8daa46832bb42193ddebfb.jpg",
}
