return {
	AdvanceMonthOptimizationEnabled = true,
	EnableCharacterActionPlanningOptimization = true,
	EnableSaveWorldParallelDeflate = true,
	SaveWorldBlockSizeTier = 3,
	ReduceRemoteNpcOfflineCurrentGoalActionPointGain = false,
	RemoteNpcOfflineCurrentGoalActionPointGainReduction = 10,
	ProtectNeighborStatesForAdvanceMonthOptimization = true,
	EnableAdvanceMonthOptimizationFrameBudget = true,
	AdvanceMonthOptimizationFrameBudgetMs = 2,
	ProtectTaiwuVillageResidentsFromOfflineActionPointReduction = true,
	ProtectSectMembersFromOfflineActionPointReduction = true,
	AdvanceMonthOptimizationDiagnosticsEnabled = false,
	EnableTaiwuDiagnosticsServer = true,
	AutoOpenTaiwuDiagnosticsDashboard = false,
	TaiwuDiagnosticsPort = 18580,
	DiagnosticsLogToGameLog = false,
	DiagnosticsSaveSnapshotOnSave = true,
	DiagnosticsSnapshotMaxCount = 5,
}
