return {
	Enabled = true,
	SyncNeighborStates = true,
	FrameBudgetMs = 1,
	DelayEquipment = true,
	DelayMissionGoal = true,
	DelayLoseOverloadItems = true,
	DelayBrokenBlocks = true,
	DelayMapMonthlyUpdate = true,
	DelayRandomEnemies = true,
	DelayNpcTaming = true,
	DelayAnimalAreaData = true,
	DelaySkeletonGeneration = true,
	DelayMapPickups = true,
}
