<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>GameData.Shared</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>netstandard2.1</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>15.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup />
  <ItemGroup />
  <ItemGroup>
    <Reference Include="GameData.Utilities">
      <HintPath>D:\SteamLibrary\steamapps\common\The Scroll Of Taiwu\Backend\GameData.Utilities.dll</HintPath>
    </Reference>
    <Reference Include="GameData.Serializer">
      <HintPath>D:\SteamLibrary\steamapps\common\The Scroll Of Taiwu\Backend\GameData.Serializer.dll</HintPath>
    </Reference>
    <Reference Include="GameData.Combat.Cricket">
      <HintPath>D:\SteamLibrary\steamapps\common\The Scroll Of Taiwu\Backend\GameData.Combat.Cricket.dll</HintPath>
    </Reference>
    <Reference Include="GameData.ActionPlanning">
      <HintPath>D:\SteamLibrary\steamapps\common\The Scroll Of Taiwu\Backend\GameData.ActionPlanning.dll</HintPath>
    </Reference>
    <Reference Include="GameData.Combat.Math">
      <HintPath>D:\SteamLibrary\steamapps\common\The Scroll Of Taiwu\Backend\GameData.Combat.Math.dll</HintPath>
    </Reference>
    <Reference Include="Redzen">
      <HintPath>D:\SteamLibrary\steamapps\common\The Scroll Of Taiwu\Backend\Redzen.dll</HintPath>
    </Reference>
    <Reference Include="GameData.Adventure">
      <HintPath>D:\SteamLibrary\steamapps\common\The Scroll Of Taiwu\Backend\GameData.Adventure.dll</HintPath>
    </Reference>
    <Reference Include="GameData.Common">
      <HintPath>D:\SteamLibrary\steamapps\common\The Scroll Of Taiwu\Backend\GameData.Common.dll</HintPath>
    </Reference>
    <Reference Include="GameData.Utilities.Structure">
      <HintPath>D:\SteamLibrary\steamapps\common\The Scroll Of Taiwu\Backend\GameData.Utilities.Structure.dll</HintPath>
    </Reference>
    <Reference Include="SourceGenerator.Core">
      <HintPath>D:\SteamLibrary\steamapps\common\The Scroll Of Taiwu\Backend\SourceGenerator.Core.dll</HintPath>
    </Reference>
    <Reference Include="MoonSharp.Interpreter">
      <HintPath>D:\SteamLibrary\steamapps\common\The Scroll Of Taiwu\Backend\MoonSharp.Interpreter.dll</HintPath>
    </Reference>
    <Reference Include="Google.Protobuf">
      <HintPath>D:\SteamLibrary\steamapps\common\The Scroll Of Taiwu\Backend\Google.Protobuf.dll</HintPath>
    </Reference>
    <Reference Include="GameData.Common.Algorithm">
      <HintPath>D:\SteamLibrary\steamapps\common\The Scroll Of Taiwu\Backend\GameData.Common.Algorithm.dll</HintPath>
    </Reference>
    <Reference Include="TaiwuModdingLib">
      <HintPath>D:\SteamLibrary\steamapps\common\The Scroll Of Taiwu\Backend\TaiwuModdingLib.dll</HintPath>
    </Reference>
    <Reference Include="GameData.Utilities.Reflection">
      <HintPath>D:\SteamLibrary\steamapps\common\The Scroll Of Taiwu\Backend\GameData.Utilities.Reflection.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>