<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>GameData.ActionPlanning.ActionImpl</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>15.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup />
  <ItemGroup />
  <ItemGroup>
    <Reference Include="SourceGenerator.Core">
      <HintPath>D:\SteamLibrary\steamapps\common\The Scroll Of Taiwu\Backend\SourceGenerator.Core.dll</HintPath>
    </Reference>
    <Reference Include="GameData">
      <HintPath>D:\SteamLibrary\steamapps\common\The Scroll Of Taiwu\Backend\GameData.dll</HintPath>
    </Reference>
    <Reference Include="GameData.Shared">
      <HintPath>D:\SteamLibrary\steamapps\common\The Scroll Of Taiwu\Backend\GameData.Shared.dll</HintPath>
    </Reference>
    <Reference Include="GameData.Serializer">
      <HintPath>D:\SteamLibrary\steamapps\common\The Scroll Of Taiwu\Backend\GameData.Serializer.dll</HintPath>
    </Reference>
    <Reference Include="GameData.Utilities">
      <HintPath>D:\SteamLibrary\steamapps\common\The Scroll Of Taiwu\Backend\GameData.Utilities.dll</HintPath>
    </Reference>
    <Reference Include="GameData.Combat.Math">
      <HintPath>D:\SteamLibrary\steamapps\common\The Scroll Of Taiwu\Backend\GameData.Combat.Math.dll</HintPath>
    </Reference>
    <Reference Include="Redzen">
      <HintPath>D:\SteamLibrary\steamapps\common\The Scroll Of Taiwu\Backend\Redzen.dll</HintPath>
    </Reference>
    <Reference Include="GameData.SecretInformation">
      <HintPath>D:\SteamLibrary\steamapps\common\The Scroll Of Taiwu\Backend\GameData.SecretInformation.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>